Repository dataease/dataease, pull requests merged in 2021-11, with the labels that each got.

#1080 fix: 仪表板链接跳转配置白名单
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
Labels: 类型:bug

#1082 feat:瀑布图
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1085 fix: ldap忽略大小写
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:bug

#1087 feat:视图默认返回1000条数据；doris默认不排序
  backend/src/main/java/io/dataease/provider/QueryProvider.java
  backend/src/main/java/io/dataease/provider/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:新功能

#1088 fix: ldap用户姓名为空
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:bug

#1089 feat: 开源版用户列表隐藏角色和组织
  frontend/src/views/system/user/form.vue
  frontend/src/views/system/user/index.vue
Labels: 类型:新功能

#1090 fix:flyway
  backend/src/main/resources/db/migration/V27__de1.4.sql
Labels: 类型:bug

#1091 feat: 用户管理姓名字段增加重复验证
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/plugins/server/SSOServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:新功能

#1092 refactor: 数据集名称字段长度
  backend/src/main/resources/db/migration/V27__de1.4.sql
Labels: 类型:优化

#1093 feat:瀑布图
  frontend/src/views/chart/chart/waterfall/waterfall.js
Labels: 类型:新功能

#1094 refactor: 优化公共链接参数长度
  backend/src/main/java/io/dataease/auth/filter/F2CLinkFilter.java
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  frontend/src/utils/rsaEncrypt.js
  frontend/src/views/link/generate/index.vue
  frontend/src/views/link/pwd/index.vue
  frontend/src/views/link/view/index.vue
  frontend/src/views/login/index.vue
Labels: 类型:优化

#1099 feat:调色板默认色
  frontend/src/views/chart/chart/chart.js
Labels: 类型:新功能

#1100 feat:调色板默认色
  frontend/src/views/chart/chart/chart.js
Labels: 类型:新功能

#1104 fix: 指针图图例修复
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#1105 fix: 指针图图例修复
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#1106 feat:词云
  frontend/src/icons/svg/word-cloud.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/waterfall/waterfall.js
  frontend/src/views/chart/chart/wordCloud/word_cloud.js
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartType.vue
Labels: 类型:新功能

#1107 feat:词云
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1108 fix: 修复系统管理api
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/base/domain/SysMsgChannel.java
  backend/src/main/java/io/dataease/base/domain/SysMsgSetting.java
  backend/src/main/java/io/dataease/base/domain/SysMsgType.java
  backend/src/main/java/io/dataease/base/domain/SysUser.java
  backend/src/main/java/io/dataease/controller/IndexController.java
  backend/src/main/java/io/dataease/controller/response/ExistLdapUser.java
  backend/src/main/java/io/dataease/controller/sys/MsgController.java
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/controller/sys/base/BaseGridRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/MsgRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/SysUserCreateRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/SysUserPwdRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/SysUserStateRequest.java
  backend/src/main/java/io/dataease/controller/sys/response/SettingTreeNode.java
  frontend/src/api/system/msg.js
  frontend/src/components/Notification/index.vue
Labels: 类型:bug

#1109 fix: 公共链接分享老密码过长
  backend/src/main/resources/db/migration/V27__de1.4.sql
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/link/generate/index.vue
  frontend/src/views/system/user/imp-ldap.vue
Labels: 类型:bug

#1110 refactor: 轴线自定义刻度数限制不超过100
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue
Labels: 类型:优化

#1111 refactor: 轴线自定义刻度数限制不超过100
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue
Labels: 类型:优化

#1112 refactor: 轴线自定义刻度数限制不超过100
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue
Labels: 类型:优化

#1114 fix: 黑色主题选色板逻辑错误
  frontend/src/styles/index.scss
Labels: 类型:bug

#1116 fix: rollback，数据集处的doris仍需要分页
  backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
Labels: 类型:bug

#1060 refactor:仪表板刷新到秒级别
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/SubjectSetting/PanelStyle/PanelRefreshTime.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/panel/panel.js
Labels: 类型:优化

#1119 refactor: 编辑数据集，字段不会删除重建
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:优化

#1121 fix: 视图指标卡标题位置修复
  frontend/src/views/chart/components/component-style/TitleSelector.vue
Labels: 类型:bug

#1122 fix: 视图指标卡标题位置修复
  frontend/src/views/chart/components/component-style/TitleSelector.vue
Labels: 类型:bug

#1123 fix: 视图指标卡标题位置修复
  frontend/src/views/chart/components/component-style/TitleSelector.vue
Labels: 类型:bug

#1129 refactor: 优化仪表板时间组件
  frontend/src/components/canvas/components/Editor/DateFormat.vue
  frontend/src/components/widget/DeWidget/TimeSimple.vue
Labels: 类型:优化

#1130 refactor: 瀑布图图例文字优化
  frontend/src/views/chart/chart/waterfall/waterfall.js
Labels: 类型:优化

#1131 refactor: 瀑布图图例文字优化
  frontend/src/views/chart/chart/waterfall/waterfall.js
Labels: 类型:优化

#1136 refactor: 重构代码
  backend/src/main/java/io/dataease/auth/config/F2CRealm.java
Labels: 类型:优化

#1137 refactor: 重构提示信息
  backend/src/main/java/io/dataease/auth/config/F2CRealm.java
Labels: 类型:优化

#1139 feat:词云
  frontend/src/views/chart/view/ChartType.vue
Labels: 类型:新功能

#1143 feat:视图根据图表类型分类
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartType.vue
Labels: 类型:新功能

#1149 feat:视图根据图表类型分类
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1148 refactor:优化授权查询模型
  backend/src/main/java/io/dataease/base/domain/VAuthModel.java
  backend/src/main/java/io/dataease/base/domain/VAuthModelExample.java
  backend/src/main/java/io/dataease/base/domain/VAuthModelWithBLOBs.java
  backend/src/main/java/io/dataease/base/mapper/VAuthModelMapper.java
  backend/src/main/java/io/dataease/base/mapper/VAuthModelMapper.xml
  backend/src/main/java/io/dataease/controller/authModel/VAuthModelController.java
  backend/src/main/java/io/dataease/dto/authModel/VAuthModelDTO.java
  backend/src/main/resources/generatorConfig.xml
  frontend/package.json
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/VideoLinks.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/custom-component/DeVideo.vue
  frontend/src/components/canvas/custom-component/component-list.js
  frontend/src/components/canvas/custom-component/index.js
  frontend/src/custom-theme.css
  frontend/src/main.js
  frontend/src/store/index.js
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
  frontend/src/views/panel/AssistComponent/index.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/video/index.vue
Labels: 类型:优化

#1150 feat(数据集):数据集字段管理页面，增加同步字段功能
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/data/FieldEdit.vue
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#1154 feat: 新增我分享的
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml
  backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
  backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  backend/src/main/resources/db/migration/V28__de1.5.sql
  frontend/src/api/panel/share.js
  frontend/src/views/panel/GrantAuth/role/index.vue
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/GrantAuth/user/index.vue
Labels: 类型:新功能

#1156 feat(数据集):数据集字段管理页面，增加同步字段功能
  frontend/src/views/dataset/data/FieldEdit.vue
  frontend/src/views/dataset/data/UnionView.vue
Labels: 类型:新功能

#1158 feat(视图):视图保留实时计算与渲染功能，但不实时保存，提供保存与重置按钮
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/controller/request/chart/ChartCalRequest.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1159 feat(视图):视图保留实时计算与渲染功能，但不实时保存，提供保存与重置按钮
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:新功能

#1160 feat(视图):视图保留实时计算与渲染功能，但不实时保存，提供保存与重置按钮
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1161 feat(视图):视图保留实时计算与渲染功能，但不实时保存，提供保存与重置按钮
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1162 feat(视图):视图保留实时计算与渲染功能，但不实时保存，提供保存与重置按钮
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1163 feat: 完善我的分享
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml
  backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
  backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelShareRemoveRequest.java
  backend/src/main/java/io/dataease/dto/panel/PanelShareOutDTO.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  frontend/src/api/panel/share.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/GrantAuth/ShareHead/index.vue
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/enshrine/index.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:新功能

#1172 fix: 前端用户列表控制台报错
  frontend/public/fonts/element-icons.ttf
  frontend/public/fonts/element-icons.woff
  frontend/src/components/AsyncComponent/index.vue
  frontend/src/views/link/generate/index.vue
  frontend/src/views/system/user/form.vue
  frontend/src/views/system/user/index.vue
Labels: 类型:bug

#1175 feat(数据集):数据集字段管理页面，增加同步字段功能
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:新功能

#1176 feat: 完善公共链接
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/base/domain/PanelLinkMapping.java
  backend/src/main/java/io/dataease/base/domain/PanelLinkMappingExample.java
  backend/src/main/java/io/dataease/base/mapper/PanelLinkMappingMapper.java
  backend/src/main/java/io/dataease/base/mapper/PanelLinkMappingMapper.xml
  backend/src/main/java/io/dataease/controller/IndexController.java
  backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java
  backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java
  backend/src/main/java/io/dataease/controller/request/panel/link/LinkValidateRequest.java
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  backend/src/main/resources/db/migration/V28__de1.5.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/src/utils/index.js
  frontend/src/views/link/generate/index.vue
  frontend/src/views/link/index.vue
Labels: 类型:新功能

#1182 refactor:修改仪表板按钮样式
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:优化

#1204 feat: 消息订阅增加邮件渠道
  backend/src/main/java/io/dataease/base/domain/SysMsgChannel.java
  backend/src/main/java/io/dataease/base/domain/SysMsgChannelExample.java
  backend/src/main/java/io/dataease/base/mapper/SysMsgChannelMapper.xml
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  backend/src/main/java/io/dataease/service/message/DeMsgutil.java
  backend/src/main/java/io/dataease/service/message/MsgAop.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
  backend/src/main/java/io/dataease/service/message/service/SendService.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendEmail.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendStation.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  backend/src/main/java/io/dataease/service/system/EmailService.java
  backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  backend/src/main/resources/db/migration/V28__de1.5.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/src/views/msg/setting.vue
  frontend/src/views/system/SysParam/index.vue
Labels: 类型:新功能

#1205 refactor:仪表板视图联动，使用相同数据集的视图，自动补充联动字段
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/api/chart/chart.js
  frontend/src/components/canvas/components/Editor/LinkageField.vue
Labels: 类型:优化

#1206 refactor: 删除非必要注释
  backend/src/main/java/io/dataease/auth/api/AuthApi.java
  backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
  backend/src/main/java/io/dataease/commons/condition/LicStatusCondition.java
  backend/src/main/java/io/dataease/commons/license/DefaultLicenseService.java
  backend/src/main/java/io/dataease/commons/utils/CodingUtil.java
  backend/src/main/java/io/dataease/commons/utils/DateUtils.java
  backend/src/main/java/io/dataease/controller/handler/RestControllerExceptionHandler.java
  backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
  backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java
  backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java
  backend/src/main/java/io/dataease/controller/panel/server/ViewServer.java
  backend/src/main/java/io/dataease/controller/sys/SysDeptController.java
  backend/src/main/java/io/dataease/controller/sys/SysRoleController.java
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/map/utils/MapUtils.java
  backend/src/main/java/io/dataease/plugins/server/XUserKeysServer.java
  backend/src/main/java/io/dataease/provider/datasource/EsProvider.java
  backend/src/main/java/io/dataease/service/FileService.java
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  backend/src/main/java/io/dataease/service/panel/StoreService.java
  backend/src/main/java/io/dataease/service/sys/PluginService.java
  backend/src/main/java/io/dataease/service/sys/SysRoleService.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
  backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  backend/src/main/java/io/dataease/websocket/ServerEndpointConfigurator.java
  backend/src/main/java/io/dataease/websocket/WebSocketServer.java
Labels: 类型:优化

#1209 fix:部分电脑键盘全屏按键仪表板下方存在空白问题
  frontend/src/components/canvas/components/Editor/Preview.vue
Labels: 类型:bug

#1211 fix:sqlserver计算字段bug
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:bug

#1220 feat(数据集):关联数据集
  frontend/src/icons/svg/inner-join.svg
  frontend/src/icons/svg/left-join.svg
  frontend/src/icons/svg/right-join.svg
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/dataset/index.vue
Labels: 类型:新功能

#1240 feat: 整合邮件和截图
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/service/system/EmailService.java
Labels: 类型:新功能

#1243 fix: 修复仪表板编辑按钮权限取值不对问题
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#1244 refactor: 文案修改，仪表板拖拽上传组件修改为图片
  frontend/src/components/canvas/custom-component/component-list.js
Labels: 类型:优化

#1245 refactor: 移除画布设计时滚动条，优化设计体验
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#1247 refactor: 优化仪表板展示边界间隙，保持常有间隙
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/dataease/DeOutWidget.vue
Labels: 类型:优化

#1249 Pr@dev@feat panel mobile
  frontend/package.json
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/MobileCheckBar.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/custom-component/component-list.js
  frontend/src/components/canvas/utils/utils.js
  frontend/src/main.js
  frontend/src/store/index.js
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
  frontend/src/views/panel/edit/ComponentWait.vue
  frontend/src/views/panel/edit/ComponentWaitItem.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:新功能

#1252 fix(视图): 修复图表类型切换逻辑
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#1254 fix(视图): 修复图表类型切换逻辑
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#1256 feat(数据集): 关联数据集
  frontend/src/icons/svg/ds-union.svg
  frontend/src/icons/svg/no-join.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/index.scss
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/dataset/add/union/NodeItem.vue
  frontend/src/views/dataset/add/union/UnionNode.vue
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:新功能

#1258 feat: 定时报告sql语句
  backend/src/main/resources/db/migration/V28__de1.5.sql
Labels: 类型:新功能

#1259 refactor: 格式化代码
  backend/src/main/java/io/dataease/commons/utils/ServletUtils.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/TaskStrategyFactory.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/java/io/dataease/service/system/EmailService.java
Labels: 类型:优化

#1261 feat: 仪表板支持统一设置视图结果显示数量
  backend/src/main/java/io/dataease/commons/constants/CommonConstants.java
  backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/SubjectSetting/PanelStyle/ComponentGap.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/PanelRefreshTime.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/PanelViewResult.vue
  frontend/src/views/panel/SubjectSetting/index.vue
  frontend/src/views/panel/panel.js
Labels: 类型:新功能

#1262 fix: 默认仪表板不需要显示编辑按钮
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#1263 fix: 定时报告flyway逻辑错误
  backend/src/main/resources/db/migration/V28__de1.5.sql
Labels: 类型:bug

#1264 feat: 替换数据同步任务图标
  frontend/src/icons/svg/dataset-task.svg
Labels: 类型:新功能

#1267 refactor: 树形列表统一使用拼音排序规则
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartGroupMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetGroupMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelGroupMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
  frontend/src/api/authModel/authModel.js
Labels: 类型:优化

#1268 fix: 升级sass版本
  frontend/package.json
Labels: 类型:bug

#1269 refactor: 添加flyway
  backend/src/main/resources/db/migration/V28__de1.5.sql
Labels: 类型:优化

#1272 fix: 仪表板下拉列表组件显示异常
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1273 fix: 时钟组件边框属性导致背景下移
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/custom-component/component-list.js
  frontend/src/components/canvas/utils/style.js
Labels: 类型:bug

#1276 refactor: 屏蔽移动端布局功能
  frontend/src/components/canvas/components/Toolbar.vue
Labels: 类型:优化

#1279 refactor: 优化顶部餐单栏隐藏条件
  frontend/src/layout/index.vue
  frontend/src/views/panel/index.vue
Labels: 类型:优化

#1282 fix: 修复简单表盘复制后不显示问题
  frontend/src/components/widget/DeWidget/DeShowDate.vue
  frontend/src/components/widget/DeWidget/TimeComplex.vue
  frontend/src/components/widget/DeWidget/TimeSimple.vue
Labels: 类型:bug

#1284 fix: 前端改为单页面应用
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/controller/IndexController.java
  backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  frontend/public/link.html
  frontend/public/nolic.html
  frontend/src/link/Link.vue
  frontend/src/link/link-router.js
  frontend/src/link/link.js
  frontend/src/nolic/Nolic.vue
  frontend/src/nolic/nolic-router.js
  frontend/src/nolic/nolic.js
  frontend/src/permission.js
  frontend/src/router/index.js
  frontend/src/views/link/index.vue
  frontend/src/views/nolic/index.vue
  frontend/vue.config.js
Labels: 类型:bug

#1286 fix: token验签逻辑错误
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
  backend/src/main/java/io/dataease/auth/util/JWTUtils.java
Labels: 类型:bug

#1288 fix: 放开excel上传api
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
Labels: 类型:bug

#1290 refactor: 公共链接方法名称
  backend/src/main/java/io/dataease/controller/IndexController.java
Labels: 类型:优化

#1293 refactor: 优化数据集查询树
  backend/src/main/java/io/dataease/base/domain/VAuthModel.java
  backend/src/main/java/io/dataease/base/domain/VAuthModelExample.java
  backend/src/main/java/io/dataease/base/mapper/VAuthModelMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
Labels: 类型:优化

#1294 refactor: 优化数据集查询树
  backend/src/main/resources/db/migration/V28__de1.5.sql
Labels: 类型:优化

#1296 fix(数据集): 编辑数据集可能会出现重复字段
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#1297 fix(数据集): 编辑数据集可能会出现重复字段
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#1301 fix: 我分享的没有及时刷新
  frontend/src/views/panel/GrantAuth/ShareHead/index.vue
  frontend/src/views/panel/GrantAuth/dept/index.vue
  frontend/src/views/panel/GrantAuth/index.vue
  frontend/src/views/panel/GrantAuth/role/index.vue
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/GrantAuth/user/index.vue
  frontend/src/views/panel/list/PanelMain.vue
Labels: 类型:bug

#1303 fix: 公共链接分享密码错误提示位置覆盖
  frontend/src/views/link/pwd/index.vue
Labels: 类型:bug

#1304 fix: 多个时间控件相互影响
  frontend/src/components/widget/DeWidget/TimeSimple.vue
Labels: 类型:bug

#1306 refactor: 前端增加菜单缓存，加快相应速度
  frontend/src/api/authModel/authModel.js
  frontend/src/api/chart/chart.js
  frontend/src/api/panel/panel.js
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/login/index.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:优化

#1307 fix(视图): 修复图表类型有时样式错乱
  frontend/src/styles/index.scss
  frontend/src/views/chart/view/ChartType.vue
Labels: 类型:bug

#1312 refactor: 仪表板视图过滤弹框，去掉搜索条件时无需关闭
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#1313 fix: 条件组件弹框样式
  frontend/src/styles/index.scss
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:bug

#1315 fix: 条件组件弹框样式
  frontend/src/styles/index.scss
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:bug

#1316 feat(数据集): 关联数据集
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/dataset/add/union/NodeItem.vue
  frontend/src/views/dataset/add/union/UnionNode.vue
Labels: 类型:新功能

#1318 refactor: 过滤组件样式边界优化
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/DeVideo.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/filterDialog.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:优化

#1319 feat(数据集): 关联数据集
  frontend/src/views/dataset/add/union/UnionItemEdit.vue
Labels: 类型:新功能

#1320 refactor: 代码回退
  frontend/src/components/canvas/components/Editor/index.vue
Labels: 类型:优化

#1322 refactor: 增加权限模型字段优化查询条件
  backend/src/main/java/io/dataease/base/domain/VAuthModel.java
  backend/src/main/java/io/dataease/base/domain/VAuthModelExample.java
  backend/src/main/java/io/dataease/base/mapper/VAuthModelMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
  backend/src/main/java/io/dataease/controller/request/authModel/VAuthModelRequest.java
  backend/src/main/resources/db/migration/V28__de1.5.sql
Labels: 类型:优化

#1323 refactor: 增加权限模型字段优化查询条件
  backend/src/main/java/io/dataease/base/domain/VAuthModel.java
  backend/src/main/java/io/dataease/base/domain/VAuthModelExample.java
  backend/src/main/java/io/dataease/base/mapper/VAuthModelMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
  backend/src/main/java/io/dataease/controller/request/authModel/VAuthModelRequest.java
  backend/src/main/resources/db/migration/V28__de1.5.sql
Labels: 类型:优化

#1324 fix: 文本组件根据仪表板缩放比例自动缩放文本大小和间隙，防止编辑和预览不一致
  frontend/src/components/canvas/components/Editor/Preview.vue
Labels: 类型:bug

#1325 fix(权限): 统一授权数据集tree
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
Labels: 类型:bug

#1326 fix(权限): 统一授权数据集tree
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
Labels: 类型:bug

#1329 fix: 优化仪表板编辑时，边界可能间隙不一致
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/layout/index.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#1330 feat(数据集): 关联数据集
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/dataset/add/union/NodeItem.vue
  frontend/src/views/dataset/add/union/UnionNode.vue
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#1332 fix: 过滤组件修改标题字间距选项会跟着一起改变间距问题
  frontend/src/components/dataease/DeOutWidget.vue
Labels: 类型:bug

#1333 feat(数据集): 关联数据集
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/dataset/common/DatasetChartDetail.vue
Labels: 类型:新功能

#1336 feat(权限): 统一授权数据集tree
  backend/src/main/java/io/dataease/service/authModel/VAuthModelService.java
Labels: 类型:新功能

#1342 refactor: v1.5关闭关联数据集入口
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:优化
