Repository dataease/dataease, pull requests merged in 2021-08, with the labels that each got.

#456 feat: 补齐api
  backend/src/main/java/io/dataease/auth/api/AuthApi.java
  backend/src/main/java/io/dataease/auth/api/DynamicMenuApi.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.xml
  backend/src/main/java/io/dataease/controller/chart/ChartController.java
  backend/src/main/java/io/dataease/controller/chart/ChartGroupController.java
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskLogController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableUnionController.java
  backend/src/main/java/io/dataease/controller/dataset/DatasetFunctionController.java
  backend/src/main/java/io/dataease/controller/panel/PanelDesignController.java
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/panel/PanelSubjectController.java
  backend/src/main/java/io/dataease/controller/panel/PanelTemplateController.java
  backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java
  backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
  backend/src/main/java/io/dataease/controller/panel/api/StoreApi.java
  backend/src/main/java/io/dataease/controller/panel/api/ViewApi.java
  backend/src/main/java/io/dataease/controller/sys/AboutController.java
  backend/src/main/java/io/dataease/controller/sys/CommonFilesController.java
  backend/src/main/java/io/dataease/controller/sys/DisplayController.java
  backend/src/main/java/io/dataease/controller/sys/I18nController.java
  backend/src/main/java/io/dataease/controller/sys/LicenseController.java
  backend/src/main/java/io/dataease/controller/sys/MsgController.java
  backend/src/main/java/io/dataease/controller/sys/SysDeptController.java
  backend/src/main/java/io/dataease/controller/sys/SysMenuController.java
  backend/src/main/java/io/dataease/controller/sys/SysPluginController.java
  backend/src/main/java/io/dataease/controller/sys/SysRoleController.java
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  backend/src/main/java/io/dataease/controller/sys/request/BatchSettingRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/MsgRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/MsgSettingRequest.java
  backend/src/main/java/io/dataease/controller/sys/response/MsgGridDto.java
  backend/src/main/java/io/dataease/controller/sys/response/SettingTreeNode.java
  backend/src/main/java/io/dataease/controller/sys/response/SubscribeNode.java
  backend/src/main/java/io/dataease/datasource/controller/DatasourceController.java
  backend/src/main/java/io/dataease/service/message/MsgAop.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
Labels: 类型:新功能

#457 fix: 公共链接分享未启用密码保护出现空白页面
  backend/src/main/java/io/dataease/auth/filter/F2CLinkFilter.java
Labels: 类型:bug

#458 fix: 去除已读消息搜索
  frontend/src/views/msg/readed.vue
Labels: 类型:bug

#459 feat: 字段支持公式计算
  backend/src/main/java/io/dataease/dto/chart/ChartViewFieldDTO.java
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:新功能

#461 feat: 去除openApi
  backend/src/main/resources/application.properties
Labels: 类型:新功能

#462 refactor: tree编辑后右侧界面保持原状态
  frontend/src/views/chart/group/Group.vue
Labels: 类型:优化

#463 feat: 支持字段编辑
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
Labels: 类型:新功能

#464 fix: 视图维度指标显示错误
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#467 feat: 完善全局token
  backend/pom.xml
  backend/src/main/java/io/dataease/config/Knife4jConfiguration.java
  backend/src/main/resources/application.properties
Labels: 类型:新功能

#468 fix: 关联字段数据集及时刷新
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
  frontend/src/views/dataset/data/UnionView.vue
Labels: 类型:bug

#469 fix: 关联字段数据集及时刷新
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
  frontend/src/views/dataset/data/UnionView.vue
Labels: 类型:bug

#470 fix: token过期点击确定没有跳转到登录
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  frontend/src/components/Notification/index.vue
Labels: 类型:bug

#471 feat: 搜索优化
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/common/DatasetGroupSelector.vue
  frontend/src/views/dataset/data/CalcFieldEdit.vue
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:新功能

#473 fix: 资源权限逻辑错误
  backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
Labels: 类型:bug

#474 fix: maven打包错误，指定maven-resources-plugin版本解决
  backend/pom.xml
Labels: 类型:bug

#475 fix: 雷达图tooltip
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/radar/radar.js
Labels: 类型:bug

#476 fix: 雷达图tooltip
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/radar/radar.js
Labels: 类型:bug

#479 fix: 解决冲突
  frontend/src/utils/request.js
Labels: 类型:bug

#480 feat:预览界面点击组件显示设置入口，点击空白也取消设置入口；去掉原有鼠标移入显示的样式
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:新功能

#481 fix: 标签引导线修复
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
Labels: 类型:bug

#482 fix: 雷达图数据结构
  frontend/src/views/chart/chart/radar/radar.js
Labels: 类型:bug

#483 fix: 雷达图数据结构
  frontend/src/views/chart/chart/radar/radar.js
Labels: 类型:bug

#487 fix:仪表板样式修改保存按钮还是灰的问题
  frontend/src/components/DeDrag/DragShadow.vue
  frontend/src/components/canvas/components/Editor/index.vue
Labels: 类型:bug

#488 feat: 函数库flyway
  backend/src/main/resources/db/migration/V18__area_mapping.sql
Labels: 类型:新功能

#491 refactor: 编辑字段样式调整
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:优化

#492 fix: 解决国际化冲突
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/utils/request.js
Labels: 类型:bug

#493 fix: 打包后样式错误
  backend/pom.xml
Labels: 类型:bug

#494 feat: 函数库flyway
  backend/src/main/resources/db/migration/V18__area_mapping.sql
Labels: 类型:新功能

#495 fix: 字段编辑修复
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:bug

#497 feat: 函数库flyway
  backend/src/main/resources/db/migration/V18__area_mapping.sql
Labels: 类型:新功能

#501 perf: rest请求优化为json文件请求
  backend/src/main/java/io/dataease/config/WebMvcConfig.java
  frontend/src/api/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:优化

#502 refactor: 堆叠图优化
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:优化

#503 refactor: 去掉多余请求
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#504 refactor: 去掉多余请求;数据集tree修复
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
Labels: 类型:优化

#505 refactor: 数据集tree修复
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
Labels: 类型:优化

#506 refactor: 堆叠项不允许指标拖入
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#508 refactor:仪表板联动设置按钮样式调整
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
Labels: 类型:优化

#512 refactor: tree菜单位置飘移优化
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:优化

#513 refactor: tree菜单位置飘移优化
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:优化

#515 fix: sql注入和xss攻击
  backend/src/main/java/io/dataease/commons/filter/SqlFilter.java
  backend/src/main/java/io/dataease/commons/holder/ThreadLocalContextHolder.java
  backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java
  backend/src/main/java/io/dataease/config/FilterConfig.java
Labels: 类型:bug

#519 fix: sql注入排除减号
  backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java
Labels: 类型:bug

#520 fix: sql注入排除减号
  backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java
Labels: 类型:bug

#521 feat: 视图钻取
  backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java
  backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml
  backend/src/main/resources/db/migration/V18__area_mapping.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#525 feat: 视图下钻
  frontend/src/views/chart/components/drag-item/DrillItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#526 fix: 增加sql注入白名单；sql注入拦截器只验证排序字段
  backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java
  backend/src/main/resources/application.properties
Labels: 类型:bug

#530 fix: flywaysql去除navicat信息
  backend/src/main/resources/db/migration/V14__area_code.sql
Labels: 类型:bug

#531 fix: flywaysql去除重复信息
  backend/src/main/resources/db/migration/V14__area_code.sql
  backend/src/main/resources/db/migration/V18__area_mapping.sql
Labels: 类型:bug

#532 feat: dev版本号升1.2.0
  backend/pom.xml
  frontend/pom.xml
  pom.xml
Labels: 类型:新功能

#533 refactor: Dockerfile中version改为动态
  Dockerfile
Labels: 类型:优化

#534 fix: 恢复flyway误删
  backend/src/main/resources/db/migration/V18__area_mapping.sql
Labels: 类型:bug

#536 refactor: 颜色选择器更换为原生组件
  frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue
  frontend/src/views/chart/components/component-style/LegendSelector.vue
  frontend/src/views/chart/components/component-style/SplitSelector.vue
  frontend/src/views/chart/components/component-style/TitleSelector.vue
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
  frontend/src/views/chart/components/shape-attr/TooltipSelector.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue
Labels: 类型:优化

#537 refactor: 指标卡样式选项优化
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
Labels: 类型:优化

#538 refactor: 指标卡样式选项优化
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
Labels: 类型:优化

#539 refactor:优化联动设置
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.xml
  backend/src/main/java/io/dataease/dto/PanelViewLinkageDTO.java
  backend/src/main/java/io/dataease/service/panel/PanelViewLinkageService.java
Labels: 类型:优化

#547 feat: 散点图、气泡图
  backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java
  backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml
  backend/src/main/java/io/dataease/dto/chart/Series.java
  backend/src/main/java/io/dataease/provider/QueryProvider.java
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/resources/db/migration/V19__area_mapping.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/scatter/scatter.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#548 refactor: scatter优化
  frontend/src/views/chart/chart/chart.js
Labels: 类型:优化

#556 refactor: 视图返回参数构建
  backend/src/main/java/io/dataease/dto/chart/AxisChartDataDTO.java
  backend/src/main/java/io/dataease/dto/chart/ChartDimensionDTO.java
  backend/src/main/java/io/dataease/dto/chart/ChartQuotaDTO.java
  backend/src/main/java/io/dataease/dto/chart/ScatterChartDataDTO.java
  backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/chart/funnel/funnel.js
  frontend/src/views/chart/chart/pie/pie.js
Labels: 类型:优化

#558 feat: 添加ak,sk
  backend/src/main/java/io/dataease/base/domain/UserKey.java
  backend/src/main/java/io/dataease/base/domain/UserKeyExample.java
  backend/src/main/java/io/dataease/base/mapper/UserKeyMapper.java
  backend/src/main/java/io/dataease/base/mapper/UserKeyMapper.xml
  backend/src/main/java/io/dataease/plugins/server/XUserKeysServer.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/components/Topbar.vue
Labels: 类型:新功能

#560 fix: 删除多余代码
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#561 feat: 添加ak,sk的flyway
  backend/src/main/resources/db/migration/V21__user_key.sql
  frontend/src/layout/components/Topbar.vue
Labels: 类型:新功能

#562 feat: 限制矩形图指标数量
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#563 feat: 散点气泡图
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
Labels: 类型:新功能

#566 feat: 矩形树图
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/treemap/treemap.js
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#567 feat: 使用ak，sk访问api接口以及swagger
  backend/src/main/java/io/dataease/auth/config/F2CRealm.java
  backend/src/main/java/io/dataease/auth/entity/ASKToken.java
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
  backend/src/main/java/io/dataease/auth/handler/ApiKeyHandler.java
  backend/src/main/java/io/dataease/commons/utils/CodingUtil.java
  backend/src/main/java/io/dataease/config/Knife4jConfiguration.java
  backend/src/main/resources/application.properties
Labels: 类型:新功能

#568 refactor:仪表版多组件间联动
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.xml
  backend/src/main/java/io/dataease/controller/panel/PanelViewLinkageController.java
  backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java
  backend/src/main/java/io/dataease/dto/LinkageInfoDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/panel/PanelViewLinkageService.java
  frontend/src/api/panel/linkage.js
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/store/copy.js
  frontend/src/store/index.js
  frontend/src/utils/conditionUtil.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/list/EditPanel/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:优化

#569 feat: 视图下钻
  backend/src/main/java/io/dataease/controller/request/chart/ChartDrillRequest.java
  backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java
  backend/src/main/java/io/dataease/dto/chart/ChartViewDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/store/index.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#570 feat: 视图下钻
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#571 feat:怎讲仪表板联动清除按钮
  frontend/src/components/canvas/components/Editor/CanvasOptBar.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/store/index.js
Labels: 类型:新功能

#572 feat: 增加xpack插件内api
  backend/src/main/java/io/dataease/auth/api/dto/CurrentUserDto.java
  backend/src/main/java/io/dataease/auth/entity/SysUserEntity.java
  backend/src/main/java/io/dataease/base/domain/SysMsgChannel.java
  backend/src/main/java/io/dataease/base/domain/SysMsgSetting.java
  backend/src/main/java/io/dataease/base/domain/SysMsgType.java
  backend/src/main/java/io/dataease/base/domain/SysUser.java
  backend/src/main/java/io/dataease/commons/condition/LicStatusCondition.java
  backend/src/main/java/io/dataease/config/Knife4jConfiguration.java
  backend/src/main/java/io/dataease/controller/sys/SysDeptController.java
  backend/src/main/java/io/dataease/controller/sys/SysRoleController.java
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/controller/sys/base/BaseGridRequest.java
  backend/src/main/java/io/dataease/controller/sys/base/ConditionEntity.java
  backend/src/main/java/io/dataease/controller/sys/request/BatchSettingRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/MsgRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/MsgSettingRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/SysUserCreateRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/SysUserPwdRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/SysUserStateRequest.java
  backend/src/main/java/io/dataease/controller/sys/response/SettingTreeNode.java
  backend/src/main/java/io/dataease/plugins/server/PluginCommonServer.java
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
  backend/src/main/java/io/dataease/service/sys/SysRoleService.java
  frontend/src/api/system/dept.js
  frontend/src/api/system/role.js
  frontend/src/api/system/user.js
  frontend/src/views/system/dept/form.vue
  frontend/src/views/system/dept/index.vue
  frontend/src/views/system/role/form.vue
  frontend/src/views/system/role/index.vue
  frontend/src/views/system/user/form.vue
  frontend/src/views/system/user/index.vue
Labels: 类型:新功能

#574 feat: 视图返回字段构建
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/system/map/index.vue
Labels: 类型:新功能

#575 refactor:优化仪表板多视图同时联动效果
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/store/index.js
Labels: 类型:优化

#582 feat: 视图下钻
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/store/index.js
Labels: 类型:新功能

#583 feat: 视图下钻
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#584 fix: 删除xpack api
  backend/src/main/java/io/dataease/config/Knife4jConfiguration.java
Labels: 类型:bug

#585 refactor:增加钻取等图标样式
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/ViewTrackBar.vue
  frontend/src/styles/deicon/demo.css
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
Labels: 类型:优化

#587 feat: 包装api接口文档
  backend/src/main/java/io/dataease/auth/config/ShiroConfig.java
  backend/src/main/java/io/dataease/auth/filter/F2CDocFilter.java
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/controller/IndexController.java
  frontend/public/nolic.html
  frontend/src/nolic/Nolic.vue
  frontend/src/nolic/nolic-router.js
  frontend/src/nolic/nolic.js
  frontend/src/views/nolic/index.vue
  frontend/vue.config.js
Labels: 类型:新功能

#588 fix: 数据集消息获取接受人权限错误
  backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.xml
Labels: 类型:bug

#590 feat: 视图上卷
  backend/src/main/java/io/dataease/dto/chart/ChartViewDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/DrillPath.vue
Labels: 类型:新功能

#593 feat:仪表板支持视图下钻
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:新功能

#595 feat: 视图下钻
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:新功能

#596 feat:仪表板视图根据一个视图是否有多事件来确认是否出现弹框，单事件直接触发
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:新功能

#598 feat:【用户管理】增加根据角色/组织进行查询的支持
  backend/src/main/java/io/dataease/base/mapper/ext/ExtSysUserMapper.xml
  frontend/src/views/system/user/index.vue
Labels: 类型:新功能

#599 refactor:恢复超级管理员无需授权功能
  backend/src/main/resources/db/migration/V22__record_auth_view.sql
Labels: 类型:优化

#600 feat: 地图增加下钻上卷
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#601 feat: 视图下钻
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#602 feat: 堆叠图下钻
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:新功能

#604 fix:前端cosole报错问题
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:bug

#609 feat: 地图缓存 地图联动预留接口
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:新功能

#611 refactor:增加国际化信息
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#613 feat: 视图下钻路径
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#612 feat: 地图联动
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  frontend/src/views/chart/chart/map/map.js
Labels: 类型:新功能

#614 fix: 外部链接token存储使用vuex不实用cookie
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/store/getters.js
  frontend/src/store/modules/user.js
  frontend/src/utils/request.js
Labels: 类型:bug

#615 refactor: 移除注释
  frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue
  frontend/src/views/chart/components/component-style/LegendSelector.vue
  frontend/src/views/chart/components/component-style/SplitSelector.vue
  frontend/src/views/chart/components/component-style/TitleSelector.vue
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/TooltipSelector.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#616 feat: 地图样式
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#617 feat: 地图颜色
  frontend/src/views/chart/chart/map/map.js
Labels: 类型:新功能

#618 refactor:优化仪表板元素拖动，大小变动延迟渲染，移动使用原始dom
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:优化

#619 fix: 外部链接带密码嵌在iframe
  frontend/src/views/link/index.vue
  frontend/src/views/link/pwd/index.vue
Labels: 类型:bug

#620 refactor:优化下钻，联动弹出窗口
  frontend/src/components/canvas/components/Editor/PreviewEject.vue
  frontend/src/views/link/view/index.vue
Labels: 类型:优化

#621 fix: 删除行政区划代码前端缓存
  backend/src/main/java/io/dataease/map/utils/MapUtils.java
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#626 feat: 地图json，区域
  backend/src/main/java/io/dataease/map/utils/MapUtils.java
  backend/src/main/resources/db/migration/V19__area_mapping.sql
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#627 fix: 增加下钻方法返回值
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#628 fix: 地图code，json
  backend/src/main/resources/db/migration/V19__area_mapping.sql
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#629 fix: 地图code
  backend/src/main/resources/db/migration/V19__area_mapping.sql
Labels: 类型:bug

#631 fix: axios异步执行导致地图切换错误
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#632 feat: 文本列表组件增加滚动条
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:新功能

#633 fix: 文本列表组件快速检索无效
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/Shape.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/styles/index.scss
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#634 fix: 组件弹框树节点增加tip
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:bug

#635 feat: 视图支持简单颜色修改
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
Labels: 类型:新功能

#636 feat: 视图支持简单颜色修改
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
Labels: 类型:新功能

#638 feat: 视图支持简单颜色修改
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
Labels: 类型:新功能

#641 feat: 视图支持简单颜色修改
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
Labels: 类型:新功能

#642 refactor: 优化分享组织树
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/service/sys/SysRoleService.java
  frontend/src/api/system/user.js
  frontend/src/views/panel/GrantAuth/dept/index.vue
  frontend/src/views/panel/GrantAuth/role/index.vue
  frontend/src/views/system/user/index.vue
Labels: 类型:优化

#643 fix: doris函数
  backend/src/main/resources/db/migration/V19__area_mapping.sql
Labels: 类型:bug

#644 fix: 定时查询未读消息条数错误
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/controller/sys/MsgController.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
  frontend/src/api/system/msg.js
  frontend/src/components/Notification/index.vue
  frontend/src/utils/request.js
Labels: 类型:bug

#645 feat: 字段编辑
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/data/CalcFieldEdit.vue
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:新功能

#646 feat: 视图增加边框圆角配置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue
Labels: 类型:新功能

#647 refactor:下钻到最后一级提示对应信息
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#648 feat: 散点气泡图轴线样式
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#653 feat: 字段编辑增加引用字段和引用函数说明
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:新功能

#656 feat: 字段编辑优化界面显示
  backend/src/main/java/io/dataease/service/dataset/DatasetFunctionService.java
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:新功能

#657 fix: 仪表板数字范围组件样式错误
  frontend/src/components/dataease/DeOutWidget.vue
Labels: 类型:bug

#659 refactor: 用户列表高级搜索优化
  frontend/src/components/business/condition-table/DeComplexOperator.vue
  frontend/src/components/business/condition-table/DeComplexSelect.vue
  frontend/src/main.js
  frontend/src/views/system/user/index.vue
Labels: 类型:优化

#660 feat: 饼图、气泡图优化
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/scatter/scatter.js
Labels: 类型:新功能

#661 feat: 气泡图优化
  frontend/src/views/chart/chart/scatter/scatter.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#663 feat: 矩形树图优化
  frontend/src/views/chart/chart/treemap/treemap.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#664 refactor:仪表板视图编辑等图标增加悬浮提示
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#665 fix: 计算字段dataease name
  backend/src/main/java/io/dataease/service/dataset/DataSetTableFieldsService.java
Labels: 类型:bug

#666 refactor: 坐标轴强制显示最大值，scatter横轴优化
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common.js
Labels: 类型:优化

#668 feat: 公共链接分享增加短链接
  backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java
  backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  frontend/src/api/link/index.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/link/generate/index.vue
Labels: 类型:新功能

#669 refactor: db数据集增加原表显示
  frontend/src/views/dataset/common/DatasetChartDetail.vue
Labels: 类型:优化

#673 fix: 指标卡间隔不生效
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:bug

#680 fix: api验证lic
  backend/src/main/java/io/dataease/controller/IndexController.java
Labels: 类型:bug

#681 fix: 外部链接带密码嵌在iframe
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/store/getters.js
  frontend/src/store/modules/user.js
  frontend/src/utils/request.js
  frontend/src/views/link/index.vue
  frontend/src/views/link/pwd/index.vue
Labels: 类型:bug

#684 refactor:编辑时视图的设置按钮永远在最上层
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/index.vue
Labels: 类型:优化

#685 refactor:仪表板编辑清除联动信息不需要再保存
  frontend/src/store/index.js
Labels: 类型:优化

#686 refactor:样式调整，放着transfrom使z-index失效
  frontend/src/components/canvas/components/Editor/index.vue
Labels: 类型:优化

#687 fix: 公共链接弹出登录框
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#688 fix: 创建用户角色列表遮罩组织树
  frontend/src/views/system/user/form.vue
Labels: 类型:bug

#689 feat: 雷达图大小
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/radar/radar.js
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
Labels: 类型:新功能

#691 refactor:仪表版首次刷新设置为5分钟
  frontend/src/components/canvas/components/Editor/Preview.vue
Labels: 类型:优化

#692 refactor:优化页面查询速度
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartGroupMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetGroupMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSourceMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelGroupMapper.xml
Labels: 类型:优化

#696 fix: 表格和视图类型圆角无效
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#697 fix: 表格和视图类型圆角无效
  frontend/src/icons/svg/map.svg
  frontend/src/icons/svg/map_old.svg
Labels: 类型:bug

#724 fix:条件组件值回显错误
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
Labels: 类型:bug

#728 fix: 仪表板多个地图resize错误
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#729 fix: 雷达图空数据报错
  frontend/src/views/chart/chart/radar/radar.js
Labels: 类型:bug

#730 fix: 雷达图空数据报错
  frontend/src/views/chart/chart/radar/radar.js
Labels: 类型:bug

#732 fix: 修改删除组织提示信息
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:bug

#734 fix: 日期组件必须点左侧挂件才能弹出日期
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/Shape.vue
  frontend/src/views/panel/enshrine/index.vue
Labels: 类型:bug

#735 fix: 个人信息表单中角色信息展示错误
  frontend/src/views/system/user/privateForm.vue
Labels: 类型:bug
