Repository dataease/dataease, pull requests merged in 2021-12, with the labels that each got.

#1345 refactor: 定时报告迭代至下版本
  frontend/src/permission.js
Labels: 类型:优化

#1347 Pr@v1.5@refactor panel video refresh
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#1349 fix: 仪表板日期组件无法二次编辑
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/utils/index.js
Labels: 类型:bug

#1350 refactor(数据集): 优化数据集数据预览报错信息
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:优化

#1352 refactor(数据集): 优化数据集数据预览报错信息
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:优化

#1355 refactor: 仪表板导出pdf优化，防止导出画面不全
  frontend/src/api/panel/view.js
  frontend/src/components/canvas/components/Editor/Preview.vue
Labels: 类型:优化

#1359 refactor: 去除时间控件外边框
  frontend/src/components/canvas/components/TextAttr.vue
Labels: 类型:优化

#1360 fix: 修复PDF导出没有背景的问题
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue
  frontend/src/views/panel/export/PDFPreExport.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#1362 fix: 文本列表多选切换单选无效
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#1363 fix: 条件组件新增失败
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#1366 refactor: 前端eslint警告以及报错
  frontend/src/api/dataset/dataset.js
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/custom-component/DeVideo.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/widget/DeWidget/DeTreeSelect.vue
  frontend/src/views/dataset/add/union/UnionItemEdit.vue
  frontend/src/views/panel/export/PDFPreExport.vue
  frontend/src/views/panel/list/PanelViewShow.vue
  frontend/src/views/system/datasource/form.vue
  frontend/src/views/system/task/DatasetTaskList.vue
Labels: 类型:优化

#1373 feat(数据集): 关联数据集
  backend/src/main/java/io/dataease/commons/utils/DorisTableUtils.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/dto/dataset/DataTableInfoDTO.java
  backend/src/main/java/io/dataease/dto/dataset/union/UnionDTO.java
  backend/src/main/java/io/dataease/dto/dataset/union/UnionItemDTO.java
  backend/src/main/java/io/dataease/dto/dataset/union/UnionParamDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/dataset/add/union/UnionPreview.vue
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
  frontend/src/views/dataset/data/FieldEdit.vue
  frontend/src/views/dataset/data/TabDataPreview.vue
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:新功能

#1377 feat(数据集): 关联数据集
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/views/dataset/add/union/UnionEdit.vue
Labels: 类型:新功能

#1378 feat(数据集): 关联数据集
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:新功能

#1379 feat(数据集): 关联数据集
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/views/dataset/add/AddUnion.vue
Labels: 类型:新功能

#1380 feat(数据集): 关联数据集
  backend/src/main/java/io/dataease/service/authModel/VAuthModelService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  frontend/src/views/dataset/common/DatasetGroupSelector.vue
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:新功能

#1388 feat(数据集): 关联数据集
  frontend/src/views/dataset/add/AddUnion.vue
Labels: 类型:新功能

#1389 feat: 新增移动端接口
  backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.xml
  backend/src/main/java/io/dataease/mobile/api/HomeApi.java
  backend/src/main/java/io/dataease/mobile/dto/HomeItemDTO.java
  backend/src/main/java/io/dataease/mobile/server/HomeServer.java
  backend/src/main/java/io/dataease/mobile/service/HomeService.java
Labels: 类型:新功能

#1393 fix: rollback
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:bug

#1394 refactor: 计算字段无需展示原始类型
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:优化

#1395 fix: 第三方iframe嵌入公共链接
  backend/src/main/java/io/dataease/controller/IndexController.java
Labels: 类型:bug

#1396 refactor: 视图优化
  frontend/src/icons/svg/text.svg
  frontend/src/views/chart/chart/chart.js
Labels: 类型:优化

#1397 fix: 修复编辑仪表板时，初始化和编辑视图返回组件位置可能变化的问题
  frontend/src/components/canvas/components/Editor/index.vue
Labels: 类型:bug

#1405 refactor: 规范代码
  backend/src/main/java/io/dataease/controller/IndexController.java
Labels: 类型:优化

#1407 refactor: 数据关联优化
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:优化

#1410 feat: 新增移动端目录api
  backend/src/main/java/io/dataease/base/mapper/ext/MobileDirMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/MobileDirMapper.xml
  backend/src/main/java/io/dataease/mobile/api/DirApi.java
  backend/src/main/java/io/dataease/mobile/dto/DirItemDTO.java
  backend/src/main/java/io/dataease/mobile/dto/DirRequest.java
  backend/src/main/java/io/dataease/mobile/entity/PanelEntity.java
  backend/src/main/java/io/dataease/mobile/server/DirServer.java
  backend/src/main/java/io/dataease/mobile/service/DirService.java
  backend/src/main/java/io/dataease/mobile/service/HomeService.java
Labels: 类型:新功能

#1413 feat: 新增移动端个人中心
  backend/src/main/java/io/dataease/base/mapper/ext/MobileMeMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/MobileMeMapper.xml
  backend/src/main/java/io/dataease/mobile/api/MeApi.java
  backend/src/main/java/io/dataease/mobile/dto/MeItemDTO.java
  backend/src/main/java/io/dataease/mobile/server/MeServer.java
  backend/src/main/java/io/dataease/mobile/service/MeService.java
Labels: 类型:新功能

#1414 feat(视图): 同环比前端UI
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/compare.js
  frontend/src/views/chart/components/compare/CompareEdit.vue
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1416 fix: 公共链接适配移动端嵌入
  frontend/public/link.html
Labels: 类型:bug

#1417 fix: 修复mysql8.0 flyway执行失败问题
  backend/src/main/resources/db/migration/V15__update_function.sql
  backend/src/main/resources/db/migration/V17__update_auth.sql
  backend/src/main/resources/db/migration/V22__record_auth_view.sql
  backend/src/main/resources/db/migration/V28__de1.5.sql
  backend/src/main/resources/db/migration/V5__auth.sql
Labels: 类型:bug

#1419 feat: 移动端收藏状态
  backend/src/main/java/io/dataease/controller/panel/api/StoreApi.java
  backend/src/main/java/io/dataease/controller/panel/server/StoreServer.java
  backend/src/main/java/io/dataease/service/panel/StoreService.java
  frontend/src/api/panel/enshrine.js
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:新功能

#1423 feat(视图): 同比环比
  backend/src/main/java/io/dataease/dto/chart/ChartFieldCompareCustomDTO.java
  backend/src/main/java/io/dataease/dto/chart/ChartFieldCompareDTO.java
  backend/src/main/java/io/dataease/dto/chart/ChartViewFieldDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartConstants.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
Labels: 类型:新功能

#1424 feat: 修改镜像运行脚本
  Dockerfile
Labels: 类型:新功能

#1426 feat(视图): 同比环比
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/components/compare/CompareEdit.vue
  frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
Labels: 类型:新功能

#1427 refactor(视图): 指标结果优化
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:优化

#1428 feat(数据集): 关联数据集
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/dataset/add/union/NodeItem.vue
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
Labels: 类型:新功能

#1429 feat(视图): 同比环比
  frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
Labels: 类型:新功能

#1434 feat(视图): 过滤器支持and、or逻辑
  backend/src/main/java/io/dataease/dto/chart/ChartFieldCustomFilterDTO.java
  backend/src/main/java/io/dataease/dto/chart/ChartViewFieldBaseDTO.java
  backend/src/main/java/io/dataease/dto/chart/ChartViewFieldDTO.java
  backend/src/main/java/io/dataease/provider/query/QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  backend/src/main/resources/sql/sqlTemplate.stg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/filter/QuotaFilterEditor.vue
  frontend/src/views/chart/components/filter/ResultFilterEditor.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1435 feat(视图): 过滤器支持and、or逻辑
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:新功能

#1436 feat(视图): 行权限
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:新功能

#1437 feat: 仪表板tab组件内视图，支持放大和编辑
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelLinkJumpMapper.xml
  backend/src/main/java/io/dataease/dto/panel/linkJump/PanelLinkJumpInfoDTO.java
  frontend/src/components/canvas/components/Editor/EditBarView.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/store/index.js
  frontend/src/views/link/index.vue
  frontend/src/views/link/view/index.vue
Labels: 类型:新功能

#1439 fix: 修复仪表板内组件移动时没有对齐标线问题
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/index.vue
Labels: 类型:bug

#1442 fix: 仪表板Tab组件预览模式图层不明确问题
  frontend/src/components/canvas/components/Editor/Preview.vue
Labels: 类型:bug

#1443 fix: 设置联动信息是，目标视图选项存在uuid问题
  frontend/src/components/canvas/components/Editor/LinkageField.vue
Labels: 类型:bug

#1450 refactor: 移动端仪表板视图明细优化，手机端明细展开改为全屏模式
  frontend/src/components/canvas/components/Editor/CloseBar.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
Labels: 类型:优化

#1451 refactor: 代码回退
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
Labels: 类型:优化

#1456 feat: chrome镜像
  Dockerfile
Labels: 类型:新功能

#1459 fix: 老版本过滤组件导致死循环
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1460 fix: 使用与操作系统匹配的apk镜像
  Dockerfile
Labels: 类型:bug

#1466 feat(视图): 文本类型过滤组件支持枚举
  backend/src/main/java/io/dataease/dto/chart/ChartFieldCustomFilterDTO.java
  backend/src/main/java/io/dataease/dto/chart/ChartViewFieldBaseDTO.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/filter/ResultFilterEditor.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1468 feat: 新增移动端仪表板api
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/controller/IndexController.java
  frontend/src/utils/request.js
Labels: 类型:新功能

#1469 refactor: 重构基础镜像
  Dockerfile
Labels: 类型:优化

#1470 fix: 指定chrome版本
  Dockerfile
Labels: 类型:bug

#1472 refactor: 解决冲突
  backend/src/main/java/io/dataease/auth/filter/F2CLinkFilter.java
  backend/src/main/java/io/dataease/auth/util/JWTUtils.java
  backend/src/main/java/io/dataease/auth/util/LinkUtil.java
  backend/src/main/java/io/dataease/base/domain/PanelLink.java
  backend/src/main/java/io/dataease/base/domain/PanelLinkExample.java
  backend/src/main/java/io/dataease/base/domain/PanelLinkMapping.java
  backend/src/main/java/io/dataease/base/domain/PanelLinkMappingExample.java
  backend/src/main/java/io/dataease/base/mapper/PanelLinkMapper.java
  backend/src/main/java/io/dataease/base/mapper/PanelLinkMapper.xml
  backend/src/main/java/io/dataease/base/mapper/PanelLinkMappingMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelLinkMapper.xml
  backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java
  backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java
  backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/link/LinkValidateRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/link/OverTimeRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/link/PasswordRequest.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  backend/src/main/resources/db/migration/V29__de1.6.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/public/link.html
  frontend/src/api/link/index.js
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/utils/index.js
  frontend/src/views/link/index.vue
  frontend/src/views/link/pwd/index.vue
  frontend/src/views/link/view/index.vue
Labels: 类型:优化

#1473 feat(视图): 文本类型过滤组件支持枚举
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:新功能

#1475 refactor: 移动端静态资源打包
  backend/pom.xml
Labels: 类型:优化

#1476 refactor: 切换基础架构镜像
  Dockerfile
  backend/src/main/java/io/dataease/controller/IndexController.java
Labels: 类型:优化

#1477 fix: chrome-driver截图分辨率
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
Labels: 类型:bug

#1478 fix: tabs组件新增多个
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
Labels: 类型:bug

#1479 fix: 自定义控制范围失效
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1480 refactor: 仪表板支持高清PDF导出
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/utils/style.js
  frontend/src/store/index.js
  frontend/src/views/panel/export/PDFPreExport.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:优化

#1482 fix: 兼容老版本过滤组件
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1483 feat: 时间组件增加时间格式'无'
  frontend/src/components/canvas/components/Editor/DateFormat.vue
  frontend/src/components/widget/DeWidget/DeShowDate.vue
  frontend/src/components/widget/DeWidget/TimeDefault.vue
  frontend/src/components/widget/DeWidget/TimeElec.vue
  frontend/src/components/widget/DeWidget/TimeSimple.vue
Labels: 类型:新功能

#1484 fix: 搜索过滤组件兼容老版本
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
Labels: 类型:bug

#1485 fix: 完善定时报告分辨率提示
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:bug

#1486 fix: 文字搜索组件报错
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
Labels: 类型:bug

#1487 fix: 多字段过滤器
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1488 refactor: 移动端布局适配
  frontend/src/api/panel/enshrine.js
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/PreviewEject.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#1490 refactor: 优化移动端目录查询
  backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/MobileDirMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/MobileDirMapper.xml
  backend/src/main/java/io/dataease/mobile/service/DirService.java
  backend/src/main/resources/db/migration/V29__de1.6.sql
Labels: 类型:优化

#1491 fix: 截屏只有半屏
  backend/pom.xml
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
Labels: 类型:bug

#1493 fix: 全屏截图
  backend/pom.xml
Labels: 类型:bug

#1494 feat: 数据集入口适配
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  backend/src/main/java/io/dataease/listener/DatasetCheckListener.java
  frontend/src/api/dataset/dataset.js
  frontend/src/store/getters.js
  frontend/src/store/modules/dataset.js
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/dataset/index.vue
Labels: 类型:新功能

#1497 fix: 编辑仪表板边界位置工具栏不完整问题
  frontend/src/components/canvas/components/TextAttr.vue
Labels: 类型:bug

#1506 fix: 进行了移动设计后，仪表板没有改动，可连续保存
  frontend/src/components/canvas/components/Toolbar.vue
Labels: 类型:bug

#1508 fix: 翻译优化
  backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.xml
  frontend/src/lang/en.js
Labels: 类型:bug

#1509 fix: 任务管理国际化
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#1514 fix: 动态日期逻辑
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
Labels: 类型:bug

#1515 fix: 下拉列表选项重复
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
Labels: 类型:bug

#1516 refactor: 优化PC移动端布局切换，防止恢复
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/store/index.js
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:优化

#1517 fix: 过滤组件逻辑
  frontend/src/components/canvas/components/Editor/PreviewEject.vue
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/components/canvas/mobile/PreviewMobile.vue
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:bug

#1518 fix: 兼容老版本日期控件
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:bug

#1519 feat: 地图增加缩放重置按钮
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:新功能

#1522 fix: 空地图试图切换错误
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#1524 refactor: 移动端布局组件等待区域靠左排列
  frontend/src/components/canvas/components/Editor/MobileCheckBar.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/views/panel/edit/ComponentWait.vue
Labels: 类型:优化

#1532 feat: 日期范围动态时间
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/index.scss
  frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
  frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
  frontend/src/views/panel/filter/filterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterFoot.vue
Labels: 类型:新功能

#1533 fix: 时间范围动态时间兼容老版本
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:bug

#1535 fix: 时间范围动态时间限制
  frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
Labels: 类型:bug

#1542 fix: 下拉列表单选框不能取消
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1544 fix: 仪表板预览过滤条件失效
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1546 fix: 表格分页问题
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#1547 fix: 表格分页问题
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#1548 fix: BS/MS多端统一入口
  frontend/src/permission.js
  frontend/src/utils/index.js
Labels: 类型:bug

#1549 fix: 动态时间组件无效
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:bug

#1550 fix: sql过滤
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:bug

#1551 fix: 过滤组件对小数不支持
  frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
Labels: 类型:bug

#1553 fix: 移动端仪表板访问异常
  frontend/src/permission.js
Labels: 类型:bug

#1558 fix: 多字段枚举接口免登录
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/service/system/EmailService.java
Labels: 类型:bug

#1559 fix: 删除分组后，右侧界面关闭
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:bug

#1560 fix: 公共链接有效期
  frontend/src/views/link/generate/index.vue
Labels: 类型:bug

#1562 refactor: 仪表板间隙设置优化
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:优化

#1564 fix: 邮件截图报错
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
Labels: 类型:bug

#1565 fix: 弹框回车事件
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:bug

#1566 fix: 打印邮件堆栈异常
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
Labels: 类型:bug

#1567 fix: 数据集文本转日期
  backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug

#1568 fix: 优化打印日志
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
Labels: 类型:bug

#1571 fix: 定时任务截图报错
  Dockerfile
Labels: 类型:bug

#1570 refactor: 过滤组件初始化优化，视频历史过滤组件
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:优化

#1572 fix: dockerfile报错
  Dockerfile
Labels: 类型:bug

#1573 fix: dockerfile路径错误
  Dockerfile
Labels: 类型:bug

#1574 refactor: 过滤组件初始化优化，适配历史过滤组件
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:优化

#1576 fix: 我的分享多个焦点
  frontend/src/views/panel/GrantAuth/shareTree.vue
Labels: 类型:bug

#1579 fix: 下拉列表逻辑
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1580 refactor: 优化文字组件FontSize值范围设置
  frontend/src/components/canvas/components/TextAttr.vue
Labels: 类型:优化

#1581 fix: 公共链接跳转白名单
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
Labels: 类型:bug
