Repository dataease/dataease, pull requests merged in 2021-07, with the labels that each got.

#116 refactor: 前端tree组件以及拉宽线优化
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/index.vue
  frontend/src/views/chart/view/TableSelector.vue
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
  frontend/src/views/dataset/common/DatasetTableData.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/dataset/index.vue
  frontend/src/views/system/datasource/DsMain.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:优化

#117 fix: axios线上build后导致弹框
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  frontend/public/index.html
  frontend/src/main.js
Labels: 类型:bug

#122 fix: 修复部分开发环境仪表板编辑无法拖拽问题
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#131 feat: 视图坐标轴设置增加属性设置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
Labels: 类型:新功能

#134 feat: 饼图标签增加引导线设置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/pie/pie.js
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
Labels: 类型:新功能

#140 fix: 视图表格组件高度自适应
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#141 fix: 视图表格组件高度自适应
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#139 feat: 消息中心
  backend/src/main/java/io/dataease/auth/service/ExtAuthService.java
  backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
  backend/src/main/java/io/dataease/base/domain/SysMsg.java
  backend/src/main/java/io/dataease/base/domain/SysMsgExample.java
  backend/src/main/java/io/dataease/base/mapper/SysMsgMapper.java
  backend/src/main/java/io/dataease/base/mapper/SysMsgMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.xml
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml
  backend/src/main/java/io/dataease/commons/model/AuthURD.java
  backend/src/main/java/io/dataease/commons/utils/AuthUtils.java
  backend/src/main/java/io/dataease/controller/message/MsgController.java
  backend/src/main/java/io/dataease/controller/message/dto/MsgRequest.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  backend/src/main/java/io/dataease/service/message/DeMsgutil.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  backend/src/main/resources/db/migration/V10__web_msg.sql
  frontend/src/api/system/msg.js
  frontend/src/components/Notification/index.vue
  frontend/src/icons/svg/all-msg.svg
  frontend/src/icons/svg/notification.svg
  frontend/src/icons/svg/readed-msg.svg
  frontend/src/icons/svg/unread-msg.svg
  frontend/src/icons/svg/web-msg.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/components/Topbar.vue
  frontend/src/permission.js
  frontend/src/styles/index.scss
  frontend/src/styles/sidebar.scss
  frontend/src/styles/variables.scss
  frontend/src/utils/webMsg.js
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/dataset/index.vue
  frontend/src/views/msg/all.vue
  frontend/src/views/msg/index.vue
  frontend/src/views/msg/readed.vue
  frontend/src/views/msg/unread.vue
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/index.vue
  frontend/src/views/panel/list/PanelMain.vue
Labels: 类型:新功能

#144 feat: radar支持轴线样式设置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/components/component-style/SplitSelector.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#146 fix: 视图过滤不能设置无限制
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/filter/DimensionFilterEditor.vue
  frontend/src/views/chart/components/filter/QuotaFilterEditor.vue
  frontend/src/views/chart/components/filter/ResultFilterEditor.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#149 feat: 完善分享消息
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml
  backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
  backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelShareFineDto.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  frontend/src/api/panel/share.js
  frontend/src/api/system/msg.js
  frontend/src/components/Notification/index.vue
  frontend/src/permission.js
  frontend/src/views/panel/GrantAuth/dept/index.vue
  frontend/src/views/panel/GrantAuth/index.vue
  frontend/src/views/panel/GrantAuth/role/index.vue
  frontend/src/views/panel/GrantAuth/user/index.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:新功能

#150 feat: 添加站内消息sql
  backend/src/main/resources/db/migration/V10__web_msg.sql
Labels: 类型:新功能

#153 feat: 视图过滤增加包含与不包含
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/filter/DimensionFilterEditor.vue
  frontend/src/views/chart/components/filter/QuotaFilterEditor.vue
  frontend/src/views/chart/components/filter/ResultFilterEditor.vue
Labels: 类型:新功能

#157 feat: 视图维度指标增加快速搜索；视图界面可以编辑数据集字段
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#159 feat: 视图过滤优化
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
Labels: 类型:新功能

#160 feat: 继续完善消息提醒
  backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.java
  backend/src/main/java/io/dataease/controller/message/MsgController.java
  backend/src/main/java/io/dataease/controller/message/dto/MsgRequest.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/api/system/msg.js
  frontend/src/components/Notification/index.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/components/Topbar.vue
  frontend/src/views/dataset/index.vue
  frontend/src/views/msg/all.vue
  frontend/src/views/msg/readed.vue
  frontend/src/views/msg/unread.vue
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/index.vue
Labels: 类型:新功能

#163 fix:修复组件查询条件无效
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/system/datasource/form.vue
Labels: 类型:bug

#164 feat: 同步数据集预览数据从doris中取
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#168 feat: 视图数据集权限控制
  backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue
  frontend/src/views/chart/components/component-style/LegendSelector.vue
  frontend/src/views/chart/components/component-style/SplitSelector.vue
  frontend/src/views/chart/components/component-style/TitleSelector.vue
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/TooltipSelector.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/data/TabDataPreview.vue
  frontend/src/views/dataset/data/UnionView.vue
  frontend/src/views/dataset/data/UpdateInfo.vue
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:新功能

#170 feat: 视图数据集权限控制
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
Labels: 类型:新功能

#172 fix: 视图标签tooltip提示内容修复
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
Labels: 类型:bug

#176 feat: 数据集预览数量修改
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:新功能

#177 feat: 数据集预览数量修改
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:新功能

#179 fix(數據源): 校驗 oracle schema
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/datasource/form.vue
Labels: 类型:bug

#182 feat: 数据集编辑字段，增加维度指标选项，而非老版本中通过字段类型判定
  backend/src/main/java/io/dataease/base/domain/DatasetTableField.java
  backend/src/main/java/io/dataease/base/domain/DatasetTableFieldExample.java
  backend/src/main/java/io/dataease/base/mapper/DatasetTableFieldMapper.xml
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/resources/db/migration/V12__alter_updata_ds_table_field.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/src/icons/svg/field_location.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/index.scss
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/components/filter/ResultFilterEditor.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/common/DatasetCustomField.vue
  frontend/src/views/dataset/common/DatasetTableData.vue
  frontend/src/views/dataset/data/FieldEdit.vue
  frontend/src/views/dataset/data/TabDataPreview.vue
  frontend/src/views/dataset/data/UnionView.vue
Labels: 类型:新功能

#184 feat: 视图返回sql
  backend/src/main/java/io/dataease/dto/chart/ChartViewDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/resources/db/migration/V13__system_task.sql
Labels: 类型:新功能

#186 feat(數據集): 添加非直连数据集時，默认全量同步一次
  backend/src/main/java/io/dataease/controller/request/dataset/DataSetTableRequest.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/system/task/DatasetTaskList.vue
Labels: 类型:新功能

#187 fix: sql根据类型修复
  backend/src/main/java/io/dataease/provider/SQLConstants.java
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
Labels: 类型:bug

#191 feat: 视图颜色增加多种配色方案
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
Labels: 类型:新功能

#192 feat(數據集): 数据集任务，增加简单重复执行的功能
  backend/src/main/java/io/dataease/base/domain/DatasetTableTask.java
  backend/src/main/java/io/dataease/base/domain/DatasetTableTaskExample.java
  backend/src/main/java/io/dataease/base/mapper/DatasetTableTaskMapper.xml
  backend/src/main/java/io/dataease/commons/constants/ScheduleType.java
  backend/src/main/java/io/dataease/listener/AppStartListener.java
  backend/src/main/java/io/dataease/service/ScheduleService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java
  backend/src/main/resources/db/migration/V13__system_task.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/data/UpdateInfo.vue
  frontend/src/views/system/task/DatasetTaskList.vue
  frontend/src/views/system/task/TaskRecord.vue
Labels: 类型:新功能

#204 feat: 数据集视图底层sql拼接使用stg重构(mysql部分)
  backend/pom.xml
  backend/src/main/java/io/dataease/datasource/constants/DatasourceTypes.java
  backend/src/main/java/io/dataease/dto/sqlObj/SQLObj.java
  backend/src/main/java/io/dataease/provider/SQLConstants.java
  backend/src/main/java/io/dataease/provider/mysql/MySQLConstants.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/resources/sql/sqlTemplate.stg
Labels: 类型:新功能

#208 fix: 组织名称验重
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:bug

#209 refactor: 底层SQL拼接
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
Labels: 类型:优化

#210 fix: 中文输入法回车键直接保存
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/login/index.vue
  frontend/src/views/panel/list/EditPanel/index.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/system/user/form.vue
  frontend/src/views/system/user/index.vue
Labels: 类型:bug

#211 refactor: 前端接口调整
  frontend/src/api/system/sysAuth.js
Labels: 类型:优化

#212 refactor: SQL拼接
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
Labels: 类型:优化

#213 refactor: SQL拼接
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:优化

#215 feat: 追加/更新 excel 数据集时，列名与原数据集保持一致
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/views/dataset/add/AddExcel.vue
Labels: 类型:新功能

#218 fix: 数据集字段浮点转整型
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  frontend/src/views/dataset/add/AddExcel.vue
Labels: 类型:bug

#219 fix: 数据集编辑后空白
  backend/src/main/java/io/dataease/provider/doris/DorisConstants.java
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:bug

#223 feat: excel上传后可编辑字段类型再保存
  backend/src/main/java/io/dataease/controller/request/dataset/DataSetTableRequest.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/views/dataset/add/AddExcel.vue
Labels: 类型:新功能

#229 feat: 数据关联改为左连接等方式
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/data/UnionView.vue
Labels: 类型:新功能

#233 fix: flyway版本号
  backend/src/main/resources/db/migration/V15__update_function.sql
Labels: 类型:bug

#237 feat: 仪表板条件过滤组件增加标题
  frontend/package.json
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:新功能

#238 feat: 新增外部标题组件
  frontend/src/components/dataease/DeOutWidget.vue
Labels: 类型:新功能

#239 fix: 只打印错误日志
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
Labels: 类型:bug

#242 feat: 同数据源直连数据集之间支持数据关联
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/common/DatasetGroupSelector.vue
  frontend/src/views/dataset/data/FieldEdit.vue
  frontend/src/views/dataset/data/UnionView.vue
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#243 fix: 抽取数据的错误日志
  backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  frontend/src/views/system/task/TaskRecord.vue
Labels: 类型:bug

#244 feat: 同数据源直连数据集之间支持数据关联
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:新功能

#245 fix: 过滤组件弹框样式错位
  backend/src/main/java/io/dataease/map/api/MapApi.java
  backend/src/main/java/io/dataease/map/server/MapServer.java
  backend/src/main/java/io/dataease/map/service/MapService.java
  backend/src/main/java/io/dataease/map/utils/MapUtils.java
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:bug

#247 feat: 视图增加默认padding
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:新功能

#250 feat: 更换数据集确认按钮调整
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#251 fix: tree搜索后无法折叠
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:bug

#254 feat: 前端增加token免续命白名单
  frontend/src/settings.js
  frontend/src/utils/request.js
Labels: 类型:新功能

#257 refactor: 视图UI布局初步调整
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#260 feat: 过滤组件条件调整
  frontend/src/views/chart/components/filter/DimensionFilterEditor.vue
  frontend/src/views/chart/components/filter/QuotaFilterEditor.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#261 feat: 过滤组件条件调整,视图界面调整
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#262 feat: 视图过滤重新设计，支持单维度指标展示
  backend/src/main/java/io/dataease/dto/chart/ChartCustomFilterItemDTO.java
  backend/src/main/java/io/dataease/dto/chart/ChartFieldCustomFilterDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/FilterItem.vue
  frontend/src/views/chart/components/filter/ResultFilterEditor.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#263 feat: 视图维度指标拖动区域文案细节优化
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#265 fix: 单指标图表可能下标越界
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#266 fix: 创建视图报错
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#269 feat: 替换缩略图
  backend/src/main/java/io/dataease/map/dto/entity/AreaEntity.java
  backend/src/main/java/io/dataease/map/server/MapServer.java
  frontend/src/api/map/map.js
  frontend/src/icons/svg/map.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#270 feat: 堆叠图支持堆叠项
  backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java
  backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml
  backend/src/main/java/io/dataease/provider/QueryProvider.java
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/resources/db/migration/V16__alter_chart_view.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#273 fix: 添加菜单滚动条
  frontend/src/layout/index.vue
Labels: 类型:bug

#272 feat: 行政区划代码表
  backend/src/main/resources/db/migration/V17__area_mapping.sql
Labels: 类型:新功能

#275 feat: 视图字段排序增加icon标识
  frontend/src/icons/svg/sort-asc.svg
  frontend/src/icons/svg/sort-desc.svg
  frontend/src/styles/index.scss
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#276 feat: 过滤器兼容flyway
  backend/src/main/resources/db/migration/V16__alter_chart_view.sql
Labels: 类型:新功能

#277 fix: 堆叠bug修复
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#278 refactor: 界面样式调整
  frontend/src/styles/index.scss
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#279 fix: 视图样式
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
Labels: 类型:bug

#280 refactor: 视图样式调整
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/FilterItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#281 fix: 视图样式
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#282 feat: 支持仪表板数字区间过滤
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
Labels: 类型:新功能

#284 feat: 仪表板过滤组件数值区间
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/Shape.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/bean/Condition.js
  frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/index.scss
  frontend/src/views/panel/filter/index.vue
Labels: 类型:新功能

#285 feat:仪表板矩形组件增加边框弧度设置
  frontend/src/components/canvas/components/RectangleAttr.vue
  frontend/src/components/canvas/custom-component/component-list.js
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
Labels: 类型:新功能

#287 fix: 仪表板过滤组件国际化
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/filter/index.vue
Labels: 类型:bug

#286 refactor: 坐标轴图表滚轮缩放优化
  frontend/src/views/chart/chart/chart.js
Labels: 类型:优化

#291 fix: 数据集消息任务跳转
  frontend/src/store/modules/permission.js
  frontend/src/views/system/task/TaskRecord.vue
  frontend/src/views/system/task/dataset.vue
Labels: 类型:bug

#292 fix: 完善数据集消息任务跳转
  frontend/src/store/modules/permission.js
  frontend/src/views/system/task/dataset.vue
Labels: 类型:bug

#293 refactor: 视图样式界面优化
  frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue
  frontend/src/views/chart/components/component-style/LegendSelector.vue
  frontend/src/views/chart/components/component-style/SplitSelector.vue
  frontend/src/views/chart/components/component-style/TitleSelector.vue
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/TooltipSelector.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#294 fix: 数据集权限问题导致视图没有字段
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#295 refactor: 颜色选择器更换element自带组件
  frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue
Labels: 类型:优化

#296 fix: 修复跳转后菜单不打开
  frontend/src/views/system/task/dataset.vue
Labels: 类型:bug

#297 fix: 视图中数据集权限校验
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#298 fix: 回退
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#299 fix: 视图中数据集字段获取
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#300 fix: 视图中数据集字段
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#302 fix:矩阵设计模式下点击一次组件也不需保存镜像
  frontend/src/components/DeDrag/index.vue
Labels: 类型:bug

#303 fix:矩阵设计模式下点击一次组件也不需保存镜像
  frontend/src/components/DeDrag/index.vue
Labels: 类型:bug

#305 fix: 1.数据集同步消息跳转路由flyway;2.消息内容增加任务名称
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  backend/src/main/resources/db/migration/V10__web_msg.sql
Labels: 类型:bug

#308 fix: 编辑字段全不选后弹框报错
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#310 fix: 消息跳转到同步任务记录后加载有延时
  frontend/src/views/system/task/TaskRecord.vue
  frontend/src/views/system/task/dataset.vue
Labels: 类型:bug

#311 fix: 编辑字段全不选后弹框报错
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#314 refactor: 视图拖拽块增加placeholder
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#316 fix:【仪表板】同一张图片无法连续两次被导入到仪表盘
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#317 fix:在编辑仪表板时，复制堆叠柱状图时出错
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
Labels: 类型:bug

#320 refactor: 视图拖拽块增加placeholder
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#322 refactor: 视图字段拖拽区增加placeholder
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#323 refactor: 维度指标色彩区分
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/FilterItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
Labels: 类型:优化

#328 fix: 视图表格组件高度问题
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#330 refactor: 视图缩放暂时去掉
  frontend/src/views/chart/chart/chart.js
Labels: 类型:优化

#331 fix: 视图缩放
  frontend/src/views/chart/chart/chart.js
Labels: 类型:bug

#332 fix:全屏预览模式下日期控件下拉不显示问题
  frontend/src/components/widget/DeWidget/DeDate.vue
Labels: 类型:bug

#333 fix:全屏预览模式下日期控件下拉不显示问题
  frontend/src/components/widget/DeWidget/DeDate.vue
Labels: 类型:bug

#336 refactor: 数据集字段将维度指标分类展示，后续维度和指标具有不同的操作，为配置钻取目录、字段计算做前置准备
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableFieldsService.java
  frontend/src/api/dataset/dataset.js
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:优化

#337 refactor: 全局滚动条样式调整，字段编辑样式调整
  frontend/src/styles/index.scss
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:优化

#338 feat: everyone默认订阅仪表板分享、任务失败消息通知
  backend/src/main/java/io/dataease/base/domain/SysMsgSetting.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.xml
  backend/src/main/java/io/dataease/controller/message/MsgController.java
  backend/src/main/java/io/dataease/controller/message/dto/BatchSettingRequest.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
  frontend/src/api/system/msg.js
  frontend/src/views/msg/setting.vue
Labels: 类型:新功能

#340 fix: 删除未读消息列选择器
  frontend/src/components/business/complex-table/index.vue
  frontend/src/views/msg/unread.vue
Labels: 类型:bug

#341 fix:预览模式下部分尺寸的显示屏仪表板抖动问题
  frontend/src/components/canvas/components/Editor/Preview.vue
Labels: 类型:bug

#343 fix: 跳转任务消息延时
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
  frontend/src/views/system/task/DatasetTaskList.vue
  frontend/src/views/system/task/TaskRecord.vue
  frontend/src/views/system/task/dataset.vue
Labels: 类型:bug

#345 refactor:修复仪表板矩形悬浮框部分样式设置
  frontend/src/components/canvas/components/RectangleAttr.vue
Labels: 类型:优化

#346 feat: 下拉列表增加全部选项
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:新功能

#350 fix: 过滤组件弹框回显问题
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:bug

#351 feat: 字段管理多处优化，初步完成字段公式编辑前端UI
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/data/CalcFieldEdit.vue
  frontend/src/views/dataset/data/FieldEdit.vue
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#353 refactor: 字段编辑UI优化
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:优化

#354 fix: 抽取oracle数据时有多余空格
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
Labels: 类型:bug

#355 perf: 地图坐标json使用缓存
  frontend/src/store/getters.js
  frontend/src/store/index.js
  frontend/src/store/modules/map.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:优化

#356 fix: 数据集翻页不显示数据；国际化
  frontend/src/lang/en.js
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:bug

#357 fix: 数据集翻页不显示数据；国际化
  frontend/src/lang/en.js
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:bug

#358 fix: 数据集预览条数
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#359 fix: 数据集预览条数
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#360 fix:不参与授权的菜单授权页面不再显示
  backend/src/main/resources/db/migration/V15__update_function.sql
Labels: 类型:bug

#361 fix:不参与授权的菜单授权页面不再显示
  backend/src/main/resources/db/migration/V15__update_function.sql
Labels: 类型:bug

#362 fix: 数据集权限问题
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:bug

#363 fix: 数据集切换界面权限问题
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:bug

#364 fix: 数据集切换页面权限问题
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:bug

#365 fix: 数据集切换页面权限问题
  frontend/src/views/dataset/add/AddExcel.vue
Labels: 类型:bug

#366 fix: 过滤器多条件问题；视图编辑字段问题
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:bug

#367 fix:过滤组件参数变动也可以进行保存
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#368 fix: 过滤器多条件异常问题；编辑数据集切换到添加数据集界面异常问题
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:bug

#370 fix: 新建视图后权限问题
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/group/Group.vue
Labels: 类型:bug

#371 fix: 新建视图后权限问题
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/group/Group.vue
Labels: 类型:bug

#372 fix: 数据集从编辑切换至添加界面的显示问题
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:bug

#373 feat: 增加地图工具栏
  frontend/src/views/chart/chart/map/map.js
Labels: 类型:新功能

#374 fix:关闭仪表板编辑界面时清空画布缓存，修复过滤组件回显问题
  frontend/src/components/canvas/components/Toolbar.vue
Labels: 类型:bug

#376 fix:关闭仪表板编辑界面时清空画布缓存，修复过滤组件回显问题
  frontend/src/components/canvas/components/Toolbar.vue
Labels: 类型:bug

#375 fix: 数据集从编辑切换至添加界面的显示问题
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:bug

#377 refactor:代码格式化
  backend/src/main/java/io/dataease/base/domain/License.java
  backend/src/main/java/io/dataease/controller/message/MsgController.java
  backend/src/main/java/io/dataease/datasource/provider/JdbcProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskLogService.java
Labels: 类型:优化

#378 refactor:代码格式化
  frontend/public/tinymce/langs/zh_CN.js
  frontend/public/tinymce/langs/zh_TW.js
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/styles/common/variables.scss
Labels: 类型:优化

#379 fix: 修复抽取oracle数据
  backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTaskMapper.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
Labels: 类型:bug

#381 fix: 设置用户名称长度限制
  frontend/src/views/system/user/form.vue
Labels: 类型:bug

#384 fix: 定不定阅总是能接收到"默认消息"
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
Labels: 类型:bug

#386 fix: 视图兼容过滤
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/resources/db/migration/V16__update_chart_filter.sql
Labels: 类型:bug

#387 fix: flyway兼容
  backend/src/main/resources/db/migration/V16__update_chart_filter.sql
  backend/src/main/resources/db/migration/V17__alter_chart_view.sql
  backend/src/main/resources/db/migration/V18__area_mapping.sql
Labels: 类型:bug

#388 fix: 过滤兼容
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
Labels: 类型:bug

#390 fix: 自定义数据集关联问题
  backend/src/main/java/io/dataease/provider/QueryProvider.java
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:bug

#391 fix: 头部消息数字错位
  frontend/src/components/Notification/index.vue
  frontend/src/layout/components/Topbar.vue
Labels: 类型:bug

#392 fix: 自定义数据集关联问题
  backend/src/main/java/io/dataease/provider/QueryProvider.java
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:bug

#393 fix: 底层sql逻辑
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  backend/src/main/resources/sql/sqlTemplate.stg
Labels: 类型:bug

#396 fix: 底层sql逻辑
  backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
  backend/src/main/resources/sql/sqlTemplate.stg
Labels: 类型:bug
