Repository dataease/dataease, pull requests merged in 2022-10, with the labels that each got.

#3292 fix(视图-地图): 缩放按钮背景色跟随主题色变化
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/PreviewMobile.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
  frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
Labels: 类型:bug

#3293 fix(tabs): 选项卡内部地图缩放按钮没有跟随主题色
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/views/chart/view/DrillPath.vue
Labels: 类型:bug

#3206 feat(视图): 百分比堆叠柱状图
  frontend/src/icons/svg/percentage-bar-stack.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue
Labels: 类型:新功能

#3301 Pr@dev dataset bugfix
  frontend/src/styles/index.scss
Labels: 类型:bug

#3298 fix(仪表板-查询按钮): 按钮样式跟随仪表板主题
  frontend/src/components/widget/DeWidget/DeButton.vue
Labels: 类型:bug

#3296 refactor(视图): 导出视图明细变更为xlsx格式
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
Labels: 类型:优化

#3304 Pr@dev dataset bugfix
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/datasource/DsForm.vue
Labels: 类型:bug

#3311 fix(数据集): sql 解析支持 union
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#3314 refactor(仪表板): 富文本组件和富文本视图支持自适应缩放
  frontend/src/components/canvas/custom-component/DeRichText.vue
  frontend/src/components/canvas/custom-component/DeRichTextView.vue
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:优化

#3320 refactor(视图): 辅助线数值格式化跟随y轴
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/chart/common/common_antv.js
Labels: 类型:优化

#3328 fix(数据源): Mysql jdbc反序列化漏洞
  backend/src/main/java/io/dataease/dto/datasource/MysqlConfiguration.java
Labels: 类型:bug

#3329 Pr@dev eslint auto fix
  frontend/package.json
  frontend/src/components/deCustomCm/deBtn.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/system/task/dataset.vue
Labels: 类型:bug

#3336 perf(视图): g2plot代码完善
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/mix/mix_antv.js
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
Labels: 类型:优化

#3340 fix(数据源): 添加数据源时，校验参数
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
Labels: 类型:bug

#3344 perf(视图-地图): 格式化渐变色代码
  frontend/src/components/GradientColorSelector/DeColorPicker.vue
  frontend/src/components/GradientColorSelector/base.js
  frontend/src/components/GradientColorSelector/index.vue
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
Labels: 类型:优化

#3342 Merge branch 'dev' into pr@dev@feat_donut_chart
  frontend/src/icons/svg/pie-donut-rose.svg
  frontend/src/icons/svg/pie-donut.svg
  frontend/src/icons/svg/pie-rose.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/utils/StringUtils.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3349 fix(定时报告): 时间不能选择周六
  backend/src/main/java/io/dataease/commons/utils/CronUtils.java
Labels: 类型:bug

#3355 Pr@dev eslint auto fix
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/system/datasource/DsConfiguration.vue
Labels: 类型:bug

#3359 feat(国际化): 气泡地图增加底图颜色配置项国际化
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:新功能

#3360 fix(定时报告): 接收设置国际化文案
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:bug

#3362 fix(定时报告): 任务时间选择周日报错
  backend/src/main/java/io/dataease/commons/utils/CronUtils.java
Labels: 类型:bug

#3363 fix(插件管理): xpack插件禁止在线更新
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/plugin/index.vue
Labels: 类型:bug

#3367 feat(视图): 支持坐标轴轴线控制是否显示
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelector.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue
Labels: 类型:新功能

#3373 fix(过滤器-下拉): 选项超长鼠标悬浮显示全部
  frontend/src/components/ElVisualSelect/index.vue
Labels: 类型:bug

#3376 perf(视图-提示): echarts视图提示文案优化
  frontend/src/views/chart/components/shape-attr/TooltipSelector.vue
Labels: 类型:优化

#3371 fix(定时报告): 表单中视图数据无法回显
  frontend/src/components/DeViewSelect/index.vue
Labels: 类型:bug

#3374 Pr@dev eslint auto fix
  frontend/src/styles/index.scss
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/dataset/add/union/NodeItem.vue
  frontend/src/views/dataset/add/union/UnionNode.vue
  frontend/src/views/dataset/data/UpdateInfo.vue
  frontend/src/views/dataset/form.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/msg/all.vue
  frontend/src/views/panel/appTemplate/component/TemplateList.vue
  frontend/src/views/panel/appTemplateMarket/log/filterUser.vue
  frontend/src/views/panel/appTemplateMarket/log/index.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/system/SysParam/BasicSetting.vue
  frontend/src/views/system/SysParam/ClusterModeSetting.vue
  frontend/src/views/system/SysParam/EmailSetting.vue
  frontend/src/views/system/log/filterUser.vue
  frontend/src/views/system/log/index.vue
  frontend/src/views/system/task/DatasetTaskList.vue
  frontend/src/views/system/task/TaskRecord.vue
  frontend/src/views/system/task/filterUser.vue
  frontend/src/views/system/task/filterUserRecord.vue
  frontend/src/views/system/user/CustomCondtion.vue
  frontend/src/views/system/user/filterUser.vue
  frontend/src/views/system/user/imp-ldap.vue
  frontend/src/views/system/user/index.vue
  frontend/src/views/system/user/options.js
  frontend/src/views/system/user/privateForm.vue
  frontend/src/views/system/user/userEditer.vue
Labels: 类型:bug

#3369 feat(视图): 明细表和汇总表增加序列号
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common_table.js
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/components/table/TableNormal.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:新功能

#3378 fix: git 文件大小写不敏感bug
  frontend/src/views/chart/chart/common/common_table.js
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/components/table/TableNormal.vue
  frontend/src/views/system/SysParam/BasicSetting.vue
  frontend/src/views/system/SysParam/ClusterModeSetting.vue
  frontend/src/views/system/SysParam/EmailSetting.vue
  frontend/src/views/system/task/DatasetTaskList.vue
  frontend/src/views/system/task/TaskRecord.vue
  frontend/src/views/system/user/index.vue
Labels: 类型:bug

#3379 perf(路由): 路由组件使用驼峰命名规范
  backend/src/main/resources/db/migration/V42__1.16.sql
Labels: 类型:优化

#3380 perf(数据同步): 数据同步路由组件使用驼峰命名规范
  backend/src/main/resources/db/migration/V42__1.16.sql
Labels: 类型:优化

#3386 refactor(视图): 玫瑰图，饼图，环形图，玫瑰环形图优化
  frontend/babel.config.js
  frontend/package.json
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#3388 feat(定时报告): 视图数据选项
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/service/chart/FilterBuildTemplate.java
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
  frontend/src/lang/zh.js
Labels: 类型:新功能

#3390 perf(定时报告): 根据视图数据范围导出不同数据
  backend/src/main/java/io/dataease/service/chart/FilterBuildTemplate.java
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
  backend/src/main/resources/db/migration/V42__1.16.sql
  frontend/package.json
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
Labels: 类型:优化

#3396 Pr@dev eslint auto fix
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/system/sysParam/BasicSetting.vue
  frontend/src/views/system/sysParam/EmailSetting.vue
  frontend/src/views/system/sysParam/KettleSetting.vue
  frontend/src/views/system/sysParam/MapSetting/MapSettingLeft.vue
  frontend/src/views/system/sysParam/MapSetting/MapSettingRight.vue
  frontend/src/views/system/sysParam/MapSetting/index.vue
  frontend/src/views/system/sysParam/SimpleModeSetting.vue
  frontend/src/views/system/sysParam/index.vue
  frontend/src/views/system/task/DatasetTaskList.vue
  frontend/src/views/system/task/Form.vue
  frontend/src/views/system/task/index.vue
  frontend/src/views/system/task/options.js
  frontend/src/views/system/user/PrivateForm.vue
  frontend/vue.config.js
Labels: 类型:bug

#3403 feat(定时报告): 视图数据构造时间过滤器条件
  backend/src/main/java/io/dataease/service/chart/FilterBuildTemplate.java
  backend/src/main/java/io/dataease/service/chart/build/TimeBuild.java
  backend/src/main/java/io/dataease/service/chart/build/TimeYearBuild.java
  backend/src/main/java/io/dataease/service/chart/build/time/TimeDateBuild.java
  backend/src/main/java/io/dataease/service/chart/build/time/TimeDateRangeBuild.java
  backend/src/main/java/io/dataease/service/chart/build/time/TimeMonthBuild.java
  backend/src/main/java/io/dataease/service/chart/build/time/TimeYearBuild.java
Labels: 类型:新功能

#3406 Merge branch 'dev' into pr@dev@feat_liquid_dynamic_max
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/common/common_table.js
  frontend/src/views/chart/chart/liquid/liquid.js
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:新功能

#3410 fix: 部分后台拼写错误
  backend/src/main/java/io/dataease/auth/aop/DeLogAnnotationHandler.java
  backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
  backend/src/main/java/io/dataease/commons/constants/ResourceAuthLevel.java
  backend/src/main/java/io/dataease/commons/model/excel/ExcelSheetModel.java
  backend/src/main/java/io/dataease/commons/utils/AuthUtils.java
  backend/src/main/java/io/dataease/commons/utils/CronUtils.java
  backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
  backend/src/main/java/io/dataease/commons/utils/ExcelXlsReader.java
  backend/src/main/java/io/dataease/commons/utils/ExcelXlsxReader.java
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/controller/chart/ChartViewFieldController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/request/datasource/ApiDefinition.java
  backend/src/main/java/io/dataease/controller/request/datasource/es/EsResponse.java
  backend/src/main/java/io/dataease/controller/sys/SysMenuController.java
  backend/src/main/java/io/dataease/controller/sys/base/BaseGridRequest.java
  backend/src/main/java/io/dataease/dto/dataset/ExcelFileData.java
  backend/src/main/java/io/dataease/dto/dataset/ExcelSheetData.java
  backend/src/main/java/io/dataease/dto/datasource/RedshiftConfiguration.java
  backend/src/main/java/io/dataease/ext/query/GridExample.java
  backend/src/main/java/io/dataease/map/api/MapApi.java
  backend/src/main/java/io/dataease/map/dto/response/MapNodeReadResponse.java
  backend/src/main/java/io/dataease/map/server/MapServer.java
  backend/src/main/java/io/dataease/map/service/MapService.java
  backend/src/main/java/io/dataease/plugins/server/SSOServer.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/java/io/dataease/provider/datasource/ApiProvider.java
  backend/src/main/java/io/dataease/provider/datasource/EsProvider.java
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
  backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  backend/src/main/java/io/dataease/service/dataset/PermissionService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/java/io/dataease/service/panel/PanelViewService.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  backend/src/main/java/io/dataease/service/panel/applog/AppLogManager.java
  backend/src/main/java/io/dataease/service/sys/MenuService.java
  backend/src/main/java/io/dataease/service/sys/log/LogManager.java
Labels: 类型:bug

#3411 feat: 后台所有拼写错误
  backend/src/main/java/io/dataease/controller/sys/MsgController.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
  backend/src/main/resources/db/migration/V42__1.16.sql
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/funnel/funnel_antv.js
  frontend/src/views/chart/chart/line/line_antv.js
  frontend/src/views/chart/chart/mix/mix_antv.js
  frontend/src/views/chart/chart/pie/pie_antv.js
  frontend/src/views/chart/chart/radar/radar_antv.js
  frontend/src/views/chart/chart/scatter/scatter_antv.js
  frontend/src/views/chart/chart/treemap/treemap_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/chart/waterfall/waterfall.js
  frontend/src/views/chart/chart/wordCloud/word_cloud.js
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/system/datasource/DsAppForm.vue
  frontend/src/views/system/datasource/DsForm.vue
  frontend/src/views/system/log/FilterUser.vue
Labels: 类型:新功能

#3412 feat(视图): 快速计算支持占比
  backend/src/main/java/io/dataease/service/chart/ChartConstants.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
Labels: 类型:新功能

#3413 fix: 前端拼写错误
  frontend/src/components/ElTreeSelect/index.vue
  frontend/src/components/ElVisualSelect/index.vue
  frontend/src/components/Notification/index.vue
  frontend/src/components/canvas/components/Editor/Shape.vue
  frontend/src/components/canvas/utils/calculateComponentPositionAndSize.js
  frontend/src/components/gridTable/index.vue
  frontend/src/icons/svg/read-msg.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/settings.js
  frontend/src/styles/index.scss
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/data/UpdateInfo.vue
  frontend/src/views/dataset/form.vue
  frontend/src/views/msg/all.vue
  frontend/src/views/panel/template/component/TemplateList.vue
  frontend/src/views/system/task/DatasetTaskList.vue
Labels: 类型:bug

#3414 fix: 定时同步时，隐藏sql设置
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:bug

#3416 feat(仪表板): 仪表板Tab组件支持移入移出自由布局
  frontend/src/components/DeDrag/MoveInShadow.vue
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/DeDrag/pointShadow.vue
  frontend/src/components/DeDrag/shadow.vue
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/Editor/DateFormat.vue
  frontend/src/components/canvas/components/Editor/DeEditor.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/PGrid.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/PreviewMobile.vue
  frontend/src/components/canvas/components/FilterTextAttr.vue
  frontend/src/components/canvas/components/RectangleAttr.vue
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/custom-component/component-list.js
  frontend/src/components/canvas/store/copy.js
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/store/index.js
  frontend/src/views/panel/AssistComponent/index.vue
  frontend/src/views/panel/LinkJumpSet/index.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/index.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:新功能

#3415 Pr@dev eslint auto fix
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/dataset/common/datasetTree.vue
  frontend/src/views/dataset/data/UpdateRecords.vue
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/msg/all.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#3418 Pr@dev eslint auto fix
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:bug

#3419 Pr@dev eslint auto fix
  frontend/src/components/AsyncComponent/index.vue
Labels: 类型:bug

#3420 feat(仪表板): 仪表板Tab组件支持移入移出自由布局
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/Editor/DeEditor.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/store/index.js
Labels: 类型:新功能

#3422 fix: 移动端拼写错误
  mobile/src/components/amap-wx/js/util.js
  mobile/src/components/uni-link/uni-link.vue
  mobile/src/pages/tabBar/home/detail.nvue
  mobile/src/pages/tabBar/home/index.nvue
Labels: 类型:bug

#3428 perf(平台对接): 优化飞书国际版
  backend/src/main/java/io/dataease/plugins/server/XLarksuiteServer.java
  frontend/src/views/login/index.vue
Labels: 类型:优化

#3430 feat(仪表板): Tab组件内的过滤组件作用域仅限于当前Tab页范围
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/DeEditor.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
  frontend/src/store/index.js
Labels: 类型:新功能

#3431 refactor(仪表板): 新建视图默认加到主画布中
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#3435 perf(视图-地图): 分离渐变色
  frontend/src/components/GradientColorSelector/base.js
  frontend/src/components/GradientColorSelector/index.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#3437 feat(定时报告): 飞书国际版消息渠道
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendLarksuite.java
  backend/src/main/resources/db/migration/V42__1.16.sql
Labels: 类型:新功能

#3441 fix(地图): 渐变色自定义按钮文案
  frontend/src/components/GradientColorSelector/index.vue
Labels: 类型:bug

#3440 Pr@dev eslint auto fix
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/DeDrag/pointShadow.vue
  frontend/src/components/DeDrag/shadow.vue
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/Editor/DateFormat.vue
  frontend/src/components/canvas/components/Editor/DeEditor.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/PGrid.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/PreviewMobile.vue
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/store/index.js
  frontend/src/views/chart/view/ChartStyle.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/dataset/data/noSelect.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/panel/LinkJumpSet/index.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/index.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/system/datasource/DsMain.vue
Labels: 类型:bug

#3454 feat(视图): 计算占比时自动设置数值格式为百分比
  frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
Labels: 类型:新功能

#3453 fix: 开启cas后公共链接无效
  backend/src/main/java/io/dataease/auth/config/cas/CasStrategy.java
Labels: 类型:bug

#3458 fix(数据源): sqlserver 获取表出错
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
Labels: 类型:bug

#3459 fix(数据源): sqlserver 获取表出错
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
Labels: 类型:bug

#3460 fix(视图): 修复矩形树图标签复选框无法取消选中的问题
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#3464 fix(视图): 修复指标卡视图名称设定不显示时没有缩略相关配置项的问题
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
Labels: 类型:bug

#3463 Pr@dev eslint auto fix
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#3471 feat(视图): 快速计算支持占比
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3474 perf(数据集): 增强解析csv文件时代码稳定性
  backend/pom.xml
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:优化

#3470 Pr@dev@feat_app-connect
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/controller/panel/AppLogController.java
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/request/dataset/DataSetGroupRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelAppTemplateApplyRequest.java
  backend/src/main/java/io/dataease/dto/appTemplateMarket/AppLogGridDTO.java
  backend/src/main/java/io/dataease/ext/ExtAppLogMapper.xml
  backend/src/main/java/io/dataease/ext/ExtDataSetGroupMapper.xml
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/java/io/dataease/service/panel/applog/AppLogQueryParam.java
  backend/src/main/java/io/dataease/service/panel/applog/AppLogService.java
  backend/src/main/resources/db/migration/V42__1.16.sql
  frontend/src/api/appTemplateMarket/log.js
  frontend/src/api/panel/panel.js
  frontend/src/components/business/DeLayoutContent.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/appTemplate/AppTemplateContent.vue
  frontend/src/views/panel/appTemplate/component/AppTemplateApply.vue
  frontend/src/views/panel/appTemplate/component/TemplateItem.vue
  frontend/src/views/panel/appTemplate/component/TemplateList.vue
  frontend/src/views/panel/appTemplate/index.vue
  frontend/src/views/panel/appTemplateMarket/component/AppMarketPreview.vue
  frontend/src/views/panel/appTemplateMarket/index.vue
  frontend/src/views/panel/appTemplateMarket/log/index.vue
  frontend/src/views/panel/list/PanelViewShow.vue
  frontend/src/views/system/datasource/DsForm.vue
Labels: 类型:新功能

#3479 fix(数据源): mysql8 获取表字段为空
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
Labels: 类型:bug

#3478 fix: flyway拼写错误格式化问题修改
  backend/src/main/resources/db/migration/V29__de1.6.sql
  backend/src/main/resources/db/migration/V32__1.8.sql
  backend/src/main/resources/db/migration/V33__1.9.sql
  backend/src/main/resources/db/migration/V40__1.15.sql
  backend/src/main/resources/db/migration/V42__1.16.sql
Labels: 类型:bug

#3484 Pr@dev eslint auto fix
  frontend/src/views/system/task/DatasetTaskList.vue
  frontend/src/views/system/task/FilterUser.vue
Labels: 类型:bug

#3485 refactor(仪表板): 文本矩形等悬浮工具栏适配新画布
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#3486 Pr@dev eslint auto fix
  frontend/src/assets/datasource/pg.jpg
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/views/system/user/UserEditer.vue
Labels: 类型:bug

#3488 refactor(仪表板): 移动端设计新画布适配
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/views/panel/edit/ComponentWait.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#3487 refactor(视图): 辅助线、阈值设置界面UI优化
  frontend/src/views/chart/components/senior/AssistLine.vue
  frontend/src/views/chart/components/senior/Threshold.vue
  frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue
  frontend/src/views/chart/components/senior/dialog/TableThresholdEdit.vue
Labels: 类型:优化

#3469 fix(登出): oidc宕机后无法退出系统
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  frontend/src/api/user.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/store/modules/user.js
Labels: 类型:bug

#3489 fix(登出): 对接cas后退出系统没有跳转到cas登录页面issues/2909
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/plugins/server/CasServer.java
  frontend/src/api/user.js
  frontend/src/views/login/index.vue
Labels: 类型:bug

#3490 fix(国际化): 代码冲突
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
Labels: 类型:bug

#3492 Pr@dev eslint auto fix
  frontend/src/components/deCustomCm/deDatePick.vue
Labels: 类型:bug

#3491 refactor(仪表板): 富文本组件和富文本视图支持自适应缩放
  frontend/src/components/canvas/custom-component/DeRichText.vue
  frontend/src/components/canvas/custom-component/DeRichTextView.vue
  frontend/src/views/system/task/FilterUser.vue
Labels: 类型:优化

#3493 Merge branch 'dev' into pr@dev@feat_antv_group_stack_bar
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  frontend/src/icons/svg/bar-group-stack.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3496 feat: 【首页】新增培训班二维码
  frontend/src/assets/wizard_wechat-train.png
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/wizard/index.vue
Labels: 类型:新功能

#3494 fix(定时报告): 隐藏已被删除的视图
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  frontend/src/components/DeViewSelect/index.vue
Labels: 类型:bug

#3495 fix(视图): 修复新建视图控制台有异常打印问题
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
Labels: 类型:bug

#3498 Pr@dev eslint auto fix
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:bug

#3497 perf(地图): 地图配色方案
  frontend/src/components/GradientColorSelector/base.js
Labels: 类型:优化

#3502 fix: 处理控制台报错
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/PreviewMobile.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue
  frontend/src/views/panel/list/common/PanelDetailInfo.vue
Labels: 类型:bug

#3505 refactor: 复制组件后将焦点定位到新视图
  frontend/src/store/index.js
Labels: 类型:优化

#3504 fix(地图): 未开启标签但开启了提示二者会被同时触发
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/map/map.js
Labels: 类型:bug

#3506 fix(仪表板): 修复新画布编辑状态仪表板背景未生效问题
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#3508 fix(仪表板): 仪表板修改名称后没有自动修改顶部名称 #3445
  frontend/src/views/panel/list/EditPanel/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#3507 fix(登录): 登录选项Larksuite改为Lark
  frontend/src/views/login/index.vue
Labels: 类型:bug

#3509 Pr@dev eslint auto fix
  frontend/src/store/index.js
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#3510 fix: S2报错修复
  frontend/src/store/index.js
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/ChartComponentS2.vue
Labels: 类型:bug

#3512 fix(地图): 渐变色设置不可清除
  frontend/src/components/GradientColorSelector/index.vue
Labels: 类型:bug

#3513 fix(定时报告): echarts视图截图不完整
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#3519 refactor(视图): 阈值设置界面UI优化
  frontend/src/views/chart/components/senior/dialog/TableThresholdEdit.vue
Labels: 类型:优化

#3517 Pr@dev eslint auto fix
  frontend/src/styles/index.scss
  frontend/src/views/chart/components/component-style/TitleSelector.vue
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/form.vue
  frontend/src/views/system/datasource/DsConfiguration.vue
  frontend/src/views/system/datasource/DsForm.vue
Labels: 类型:bug

#3520 fix(应用): 修复导入应用数据集字段异常更新问题
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
Labels: 类型:bug

#3525 refactor(应用): 优化应用管理界面Loading状态防止误触
  frontend/src/api/panel/panel.js
  frontend/src/views/panel/appTemplate/component/AppTemplateApply.vue
  frontend/src/views/system/datasource/DsForm.vue
Labels: 类型:优化

#3526 refactor(仪表板): 当检测到组件想要移入Tab中的画布时，被拖拽组件图层设置为最高防止被tab组件遮挡
  frontend/src/components/DeDrag/index.vue
Labels: 类型:优化

#3527 refactor(视图): 优化标题备注编辑框背景，使用仪表板加视图的复合颜色作为背景
  frontend/src/views/chart/components/component-style/dialog/RemarkEditor.vue
Labels: 类型:优化

#3530 fix(视图): 修复透视表列表头受序列号影响的问题
  frontend/src/views/chart/chart/common/common_table.js
Labels: 类型:bug

#3529 feat(组件): Tab组件支持设置头部位置
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/components/widget/DeWidget/TabStyle.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/panel/panel.js
Labels: 类型:新功能

#3532 fix(视图): 修复组合图不显示的问题
  frontend/src/views/chart/chart/common/common.js
Labels: 类型:bug

#3533 fix(拼写错误): 消息相关sql中拼写错误
  backend/src/main/resources/db/migration/V10__web_msg.sql
Labels: 类型:bug

#3531 perf(定时报告): 视图文件格式改为xlsx
  backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
Labels: 类型:优化

#3534 feat(组件): Tab组件支持排序
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/components/widget/DeWidget/CustomTabsSort.vue
Labels: 类型:新功能

#3535 perf(定时报告): 发送完消息删除临时文件
  backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
Labels: 类型:优化

#3538 Pr@dev eslint auto fix
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/ChartTitleUpdate.vue
  frontend/src/views/chart/components/component-style/dialog/RemarkEditor.vue
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/normal/LabelNormalText.vue
  frontend/src/views/system/datasource/DsConfiguration.vue
Labels: 类型:bug

#3540 refactor(视图): 视图标题备注编辑时显示填充背景，主题色切换保留备注的显示设置
  frontend/src/components/canvas/utils/style.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue
  frontend/src/views/chart/components/component-style/dialog/RemarkEditor.vue
  frontend/src/views/chart/view/TitleRemark.vue
Labels: 类型:优化

#3541 fix(定时报告): resultMode增加非空判断
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
Labels: 类型:bug

#3542 fix(定时报告): 两个任务选同一个仪表板不同视图数据覆盖
  backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
Labels: 类型:bug

#3545 refactor(视图): 视图备注与标题对齐
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/normal/LabelNormalText.vue
Labels: 类型:优化

#3547 fix(定时报告): 数字区间过滤器报错
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
  backend/src/main/java/io/dataease/service/chart/build/NumberRangeBuild.java
Labels: 类型:bug

#3543 refactor(视图): 优化横纵轴网格线深色背景下的颜色
  frontend/src/components/canvas/utils/style.js
Labels: 类型:优化

#3550 refactor(仪表板): 仪表板主题默认配色、文案优化
  backend/src/main/resources/db/migration/V42__1.16.sql
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/panel/SubjectSetting/PanelStyle/ComponentStyle.vue
Labels: 类型:优化

#3551 refactor: 修改默认主题选项卡配色
  frontend/src/views/chart/chart/chart.js
Labels: 类型:优化

#3553 Pr@dev eslint auto fix
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#3554 refactor: 国际化修改
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#3555 fix(数据集): sql 数据集编辑后，如果选择立即更新，创建一个全量更新任务
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java
Labels: 类型:bug

#3558 refactor(组件): Tab组件支持设置字体大小
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/custom-component/component-list.js
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/widget/DeWidget/DeTabs.vue
Labels: 类型:优化

#3559 fix(消息管理): 单一渠道异常阻塞全部消息渠道
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
Labels: 类型:bug

#3561 perf(气泡地图): 深色主题默认底图颜色
  frontend/src/views/chart/chart/chart.js
Labels: 类型:优化

#3562 fix: 修复应用导出后端国际化问题
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#3565 fix(国际飞书): 国际飞书英文简称为INT Lark
  frontend/src/lang/en.js
  frontend/src/views/system/user/index.vue
Labels: 类型:bug

#3566 fix(我的分享): 过滤对已被删除的目标分享
  backend/src/main/java/io/dataease/ext/ExtPanelShareMapper.xml
Labels: 类型:bug

#3568 fix(我的分享): 我分享的列表数据重复
  backend/src/main/java/io/dataease/ext/ExtPanelShareMapper.xml
Labels: 类型:bug
