Repository dataease/dataease, pull requests merged in 2022-05, with the labels that each got.

#2223 fix: tab中放地图钻取后查看详情图形错误
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
Labels: 类型:bug

#2224 fix: 移动端访问https升级策略放在nginx而不是页面代码中
  mobile/public/index.html
Labels: 类型:bug

#2228 feat: 默认登录方式设置
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/commons/constants/ParamConstants.java
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  backend/src/main/java/io/dataease/controller/sys/response/BasicInfo.java
  backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  frontend/src/api/user.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/login/index.vue
  frontend/src/views/system/SysParam/BasicSetting.vue
Labels: 类型:新功能

#2236 refactor: 视图样式处理逻辑抽取
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:优化

#2241 feat: 适配符号地图插件
  frontend/package.json
  frontend/src/main.js
  frontend/src/styles/index.scss
Labels: 类型:新功能

#2246 fix: 代码语法错误
  backend/src/main/java/io/dataease/ext/ExtSysMsgMapper.java
Labels: 类型:bug

#2247 fix: 默认登录方式无效
  frontend/src/views/login/index.vue
Labels: 类型:bug

#2248 fix: 异步加载默认登录方式
  frontend/src/views/login/index.vue
Labels: 类型:bug

#2249 feat: 仪表板条件组件设置标题位置
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/widget/DeWidget/TitlePostion.vue
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
Labels: 类型:新功能

#2262 refactor: 画布内存使用优化
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#2266 refactor: 优化辅助方格显示
  frontend/src/components/canvas/components/Editor/Grid.vue
Labels: 类型:优化

#2271 feat: 操作日志
  backend/src/main/java/io/dataease/auth/annotation/DeLog.java
  backend/src/main/java/io/dataease/auth/aop/DeCleanerAnnotationHandler.java
  backend/src/main/java/io/dataease/auth/aop/DeLogAnnotationHandler.java
  backend/src/main/java/io/dataease/commons/constants/SysLogConstants.java
  backend/src/main/java/io/dataease/commons/utils/AopUtils.java
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/controller/datasource/request/DeleteDsRequest.java
  backend/src/main/java/io/dataease/controller/sys/SysLogController.java
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/dto/SysLogDTO.java
  backend/src/main/java/io/dataease/dto/SysLogGridDTO.java
  backend/src/main/java/io/dataease/dto/log/FolderItem.java
  backend/src/main/java/io/dataease/ext/ExtSysLogMapper.java
  backend/src/main/java/io/dataease/ext/ExtSysLogMapper.xml
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
  backend/src/main/java/io/dataease/service/sys/log/LogManager.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/package.json
  frontend/src/api/system/datasource.js
  frontend/src/api/system/log.js
  frontend/src/lang/zh.js
  frontend/src/styles/index.scss
  frontend/src/views/system/datasource/DsTree.vue
  frontend/src/views/system/log/index.vue
Labels: 类型:新功能

#2272 feat: 操作日志数据结构
  backend/src/main/resources/db/migration/V35__1.11.sql
Labels: 类型:新功能

#2273 feat: 日志通过操作类型搜索
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  frontend/src/views/system/log/index.vue
Labels: 类型:新功能

#2275 feat: 新增富文本编辑器
  frontend/public/tinymce/skins/content/default/content.css
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/ContextMenu.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/DeRichText.vue
  frontend/src/components/canvas/custom-component/PanelTextEditor.vue
  frontend/src/components/canvas/custom-component/VTextBack.vue
  frontend/src/components/canvas/custom-component/component-list.js
  frontend/src/components/canvas/custom-component/index.js
  frontend/src/store/index.js
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
  frontend/src/views/Tinymce/index.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:新功能

#2289 refactor: 修改SvgIcon组件，未找到class显示未发现图标防止报错
  frontend/src/components/SvgIcon/index.vue
  frontend/src/icons/svg/non-existent.svg
Labels: 类型:优化

#2291 feat: 气泡地图增加标签字段设置
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:新功能

#2292 fix: 仪表板浏览器console报错
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:bug

#2294 feat: 符号地图sql
  backend/src/main/resources/db/migration/V35__1.11.sql
Labels: 类型:新功能

#2299 perf: 优化审计日志
  backend/src/main/java/io/dataease/auth/aop/DeLogAnnotationHandler.java
  backend/src/main/java/io/dataease/commons/utils/CustomCellWriteUtil.java
  backend/src/main/java/io/dataease/commons/utils/DeLogUtils.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/request/DeleteGroupRequest.java
  backend/src/main/java/io/dataease/controller/sys/request/LogTypeItem.java
  backend/src/main/java/io/dataease/dto/log/LogExcel.java
  backend/src/main/java/io/dataease/ext/ExtSysLogMapper.xml
  backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
  backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  backend/src/main/java/io/dataease/service/sys/log/LogManager.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/api/dataset/dataset.js
  frontend/src/api/system/log.js
  frontend/src/icons/svg/log.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/styles/index.scss
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/system/log/index.vue
  frontend/src/views/system/user/index.vue
Labels: 类型:优化

#2300 perf: 优化审计日志图标
  backend/src/main/resources/db/migration/V35__1.11.sql
Labels: 类型:优化

#2302 fix: 关于页面中版本号错误
  backend/src/main/java/io/dataease/service/AboutService.java
Labels: 类型:bug

#2305 fix: 修复富文本表格、图片等拖拽焦点编辑时错位问题
  frontend/src/components/canvas/custom-component/DeRichText.vue
  frontend/src/styles/index.scss
Labels: 类型:bug

#2308 refactor: 复用存量视图自动勾选
  frontend/src/components/canvas/components/Editor/EditBarView.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/panel/ViewSelect/multiplexing.vue
Labels: 类型:优化

#2312 fix: 批量设置视图样式时，若样式菜单过长，则无法滚动选择到底部的样式选项
  frontend/src/views/chart/view/ChartStyleBatchSet.vue
Labels: 类型:bug

#2313 feat: 过滤条件增加下拉树
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/commons/model/BaseTreeNode.java
  backend/src/main/java/io/dataease/commons/utils/TreeUtils.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetFieldService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  frontend/src/api/dataset/dataset.js
  frontend/src/components/ElTreeSelect/dom.js
  frontend/src/components/ElTreeSelect/index.vue
  frontend/src/components/ElTreeSelect/utils.js
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
  frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/filter/index.vue
  frontend/src/views/system/test/MyTree.vue
  frontend/src/views/system/test/index.vue
Labels: 类型:新功能

#2314 perf: 树形过滤器基本逻辑
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
  frontend/src/components/widget/bean/Condition.js
  frontend/src/utils/conditionUtil.js
Labels: 类型:优化

#2319 perf: 优化树形过滤器
  frontend/src/components/ElTreeSelect/index.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
  frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
  frontend/src/utils/conditionUtil.js
Labels: 类型:优化

#2320 fix: 删除测试代码
  frontend/src/views/system/test/MyTree.vue
  frontend/src/views/system/test/index.vue
Labels: 类型:bug

#2324 fix: 操作日志国际化
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#2325 fix: 日志导出增加条件
  backend/src/main/java/io/dataease/controller/sys/SysLogController.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  frontend/src/api/system/log.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/log/index.vue
Labels: 类型:bug

#2326 fix: 树形没有按照字段先后顺序构建树
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:bug

#2330 fix: 移动端查看分享错误
  backend/src/main/java/io/dataease/commons/utils/StaticResourceUtils.java
  backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java
  mobile/src/pages/tabBar/home/detail.nvue
Labels: 类型:bug

#2332 fix: 树过滤器单多模式切换
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
Labels: 类型:bug

#2333 fix: tabs选项卡不能选择视图
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
Labels: 类型:bug

#2334 perf: 优化操作日志
  backend/src/main/java/io/dataease/dto/log/LogExcel.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:优化

#2335 feat: 符号地图插件记录sql
  backend/src/main/resources/db/migration/V35__1.11.sql
Labels: 类型:新功能

#2337 fix: 恢复因为增加日志修改的api
  backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/controller/datasource/request/DeleteDsRequest.java
  frontend/src/api/dataset/dataset.js
  frontend/src/api/system/datasource.js
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:bug

#2338 fix: 暂时屏蔽视图操作日志
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
Labels: 类型:bug

#2343 fix: 接受消息设置联动错误
  frontend/src/views/msg/setting.vue
Labels: 类型:bug

#2344 fix: 纯内网环境主题切换失效
  backend/src/main/java/io/dataease/plugins/server/PluginCommonServer.java
Labels: 类型:bug

#2346 fix: 操作日志列表查询条件包含多个操作类型结果集逻辑错误
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
Labels: 类型:bug

#2348 fix: 修改log文件名称
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  frontend/src/views/system/log/index.vue
Labels: 类型:bug

#2349 fix: 文字位置去除 中 中场景，默认上 中
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/DeWidget/TitlePostion.vue
Labels: 类型:bug

#2351 refactor: 批量操作样式优化
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:优化

#2362 perf: 优化树形过滤器
  frontend/package.json
  frontend/src/components/ElTreeSelect/index.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
  frontend/src/main.js
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
Labels: 类型:优化
