Repository dataease/dataease, pull requests merged in 2022-11, with the labels that each got.

#3569 fix(分享): 分享目标重复
  backend/src/main/java/io/dataease/service/panel/ShareService.java
Labels: 类型:bug

#3570 fix(仪表板): 修复新建用户无法创建仪表板目录问题
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#3571 fix(视图): 修复标题不能调整位置的问题
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/ChartTitleUpdate.vue
  frontend/src/views/chart/components/component-style/TitleSelector.vue
  frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/normal/LabelNormalText.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/ViewTitle.vue
Labels: 类型:bug

#3572 perf(组织): 组织删除文案
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#3574 fix(数据集): 修复计算字段中引用函数错误
  backend/src/main/resources/db/migration/V42__1.16.sql
Labels: 类型:bug

#3576 feat(清理机器人): 启动时执行清理
  backend/src/main/java/io/dataease/ext/CleaningRebotMapper.java
  backend/src/main/java/io/dataease/ext/CleaningRebotMapper.xml
  backend/src/main/java/io/dataease/ext/ExtPanelShareMapper.xml
  backend/src/main/java/io/dataease/listener/CleaningRobotListener.java
  backend/src/main/java/io/dataease/service/CleaningRebotService.java
Labels: 类型:新功能

#3575 fix(数据集): 行列权限白名单用户列表
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
Labels: 类型:bug

#3577 fix(仪表板): 修复跳转的目标仪表板被删除，跳转后一直加载的问题
  frontend/src/api/panel/panel.js
  frontend/src/api/panel/shareProxy.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:bug

#3578 Pr@dev eslint auto fix
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/gridTable/index.vue
  frontend/src/views/chart/components/component-style/dialog/RemarkEditor.vue
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:bug

#3579 fix(视图): 当堆叠图有堆叠项时指标只有第一个生效，对应的跳转设置增加参数时也加上相应的限制
  frontend/src/views/panel/LinkJumpSet/index.vue
Labels: 类型:bug

#3580 fix(系统参数): 数据源检测时间间隔
  frontend/src/views/system/sysParam/BasicSetting.vue
Labels: 类型:bug

#3582 fix(仪表板): 修复部分仪表板的预览界面如全屏预览，复用预览含有tab组件时，tab内部视图出现错位重叠问题
  frontend/src/components/canvas/components/Editor/PreviewEject.vue
  frontend/src/components/canvas/components/Editor/PreviewFullScreen.vue
  frontend/src/views/link/view/index.vue
  frontend/src/views/panel/ViewSelect/multiplexing.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#3586 fix(视图): 修复部分视图属性批量操作无效
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
Labels: 类型:bug

#3588 Pr@dev eslint auto fix
  frontend/src/store/index.js
Labels: 类型:bug

#3589 fix(仪表板): 定时任务预览tab组件内的视图错位的问题
  frontend/src/components/DeViewSelect/index.vue
  frontend/src/components/canvas/store/copy.js
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/store/index.js
  frontend/src/views/panel/ViewSelect/multiplexing.vue
Labels: 类型:bug

#3590 fix(仪表板): 分享中查看仪表板缺失仪表板创建者信息
  frontend/src/api/panel/shareProxy.js
Labels: 类型:bug

#3592 fix(仪表板): 修复Tab内组件的悬浮工具栏无法修改问题
  frontend/src/components/canvas/components/TextAttr.vue
Labels: 类型:bug

#3593 fix(视图): 修复导出视图xlsx文件在mac上的Excel无法打开问题
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#3596 fix(仪表板): 修复Tab组件点击消失问题
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/store/index.js
Labels: 类型:bug

#3597 fix(视图): 修复echarts视图不能批量操作间距的问题
  frontend/src/views/chart/view/ChartStyleBatchSet.vue
Labels: 类型:bug

#3604 fix(个人信息): 绑定国际飞书账号缺失错误提醒
  frontend/src/views/system/user/PrivateForm.vue
Labels: 类型:bug

#3602 fix(仪表板): 复用查询按钮后关联组件显示错误
  frontend/src/store/index.js
Labels: 类型:bug

#3605 fix(模板市场): 修复历史模板数据应用后视图无法显示问题
  backend/src/main/java/io/dataease/service/panel/PanelGroupExtendDataService.java
  frontend/src/views/panel/templateMarket/index.vue
Labels: 类型:bug

#3606 Pr@dev eslint auto fix
  frontend/src/components/deCustomCm/deBtn.vue
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/ChartTitleUpdate.vue
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/normal/LabelNormalText.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/common/DatasetDetail.vue
  frontend/src/views/dataset/data/TabDataPreview.vue
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/system/log/FilterUser.vue
Labels: 类型:bug

#3608 Pr@dev eslint auto fix
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/store/index.js
  frontend/src/views/panel/ViewSelect/multiplexing.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#3611 Pr@dev eslint auto fix
  frontend/src/views/dataset/data/UpdateInfo.vue
  frontend/src/views/system/datasource/DsForm.vue
Labels: 类型:bug

#3610 fix(仪表板): 修复组件工具栏同时悬浮在不同Tab页的问题
  frontend/src/components/widget/DeWidget/DeTabs.vue
Labels: 类型:bug

#3612 fix(移动端): 没有角色的用户无法查看分享仪表板
  backend/src/main/java/io/dataease/ext/HomeMapper.xml
  backend/src/main/java/io/dataease/mobile/service/HomeService.java
Labels: 类型:bug

#3613 fix(移动端): 修复移动端放大不显示问题
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:bug

#3614 refactor: 修改Mysql相关字符集排序
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:优化

#3625 fix(应用): 解决无法创建应用分类问题
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
Labels: 类型:bug

#3627 fix(应用): 修复数据集字段未替换问题
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
Labels: 类型:bug

#3629 fix: 修复eslint导致的地图映射搜索不可用
  frontend/src/views/chart/components/senior/MapMapping.vue
Labels: 类型:bug

#3633 refactor(模板市场): 增加模板市场分类排序
  backend/src/main/java/io/dataease/commons/utils/HttpClientConfig.java
  backend/src/main/java/io/dataease/dto/templateMarket/TemplateCategory.java
  backend/src/main/java/io/dataease/service/templateMarket/TemplateMarketService.java
Labels: 类型:优化

#3635 feat(用户管理): 导入用户使用xlsx
  backend/pom.xml
  backend/src/main/resources/excel/user.xls
  backend/src/main/resources/excel/user.xlsx
Labels: 类型:新功能

#3647 fix(视图): 符号地图锁定依赖解决符号无法展示
  frontend/package.json
Labels: 类型:bug

#3651 fix: 内存泄露修复
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/normal/LabelNormalText.vue
  frontend/src/views/chart/components/table/TableNormal.vue
  frontend/src/views/chart/view/ChartFieldEdit.vue
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/dataset/add/union/UnionPreview.vue
  frontend/src/views/dataset/common/DatasetTableData.vue
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:bug

#3652 feat(定时报告): 预览按钮文案国际化
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:新功能

#3650 fix(应用): 修复应用新建自定义数据集可能无效的问题
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#3654 feat(基础设置): 日志保留时间
  backend/src/main/java/io/dataease/commons/constants/ParamConstants.java
  backend/src/main/java/io/dataease/controller/sys/response/BasicInfo.java
  backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/sysParam/BasicSetting.vue
Labels: 类型:新功能

#3657 feat(日志管理): 日志保留期限机制
  backend/src/main/java/io/dataease/controller/sys/SysLogController.java
  backend/src/main/java/io/dataease/service/CleaningRebotService.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
Labels: 类型:新功能

#3663 refactor: 文件命名标准化
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/components/editor/DeEditor.vue
  frontend/src/components/canvas/components/editor/SettingMenu.vue
  frontend/src/components/canvas/components/editor/index.vue
  frontend/src/components/widget/index.js
Labels: 类型:优化

#3661 feat(登录): 禁止扫码创建用户配置
  backend/src/main/java/io/dataease/auth/service/AuthUserService.java
  backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
  backend/src/main/java/io/dataease/commons/constants/ParamConstants.java
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarksuiteServer.java
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/views/login/index.vue
  frontend/src/views/system/sysParam/BasicSetting.vue
Labels: 类型:新功能

#3662 feat(数据集): 数据集导出Excel
  backend/src/main/java/io/dataease/controller/chart/ChartViewFieldController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/request/dataset/DataSetExportRequest.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/api/dataset/dataset.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#3669 feat(日志管理): 客户端IP地址
  backend/src/main/java/io/dataease/commons/utils/IPUtils.java
  backend/src/main/java/io/dataease/dto/SysLogGridDTO.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/log/index.vue
Labels: 类型:新功能

#3673 feat(日志): 公共链接增加日志
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/commons/constants/SysLogConstants.java
  backend/src/main/java/io/dataease/commons/utils/DeLogUtils.java
  backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java
  backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java
  backend/src/main/java/io/dataease/controller/request/panel/link/LinkViewLogRequest.java
  backend/src/main/java/io/dataease/service/sys/log/LogManager.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/db/migration/V44__1.17.sql
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/api/link/index.js
  frontend/src/views/link/view/index.vue
  frontend/src/views/system/log/index.vue
Labels: 类型:新功能

#3675 feat(数据集): 数据集导出Excel
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#3674 feat(视图): 色彩地图增加悬浮组件显隐设置
  frontend/src/components/suspensionSelector/index.vue
  frontend/src/components/widget/deWidget/inputStyleMixin.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:新功能

#3682 feat(数据集): 数据集导出Excel
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/PermissionsTreeService.java
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#3691 perf(数据集): 优化数据集表单路由驼峰命名
  backend/src/main/resources/db/migration/V44__1.17.sql
Labels: 类型:优化

#3688 feat(过滤器): 日期范围过滤器动态时间可设置固定时分秒
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/styles/index.scss
  frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:新功能

#3692 perf(登录): 页面右侧图片
  frontend/src/assets/login-desc.png
Labels: 类型:优化

#3695 feat(数据集): 数据集导出Excel
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:新功能

#3694 perf(视图): 插件视图样式设置无法加载
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:优化

#3698 feat(公共链接): 公共链接跳转支持返回
  frontend/src/components/canvas/components/editor/CanvasOptBar.vue
Labels: 类型:新功能

#3699 feat(视图): 视图中过滤增加数值校验
  frontend/src/views/chart/components/dragItem/utils.js
Labels: 类型:新功能

#3701 perf: npm缓存清理
  frontend/pom.xml
Labels: 类型:优化

#3705 fix: 删除代码中debugger
  frontend/src/views/login/index.vue
Labels: 类型:bug

#3704 perf(系统): 每天00:00:00定时清理废弃数据
  backend/src/main/java/io/dataease/job/sechedule/Schedular.java
  backend/src/main/java/io/dataease/service/CleaningRebotService.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
Labels: 类型:优化

#3716 feat(视图):地图可以切换指标
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/editor/DeEditor.vue
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/components/deDrag/index.vue
  frontend/src/components/widget/deWidget/inputStyleMixin.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/map/MapController.vue
  frontend/src/views/chart/components/map/MapLayerController.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3719 perf(消息中心): 消息组件命名规范化
  backend/src/main/resources/db/migration/V44__1.17.sql
Labels: 类型:优化

#3729 Merge branch 'dev' into pr@dv@feat_group_line
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  frontend/src/utils/StringUtils.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3735 fix(仪表板): 修复开启辅助网格模式后矩阵和悬浮视图叠在一起的问题
  frontend/src/components/deDrag/index.vue
Labels: 类型:bug

#3737 feat(定时报告): 立即执行国际化文案
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:新功能

#3736 feat: 支持水印设置
  backend/src/main/java/io/dataease/controller/sys/SystemInfoController.java
  backend/src/main/java/io/dataease/dto/UserLoginInfoDTO.java
  backend/src/main/java/io/dataease/dto/panel/PanelGroupDTO.java
  backend/src/main/java/io/dataease/plugins/server/XWatermarkServer.java
  backend/src/main/java/io/dataease/service/SystemInfoService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/resources/db/migration/V44__1.17.sql
  frontend/src/api/panel/panel.js
  frontend/src/api/panel/shareProxy.js
  frontend/src/api/systemInfo/userLogin.js
  frontend/src/assets/watermark-demo.png
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/tools/watermark.js
  frontend/src/components/deViewSelect/index.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/deicon/demo.css
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
  frontend/src/views/link/view/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:新功能

#3739 fix(仪表板): 修复当开启辅助网格画布有滚动条时,画布滚动部分没有网格的问题
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/editor/DeEditor.vue
Labels: 类型:bug

#3746 feat(视图): 增加字段一键清除按钮
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3751 feat: 支持水印设置
  backend/src/main/java/io/dataease/plugins/server/PluginCommonServer.java
  backend/src/main/java/io/dataease/plugins/server/XWatermarkServer.java
  backend/src/main/resources/db/migration/V44__1.17.sql
  frontend/src/api/panel/panel.js
  frontend/src/api/panel/shareProxy.js
  frontend/src/assets/watermark-demo.png
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/components/canvas/components/editor/DeEditor.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/tools/watermark.js
  frontend/src/components/deDrag/index.vue
  frontend/src/components/deViewSelect/index.vue
  frontend/src/views/link/view/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:新功能

#3749 perf: 查询用户列表过滤废弃角色
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:优化

#3752 fix: 修复公共链接水印显示问题
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
Labels: 类型:bug

#3755 refactor(仪表板): 优化组件边框设置，设置时加上当前仪表板背景和和组件颜色
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/deDrag/index.vue
  frontend/src/views/background/BackgroundItem.vue
  frontend/src/views/background/index.vue
  frontend/src/views/panel/edit/ComponentWaitItem.vue
Labels: 类型:优化

#3758 refactor(仪表板): 图片组件默认存储在服务器
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/subjectSetting/panelStyle/BackgroundSelector.vue
Labels: 类型:优化

#3759 feat: 系统的默认超时时间设置为100
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/utils/request.js
Labels: 类型:新功能

#3760 feat(仪表板): 仪表板视图刷新增加开关控制
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/utils/utils.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/panel.js
  frontend/src/views/panel/subjectSetting/index.vue
  frontend/src/views/panel/subjectSetting/panelStyle/BackgroundSelector.vue
  frontend/src/views/panel/subjectSetting/panelStyle/FilterStyleSelector.vue
  frontend/src/views/panel/subjectSetting/panelStyle/OverallSetting.vue
Labels: 类型:新功能

#3730 feat(过滤器): 下拉过滤器自定义排序(等待设计请勿merge)
  frontend/src/components/dragItem/index.vue
  frontend/src/components/widget/deWidget/DeSelect.vue
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/utils/index.js
  frontend/src/views/panel/filter/FilterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
  frontend/src/views/panel/filter/filterMain/FilterCustomSort.vue
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
  frontend/src/views/panel/filter/filterMain/FilterSort.vue
Labels: 类型:新功能

#3762 feat(定时报告): 立即执行后台
  backend/src/main/java/io/dataease/commons/utils/CronUtils.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskViewHandler.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/java/io/dataease/service/ScheduleService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:新功能

#3764 refactor(仪表板): 组件样式设置边框浏览界面展示两排
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/views/background/BackgroundItem.vue
  frontend/src/views/background/index.vue
Labels: 类型:优化

#3766 perf(过滤器): 文本下拉框自定义排序
  frontend/src/utils/index.js
  frontend/src/views/panel/filter/FilterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
  frontend/src/views/panel/filter/filterMain/FilterSort.vue
Labels: 类型:优化

#3770 feat(仪表板): 移动端支持自定义背景
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/utils/utils.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/edit/ComponentWait.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/panel.js
  frontend/src/views/panel/subjectSetting/panelStyle/MobileBackgroundSelector.vue
Labels: 类型:新功能

#3771 fix(视图): 修复明细表分页导致的视图异常
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#3777 perf(公共链接): 交互区域样式
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  frontend/src/components/canvas/components/editor/CanvasOptBar.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#3779 refactor(视图): 富文本视图允许修改标题
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/views/background/index.vue
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/componentStyle/TitleSelectorAntV.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:优化

#3781 refactor(视图): 优化视图计算字段交互
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#3783 feat(数据集): 日期格式支持
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  frontend/src/api/dataset/dataset.js
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:新功能

#3787 perf(公共链接): 交互区域样式优化
  frontend/src/components/canvas/components/editor/CanvasOptBar.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/icons/svg/link-back.svg
  frontend/src/icons/svg/link-down.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#3791 feat(视图): 透视表支持按合计排序
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
Labels: 类型:新功能

#3795 Pr@dev@feat line hide empty data
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/line/line_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/senior/FunctionCfg.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3797 refactor(仪表板): 仪表板自动刷新时清理联动条件
  frontend/src/components/canvas/components/editor/Preview.vue
Labels: 类型:优化

#3798 fix(地图): 多系列数据下钻问题
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#3799 fix(地图): 缩放功能异常
  frontend/src/views/chart/components/map/MapController.vue
Labels: 类型:bug

#3802 feat(仪表板): 悬浮组件支持精确位置调整
  frontend/src/components/canvas/components/editor/SettingMenu.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/store/index.js
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/PositionAdjust.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:新功能

#3813 feat(仪表板): 增加粘贴复制保存放大等快捷键
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/components/canvas/utils/shortcutKey.js
Labels: 类型:新功能

#3815 fix(公共链接): 深色主题下操作区域样式
  frontend/src/components/canvas/components/editor/CanvasOptBar.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/icons/svg/link-back.svg
  frontend/src/icons/svg/link-down.svg
  frontend/src/views/panel/export/PDFPreExport.vue
Labels: 类型:bug

#3816 fix(仪表板): 批量设置echarts视图外间距无效
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#3817 feat(仪表板): Tab组件支持轮播
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/widget/deWidget/DeTabs.vue
  frontend/src/components/widget/deWidget/TabStyle.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3820 feat(仪表板): Tab组件支持设置激活字体大小
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/customComponent/component-list.js
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/widget/deWidget/DeTabs.vue
  frontend/src/components/widget/deWidget/TabStyle.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3821 feat(视图): 透视表支持按合计排序
  frontend/package.json
  frontend/src/views/chart/chart/table/table-info.js
Labels: 类型:新功能

#3822 feat(视图): 透视表行汇总支持按合计排序
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
Labels: 类型:新功能

#3823 feat: 日期格式的支持
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
Labels: 类型:新功能

#3824 feat: Excel空单元格不参与类型判断
  backend/src/main/java/io/dataease/commons/utils/ExcelXlsReader.java
  backend/src/main/java/io/dataease/commons/utils/ExcelXlsxReader.java
Labels: 类型:新功能

#3830 feat: 日期格式的支持
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/response/DatasetTableField4Type.java
  backend/src/main/java/io/dataease/dto/dataset/DatasetTableFieldDTO.java
  backend/src/main/resources/db/migration/V44__1.17.sql
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:新功能

#3831 feat(视图): 透视表行汇总支持按合计排序
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
Labels: 类型:新功能

#3834 refactor(仪表板): 优化仪表板过滤组件表格等组件的自适应缩放方式，防止组件在仪表板不同分辨率下组件大小不适配问题
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:优化

#3836 fix(过滤器): 选择名为count的字段排序会被sql注入拦截
  backend/src/main/resources/application.properties
Labels: 类型:bug

#3837 fix(视图): 地图批量设置组件悬浮无效
  frontend/src/views/chart/view/ChartStyleBatchSet.vue
Labels: 类型:bug

#3839 fix(仪表板): 编辑分享树，底层仪表板会loading
  frontend/src/api/panel/share.js
  frontend/src/api/system/dept.js
Labels: 类型:bug

#3841 Pr@dev@feat table scroll bar color
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common_table.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shapeAttr/ColorSelector.vue
  frontend/src/views/chart/components/table/TableNormal.vue
  frontend/src/views/panel/subjectSetting/panelStyle/PanelColorSelector.vue
Labels: 类型:新功能

#3845 refactor(仪表板): 复用视图悬浮模式默认大小修改
  frontend/src/components/canvas/store/copy.js
Labels: 类型:优化

#3847 feat(过滤器): 时间范围过滤器支持动态参数
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
  frontend/src/styles/index.scss
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:新功能

#3850 fix(仪表): 修复Tab组件预览状态无法放大内部视图问题
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#3853 fix: 修复浏览器复制新的窗口可能出现仪表板列表无法显示的问题
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#3858 fix(仪表板): 优化一些热键冲突
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/store/copy.js
  frontend/src/components/canvas/utils/shortcutKey.js
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/PositionAdjust.vue
  frontend/src/views/dataset/data/FieldEdit.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#3859 Merge branch 'dev' into pr@dev@feat_percentage_horizonal_bar
  frontend/src/icons/svg/percentage-bar-stack-horizontal.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/ChartComponentG2.vue
Labels: 类型:新功能

#3861 fix(公共链接): 下载pdf缺失图片
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/views/link/view/index.vue
Labels: 类型:bug

#3864 fix(仪表板): 修复边框设置预览时背景图片显示不全问题
  frontend/src/views/background/index.vue
Labels: 类型:bug

#3862 refactor(仪表版): Tab组件轮播时间和轮播顺序优化
  frontend/src/components/widget/deWidget/DeTabs.vue
  frontend/src/components/widget/deWidget/TabStyle.vue
Labels: 类型:优化

#3865 feat: 数据集脱敏规则
  backend/src/main/java/io/dataease/commons/constants/ColumnPermissionConstants.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/PermissionService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:新功能

#3871 refactor(仪表板): 优化仪表板水印层级
  frontend/src/components/canvas/tools/watermark.js
Labels: 类型:优化

#3870 fix(仪表板): 重命名报错无权限
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#3873 refactor: 单词拼写优化
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  frontend/src/components/canvas/components/editor/DeEditor.vue
  frontend/src/components/deDrag/PointShadow.vue
  frontend/src/components/widget/deWidget/DeTabs.vue
  frontend/src/styles/theme/dark.scss
Labels: 类型:优化

#3876 fix(公共链接): 导出pdf出现loading
  frontend/src/components/canvas/components/editor/Preview.vue
Labels: 类型:bug

#3877 fix(视图): 批量地图组件悬浮设置对存量地图无效
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#3879 fix(仪表板): 修复仪表板导出PDF水印不全或者没有水印的问题
  frontend/src/components/canvas/components/editor/Preview.vue
Labels: 类型:bug

#3880 refactor: 优化悬浮工具栏最小字体
  frontend/src/components/canvas/components/TextAttr.vue
Labels: 类型:优化

#3878 feat(视图): 部分数据源不支持直连分页，使用前端分页
  backend/src/main/java/io/dataease/dto/chart/ChartViewDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:新功能

#3885 Merge branch 'dev' into pr@dev@fix_line_empty_data_cfg
  frontend/src/views/chart/chart/line/line_antv.js
Labels: 类型:bug

#3883 feat(视图): 部分数据源不支持直连分页，使用前端分页
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:新功能

#3888 fix: 渐变色 堆叠折线图
  frontend/src/views/chart/chart/util.js
Labels: 类型:bug

#3887 refactor(仪表板): 仪表板组件位置调整优化
  frontend/src/components/canvas/components/editor/SettingMenu.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#3889 fix(视图-AntV折线图): 修复多维度折线图线条断开策略的排序问题
  frontend/src/views/chart/chart/util.js
Labels: 类型:bug

#3891 feat(视图): 词云支持修改配色方案颜色
  frontend/src/views/chart/chart/util.js
Labels: 类型:新功能

#3890 fix(仪表板): 修复无法复用Tab内部组件的问题
  frontend/src/components/canvas/store/copy.js
  frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug

#3896 refactor(仪表板): 优化编辑状态其他组件侧边栏显示提示
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:优化

#3897 fix(用户管理): 用户表单可以保存包含特殊字符.的姓名
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/user/UserEditer.vue
Labels: 类型:bug

#3898 fix(数据集): 自定义时间格式
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:bug

#3899 perf(用户管理): 用户验证规则
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/user/UserEditer.vue
Labels: 类型:优化

#3900 fix(过滤器): 日期范围过滤器参数设置单个结束时间有效
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#3903 fix(应用): 修复应用重命名、控制台报错相关问题
  backend/src/main/resources/db/migration/V44__1.17.sql
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/appTemplate/AppTemplateContent.vue
  frontend/src/views/panel/appTemplateMarket/index.vue
  frontend/src/views/panel/templateMarket/index.vue
Labels: 类型:bug

#3906 fix(登录): 登录失败提示信息
  backend/src/main/java/io/dataease/auth/entity/AccountLockStatus.java
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/auth/service/AuthUserService.java
  backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#3910 refactor(插件): 优化插件显示
  frontend/src/views/system/plugin/index.vue
Labels: 类型:优化

#3912 fix(应用): 修复含有关联数据集的仪表板应用导入后关联数据集报错问题
  backend/src/main/java/io/dataease/commons/utils/DatasetUtils.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTableFieldMapper.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTableFieldMapper.xml
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/ext/ExtDataSetTaskMapper.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTaskMapper.xml
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.java
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml
  backend/src/main/java/io/dataease/service/dataset/DataSetTableFieldsService.java
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#3914 refactor(视图): 优化明细表下侧总计在切换主题时的颜色
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:优化

#3915 refactor(应用): 删除应用日志勾选删除相关资源时，清理掉浏览器相关资源的缓存
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/views/panel/appTemplateMarket/log/index.vue
Labels: 类型:优化

#3916 fix(视图): 编辑已删除的视图报错无权限
  frontend/src/api/chart/chart.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#3920 fix(视图): 修复明细表分页错误
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#3922 fix(仪表板): 修复部分Tab页面内容不显示问题
  frontend/src/store/index.js
Labels: 类型:bug

#3924 fix(仪表板): 修复富文本公共链接访问行间距过大问题
  frontend/src/components/canvas/customComponent/DeRichText.vue
  frontend/src/components/canvas/customComponent/DeRichTextView.vue
Labels: 类型:bug

#3926 refactor(仪表板): 快捷键优化
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/components/canvas/components/editor/SettingMenu.vue
  frontend/src/components/canvas/utils/shortcutKey.js
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#3927 fix(视图): 修复仪表antv环形图空标签联动高亮显示异常的问题
  frontend/src/components/deDrag/index.vue
  frontend/src/views/chart/components/ChartComponentG2.vue
Labels: 类型:bug

#3933 fix(仪表板): 修复用户视图放大，组件下拉框在全屏状态无法显示的问题
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/websocket/index.js
Labels: 类型:bug
