Repository dataease/dataease, pull requests merged in 2022-08, with the labels that each got.

#2745 fix(仪表板-下拉选择器): 全选无效
  frontend/src/components/ElVisualSelect/index.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
Labels: 类型:bug

#2746 fix(视图-地图): 格式化地图区域映射代码
  frontend/src/views/chart/components/senior/MapMapping.vue
Labels: 类型:bug

#2747 fix(仪表板): 修复批量设置时，当出现组件叠加时底层视图的选择按钮被覆盖问题
  frontend/src/components/DeDrag/index.vue
Labels: 类型:bug

#2748 fix(仪表板-树过滤器): 全屏模式下无法显示
  frontend/src/components/ElTreeSelect/index.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
Labels: 类型:bug

#2749 fix(仪表板-过滤组件): 复制视图后过滤组件对原视图和目标视图作用效果不一致
  frontend/src/components/canvas/store/copy.js
Labels: 类型:bug

#2752 refactor(仪表板): 符号地图适配主题变化
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/utils/style.js
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/panel/SubjectSetting/PanelStyle/OverallSetting.vue
  frontend/src/views/panel/panel.js
Labels: 类型:优化

#2756 fix(仪表板-时间过滤器): 精确到小时但是没有隐藏分钟选择器
  frontend/src/components/widget/DeWidget/DeDate.vue
Labels: 类型:bug

#2757 fix(系统管理-定时报告): 定时报告发送视图数据包含无效小数
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
Labels: 类型:bug

#2765 fix(系统管理-地图设置): 上传地图文件没有反应
  frontend/src/views/system/SysParam/MapSetting/MapSettingLeft.vue
  frontend/src/views/system/SysParam/MapSetting/MapSettingRight.vue
Labels: 类型:bug

#2769 fix(系统管理-定时报告): 定时报告不带视图数据发送报错
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
Labels: 类型:bug

#2794 feat(仪表板-日期范围过滤器): 增加时分秒精度设置
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
Labels: 类型:新功能

#2797 fix(视图-地图): 优化世界地图布局
  mapFiles/full/000/000000000_full.json
Labels: 类型:bug

#2800 feat(系统管理-ui优化): 适配新版UI新增系统管理路由页面
  frontend/src/views/system/settings/AppearanceSetting.vue
  frontend/src/views/system/settings/index.vue
  frontend/src/views/system/task/form.vue
Labels: 类型:新功能

#2801 feat(系统管理-ui优化): 配置ui优化对应的路由菜单sql
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:新功能

#2807 perf(仪表板-日期范围过滤器): 允许选择同一天
  frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
Labels: 类型:优化

#2816 feat(仪表板-清空按钮): 一键清空查询按钮绑定的过滤条件
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeResetButton.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
  frontend/src/components/widget/DeWidget/SearchButton.vue
  frontend/src/components/widget/serviceImpl/ButtonResetServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/utils/conditionUtil.js
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/ButtonResetDialog.vue
  frontend/src/views/panel/filter/index.vue
Labels: 类型:新功能

#2818 perf(系统管理-主题设置): 适配新版UI增加主题表单路由
  backend/src/main/java/io/dataease/plugins/server/PluginCommonServer.java
  frontend/src/components/AsyncComponent/index.vue
  frontend/src/store/modules/permission.js
Labels: 类型:优化

#2820 feat(系统): 动态获取系统图标favicon
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/components/Topbar.vue
  frontend/src/utils/index.js
  frontend/src/views/login/index.vue
Labels: 类型:新功能

#2822 perf(视图-地图): 优化地图缩放按钮样式
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:优化

#2827 perf: 优化主题设置后台接口
  backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:优化

#2828 feat(系统管理-主题): 增加主题设置api文档
  backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
Labels: 类型:新功能

#2830 refactor(仪表板): 清除联动按钮始终保持在右上方
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/PreviewMobile.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#2833 refactor(仪表板): 透视表跳转设置只保留指标字段
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/views/panel/LinkJumpSet/index.vue
Labels: 类型:优化

#2834 fix(视图-地图): 缩放按钮深色主题切到浅色没有反应
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#2838 perf(系统-依赖): easyexcel依赖移到xpack的sdk中
  backend/pom.xml
Labels: 类型:优化

#2841 feat(仪表板): 仪表板编辑时定时缓存未完成的仪表板，如果异常退出重新进入可以选择是否打开未保存的仪表板
  backend/src/main/java/io/dataease/commons/constants/JdbcConstants.java
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/api/panel/panel.js
  frontend/src/components/canvas/components/Editor/DateFormat.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/FrameLinks.vue
  frontend/src/components/canvas/components/Editor/Hyperlinks.vue
  frontend/src/components/canvas/components/Editor/HyperlinksDialog.vue
  frontend/src/components/canvas/components/Editor/PreviewEject.vue
  frontend/src/components/canvas/components/Editor/StreamMediaLinks.vue
  frontend/src/components/canvas/components/Editor/VideoLinks.vue
  frontend/src/components/canvas/components/FilterTextAttr.vue
  frontend/src/components/canvas/components/RectangleAttr.vue
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/components/canvas/custom-component/DeRichText.vue
  frontend/src/components/canvas/custom-component/DeRichTextView.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/custom-component/VText.vue
  frontend/src/components/canvas/store/snapshot.js
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/components/widget/DeWidget/TabStyle.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/PanelAidedDesign.vue
  frontend/src/views/panel/SubjectSetting/PanelStyle/ViewResult.vue
  frontend/src/views/panel/SubjectSetting/index.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/enshrine/index.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:新功能

#2844 feat(系统管理-用户管理): 导入用户操作权限sql
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:新功能

#2848 perf(系统管理-主题): 主题api结果增加主要设置项
  backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:优化

#2850 fix(系统管理-用户管理): 导入用户文件最大不能超过10M
  backend/src/main/java/io/dataease/plugins/server/XUserServer.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#2854 refactor(仪表板): 视图放大按钮样式可以跟随主题变化
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
  frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
  frontend/src/components/canvas/utils/style.js
Labels: 类型:优化

#2855 perf(仪表板-选项卡): 选项卡从插件合并到dataease主工程
  frontend/src/components/dataease-tabs/index.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/styles/de-tabs.scss
Labels: 类型:优化

#2860 fix: babel-eslint 版本降级
  frontend/package.json
Labels: 类型:bug

#2867 feat(系统管理-日志管理): 用户登录日志
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/commons/constants/SysLogConstants.java
  backend/src/main/java/io/dataease/plugins/server/CasServer.java
  backend/src/main/java/io/dataease/plugins/server/SSOServer.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:新功能

#2870 feat(系统管理-任务管理): 数据同步列表增加批量删除api
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java
Labels: 类型:新功能

#2871 feat(系统管理-插件管理): 优化代码删除冗余代码
  backend/src/main/java/io/dataease/plugins/config/PluginRunner.java
Labels: 类型:新功能

#2872 feat(系统管理-日志管理): pc查看仪表板记录日志-前端
  frontend/src/api/panel/panel.js
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/enshrine/index.vue
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:新功能

#2874 feat(系统管理-日志管理): 导出视图数据日志
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:新功能

#2877 feat(系统管理-日志管理): 移动端查看仪表板日志
  backend/src/main/java/io/dataease/commons/constants/SysLogConstants.java
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelViewLogRequest.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/api/panel/panel.js
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
  frontend/src/views/panel/GrantAuth/shareTree.vue
  frontend/src/views/panel/enshrine/index.vue
  frontend/src/views/panel/list/PanelList.vue
  mobile/src/api/panel.js
  mobile/src/pages/tabBar/home/detail.nvue
Labels: 类型:新功能

#2878 perf(系统管理-任务管理): 数据同步增加详情接口
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java
Labels: 类型:优化

#2882 feat(系统管理-外观配置): 增加登录页脚设置
  backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  backend/src/main/resources/db/migration/V39__1.14.sql
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/login/index.vue
Labels: 类型:新功能

#2888 fix(系统管理-定时报告): 定时报告选择太多视图会报错字段值长度过长，无法保存
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:bug

#2890 fix(系统管理-外观配置): 浏览器title设置
  frontend/public/index.html
  frontend/src/permission.js
  frontend/src/views/login/index.vue
Labels: 类型:bug

#2892 fix(系统管理-定时报告): 定时报告增加批量删除api
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
Labels: 类型:bug

#2896 feat(视图-地图): 地图边线颜色配置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
Labels: 类型:新功能

#2898 feat: 数据同步 定时报告 优化
  frontend/src/components/business/DeLayoutContent.vue
  frontend/src/components/gridTable/index.vue
  frontend/src/components/gridTable/tableBody.vue
  frontend/src/filter/filter.js
  frontend/src/icons/svg/ds-api.svg
  frontend/src/icons/svg/ds-db.svg
  frontend/src/icons/svg/ds-excel.svg
  frontend/src/icons/svg/ds-sql.svg
  frontend/src/icons/svg/ds-union.svg
  frontend/src/icons/svg/scene.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/index.scss
  frontend/src/views/panel/template/component/TemplateList.vue
  frontend/src/views/panel/template/index.vue
  frontend/src/views/system/SysParam/BasicSetting.vue
  frontend/src/views/system/task/DatasetTaskList.vue
  frontend/src/views/system/task/TableSelector.vue
  frontend/src/views/system/task/TaskRecord.vue
  frontend/src/views/system/task/dataset.vue
  frontend/src/views/system/task/filterUser.vue
  frontend/src/views/system/task/filterUserRecord.vue
  frontend/src/views/system/task/form.vue
  frontend/src/views/system/task/options.js
  frontend/src/views/system/user/index.vue
Labels: 类型:新功能

#2899 fix(系统管理-外观配置): 系统图标设置错误
  frontend/src/permission.js
Labels: 类型:bug

#2901 fix(系统管理-外观配置): uiinfo过大导致存储在前端cookie失效
  frontend/src/layout/components/Topbar.vue
  frontend/src/permission.js
  frontend/src/utils/auth.js
  frontend/src/views/login/index.vue
Labels: 类型:bug

#2903 fix(仪表板-过滤器): 数字范围过滤器标题样式
  frontend/src/components/dataease/DeOutWidget.vue
Labels: 类型:bug

#2906 fix(系统管理-插件管理): 替换菜单图标
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:bug

#2914 fix(系统管理-用户管理): 批量导入的模版不能使用excel打开
  backend/pom.xml
  backend/src/main/java/io/dataease/plugins/server/XUserServer.java
  backend/src/main/resources/excel/user.xls
Labels: 类型:bug

#2921 fix(系统管理-用户管理): 批量导入没有验证文件表头
  backend/src/main/java/io/dataease/plugins/server/XUserServer.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#2926 fix(仪表板-oracle数据源+树过滤器): 当树过滤器不是两级无法查询视图
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
Labels: 类型:bug

#2927 feat(系统管理-插件管理): 插件更新api
  backend/src/main/java/io/dataease/controller/sys/SysPluginController.java
Labels: 类型:新功能

#2929 feat(系统管理-定时报告): 增加导出api
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:新功能

#2931 fix(系统管理-插件管理): 优化更新插件api
  backend/src/main/java/io/dataease/controller/sys/SysPluginController.java
Labels: 类型:bug

#2936 fix(仪表板): 修复富文本在tab页无效的问题
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/api/panel/panel.js
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/custom-component/DeRichTextView.vue
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#2943 fix(仪表板-过滤器按钮): 清空按钮可以拖入多个
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/utils/conditionUtil.js
  frontend/src/views/panel/filter/index.vue
Labels: 类型:bug

#2947 fix(仪表板-日期范围过滤器): 显示时间默认值调整
  frontend/src/components/widget/DeWidget/DeDate.vue
Labels: 类型:bug

#2955 fix: 插件图片路径报错修复
  frontend/static/img/Group7.png
  frontend/static/img/WechatIMG1383.jpeg
  frontend/static/img/dataease.png
  frontend/static/img/login.jpg
Labels: 类型:bug

#2963 fix(仪表板-清空按钮): 过滤器全选后清空按钮无法重置全选状态
  frontend/src/components/ElTreeSelect/index.vue
  frontend/src/components/ElVisualSelect/index.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
Labels: 类型:bug

#2964 fix(仪表板-过滤器): ck数据源不能使用时间过滤器
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
Labels: 类型:bug

#2968 fix(视图-气泡地图): 移动端放大查看气泡地图样式模糊
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
  frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
Labels: 类型:bug

#2973 fix: lodash引用错误
  frontend/src/views/system/log/index.vue
Labels: 类型:bug

#2982 fix(系统管理-用户管理): 优化修改密码提示
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#2983 perf(系统管理-日志管理): 优化用户列表查询api根据关键字查询
  backend/src/main/java/io/dataease/ext/ExtSysLogMapper.java
  backend/src/main/java/io/dataease/ext/ExtSysLogMapper.xml
  backend/src/main/java/io/dataease/service/sys/log/LogQueryParam.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
Labels: 类型:优化

#2986 refactor(仪表板): 更新仪表板默认深色主题过滤组件颜色值
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:优化

#2995 fix(Tab组件): 修复点击Tab组件时编辑区域没有及时更换显示信息
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/lang/en.js
Labels: 类型:bug

#2997 perf(系统管理-日志管理): 增加角色组织绑定用户日志
  backend/src/main/java/io/dataease/commons/constants/SysLogConstants.java
  backend/src/main/java/io/dataease/commons/utils/DeLogUtils.java
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:优化

#3003 fix(登录-oidc): 修改系统默认密码后再次登录oidc用户失败
  backend/src/main/java/io/dataease/plugins/server/CasServer.java
  backend/src/main/java/io/dataease/plugins/server/SSOServer.java
Labels: 类型:bug

#3006 perf(系统管理-定时报告): 定时报告带模版视图数据报错
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
Labels: 类型:优化

#3007 perf(系统管理-消息管理): 删除已读消息未读消息菜单
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:优化

#3014 fix(仪表板-过滤器): 仪表板编辑状态下切换移动布局再切回来过滤器逻辑错误
  frontend/src/store/index.js
Labels: 类型:bug

#3020 fix(系统管理-插件管理): 修改插件信息
  backend/src/main/resources/db/migration/V39__1.14.sql
Labels: 类型:bug

#3025 fix(视图-s2表格): 预览s2表格后切换到空仪表板拖动浏览器控制台报错
  frontend/src/views/chart/chart/table/table-info.js
Labels: 类型:bug
