Repository dataease/dataease, pull requests merged in 2022-07, with the labels that each got.

#2541 refactor: 优惠插件菜单同步慢sql
  backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
  backend/src/main/java/io/dataease/auth/service/impl/DynamicMenuServiceImpl.java
  backend/src/main/java/io/dataease/plugins/util/PluginUtils.java
Labels: 类型:优化

#2544 fix: echarts雷达图没有指标
  frontend/src/views/chart/chart/radar/radar.js
Labels: 类型:bug

#2549 fix: 数字下拉参数无法显示
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:bug

#2550 fix(视图): 符号地图查看数据明细样式错位
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
Labels: 类型:bug

#2552 refactor(仪表板): 卡片组件内部视图增加放大功能
  frontend/src/components/canvas/components/Editor/EditBarView.vue
Labels: 类型:优化

#2553 fix(视图): 横向柱状图最大值输入不了数据问题
  frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
Labels: 类型:bug

#2554 fix(仪表板): 修复下架有权限的仪表板，编辑预览时提示已下架问题
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#2558 fix(仪表板): 下拉过滤器选择多字段枚举值出现空白选项
  frontend/src/components/ElVisualSelect/index.vue
Labels: 类型:bug

#2559 fix(仪表板): 下拉过滤器排序字段出现sql注入参数后依然能够点击确认
  frontend/src/components/widget/DeWidget/DeSelect.vue
Labels: 类型:bug

#2560 fix(仪表板): 下拉过滤器删除带有sql注入的排序字段后依然不能点击确认按钮
  frontend/src/components/widget/DeWidget/DeSelect.vue
Labels: 类型:bug

#2561 fix(视图): 仪表板全屏时雷达图有时会出现缩小问题
  frontend/src/views/chart/chart/radar/radar_antv.js
Labels: 类型:bug

#2562 fix(系统管理): 授权插件菜单的操作在记录日志时无法获取到菜单名称
  backend/src/main/java/io/dataease/ext/ExtSysLogMapper.xml
Labels: 类型:bug

#2564 fix(仪表板): 下拉过滤器添加同数据集多字段虽然有提示但还是能添加成功
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:bug

#2566 fix(视图): 基础折线图/堆叠折线图-大小设置缺少实线/虚线设置、折点大小设置项
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
Labels: 类型:bug

#2567 fix: 过滤组件中的虚拟滚动组件自定义样式不生效
  frontend/src/components/ElVisualSelect/index.vue
  frontend/src/components/widget/DeWidget/serviceNameFn.js
Labels: 类型:bug

#2579 fix: 修复safari由于不支持对js中正则表达式的 几个新增的断言验证不支持导致的白屏
  frontend/src/views/chart/view/CalcChartFieldEdit.vue
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:bug

#2581 fix(仪表板): 修复部分情况下批量设置视图属性再单独编辑视图原来批量设置的属性被恢复问题
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#2582 fix(视图): 批量设置视图属性时表格列宽、提示背景、折点大小未生效问题
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/components/shape-attr/TooltipSelectorAntV.vue
Labels: 类型:bug

#2583 refactor(视图): 坐标轴格式化支持批量样式设置
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelector.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue
Labels: 类型:优化

#2585 refactor: 联动高亮样式优化，优化一些不太明显的高亮
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/line/line_antv.js
Labels: 类型:优化

#2586 feat(系统管理): 定时报告增加视图选择器前端组件
  frontend/src/components/DeViewSelect/dom.js
  frontend/src/components/DeViewSelect/index.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/EditBarView.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/store/getters.js
  frontend/src/store/index.js
  frontend/src/store/modules/task.js
  frontend/src/styles/index.scss
Labels: 类型:新功能

#2588 refactor: 优化符号地图对公共组件样式的shi
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/views/background/index.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:优化

#2591 perf(系统): 升级kettle依赖版本号到8.3.0.18-1112(更好下载)
  backend/pom.xml
Labels: 类型:优化

#2594 fix(视图): 批量操作中饼图标签位置未翻译问题
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
  frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue
Labels: 类型:bug

#2596 feat(系统管理): 定时报告增加任务类型
  frontend/src/components/DeViewSelect/index.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/main.js
Labels: 类型:新功能

#2597 fix(仪表板): 取消收藏成功没有提示
  frontend/src/views/panel/enshrine/index.vue
Labels: 类型:bug

#2599 fix(仪表板): 删除分享仪表板报错
  backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
  backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  frontend/src/api/panel/share.js
  frontend/src/views/panel/GrantAuth/shareTree.vue
Labels: 类型:bug

#2604 fix(仪表板): 仪表板过滤器设置默认值失效
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
Labels: 类型:bug

#2605 fix(仪表板): 下拉过滤器交换多字段顺序后排序逻辑错乱
  frontend/src/components/DragItem/index.vue
  frontend/src/views/panel/filter/filterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
Labels: 类型:bug

#2609 feat(系统管理): 定时报告增加发送视图数据
  backend/src/main/java/io/dataease/commons/model/excel/ExcelSheetModel.java
  backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskViewHandler.java
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
  backend/src/main/java/io/dataease/service/system/EmailService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:新功能

#2621 fix(系统管理): 定时报告选择附件页面过滤掉非视图组件
  backend/src/main/java/io/dataease/controller/IndexController.java
  frontend/src/components/canvas/components/Editor/EditBarView.vue
Labels: 类型:bug

#2625 perf(系统管理): 优化角色管理适配新版ui
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
Labels: 类型:优化

#2632 perf(仪表板): 日期过滤组件增加时间精度配置
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/utils/index.js
  frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:优化

#2638 perf(仪表板): 优化echarts地图 增加世界地图
  backend/src/main/java/io/dataease/map/api/MapApi.java
  backend/src/main/java/io/dataease/map/dto/entity/Constants.java
  backend/src/main/java/io/dataease/map/server/MapServer.java
  backend/src/main/java/io/dataease/map/service/MapService.java
  backend/src/main/java/io/dataease/map/utils/MapUtils.java
  frontend/src/api/map/map.js
Labels: 类型:优化

#2639 perf(系统管理): 组织角色管理api适配新版UI
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/controller/sys/request/UserGridRequest.java
  backend/src/main/java/io/dataease/ext/ExtSysUserMapper.xml
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:优化

#2653 fix: 恢复镜像构建文件
  Dockerfile
Labels: 类型:bug

#2656 fix: 插件包引用路径修复
  frontend/src/components/AsyncComponent/index.vue
Labels: 类型:bug

#2659 perf(仪表板): 复制地图坐标文件判断是否已存在
  backend/src/main/java/io/dataease/map/service/MapTransferService.java
Labels: 类型:优化

#2666 fix(仪表板): 从模版市场新建仪表板地图找不到坐标文件
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#2671 refactor(仪表板): 优化仪表板编辑按钮显示位置，优先在视图外测显示且可以左右位置自适应改变
  frontend/src/components/canvas/components/Editor/EditBar.vue
Labels: 类型:优化

#2676 feat(仪表板): 仪表板新增查询按钮
  backend/src/main/resources/db/migration/V38__1.13.sql
  frontend/src/components/canvas/components/Editor/ContextMenu.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/components/widget/DeWidget/DeButton.vue
  frontend/src/components/widget/DeWidget/SearchButton.vue
  frontend/src/components/widget/serviceImpl/ButtonSureServiceImpl.js
  frontend/src/styles/index.scss
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/ButtonDialog.vue
  frontend/src/views/panel/filter/index.vue
Labels: 类型:新功能

#2677 fix(系统管理): 定时报告发增加视图Id集合注释错误
  backend/src/main/resources/db/migration/V38__1.13.sql
Labels: 类型:bug

#2679 refactor(仪表板): 仪表板的复用支持复用所有组件
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/store/copy.js
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/layout/components/Topbar.vue
  frontend/src/permission.js
Labels: 类型:优化

#2681 fix(系统管理): 定时报告发送邮件附件名称过长导致展示错误
  backend/src/main/java/io/dataease/service/system/EmailService.java
Labels: 类型:bug

#2687 perf(仪表板): 优化仪表板查询按钮
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/DeWidget/DeButton.vue
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
  frontend/src/components/widget/serviceImpl/ButtonSureServiceImpl.js
  frontend/src/utils/conditionUtil.js
  frontend/src/views/panel/filter/ButtonDialog.vue
  frontend/src/views/panel/filter/index.vue
Labels: 类型:优化

#2692 refactor(仪表板): 优化仪表板外部链接跳转参数替换逻辑，防止出现未替换情况
  frontend/src/views/panel/LinkJumpSet/index.vue
Labels: 类型:优化

#2691 perf(仪表板): 优化仪表板查询按钮
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
Labels: 类型:优化

#2705 feat(视图): echarts地图丰富标签样式属性设置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
Labels: 类型:新功能

#2707 fix(视图): 禁用echarts地图提示触发位置
  frontend/src/views/chart/chart/util.js
Labels: 类型:bug

#2711 fix(仪表板): 下拉框模糊搜索逻辑错误
  frontend/src/components/ElVisualSelect/index.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
Labels: 类型:bug

#2715 fix(系统管理-用户管理): 修改用户角色后其他客户端不能实时同步信息
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:bug

#2718 fix(仪表板): 时间过滤组件设置默认GMT时区
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
Labels: 类型:bug

#2728 perf(系统管理-定时报告): 发送视图信息需要带入过滤条件
  backend/src/main/java/io/dataease/dto/chart/FilterParamTO.java
  backend/src/main/java/io/dataease/service/chart/FilterBuildTemplate.java
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
  backend/src/main/java/io/dataease/service/chart/build/NumberRangeBuild.java
  backend/src/main/java/io/dataease/service/chart/build/SelectBuild.java
  backend/src/main/java/io/dataease/service/chart/build/SelectTreeBuild.java
  backend/src/main/java/io/dataease/service/chart/build/TextInputBuild.java
  backend/src/main/java/io/dataease/service/chart/build/TimeYearBuild.java
Labels: 类型:优化

#2731 fix(仪表板-过滤器): 时间过滤组件过滤精度到毫秒的视图有误差
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:bug

#2741 fix(视图): 地图地名映射配置以解决世界地图无法下钻
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/senior/MapMapping.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#2743 feat(视图-地图): 地图增加区域名称映射配置
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/senior/MapMapping.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能
