Repository dataease/dataease, pull requests merged in 2022-09, with the labels that each got.

#3033 feat(系统管理-系统参数): 企业微信设置
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  frontend/src/views/system/SysParam/index.vue
Labels: 类型:新功能

#3041 feat(数据源): 数据源表单sql
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:新功能

#3042 perf(登录): 企业微信扫码登录
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:优化

#3049 fix(登录): 钉钉扫码登录失败
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:bug

#3061 feat(数据集): 增加数据集表单路由页面
  backend/src/main/resources/db/migration/V40__1.15.sql
  frontend/src/store/modules/permission.js
  frontend/src/views/dataset/form.vue
Labels: 类型:新功能

#3063 feat(系统管理-消息中心): 增加第三方消息平台
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendDingtalk.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendLark.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendWecom.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:新功能

#3065 fix(系统管理-用户管理): 用户来源错误
  frontend/src/views/system/user/index.vue
Labels: 类型:bug

#3079 perf(系统管理-定时报告): 消息渠道sql
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:优化

#3086 perf(系统管理-定时报告): 优化企业微信、钉钉消息渠道
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
Labels: 类型:优化

#3090 fix(登录): 扫码登录失败错误提示
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  frontend/src/views/login/index.vue
Labels: 类型:bug

#3104 feat(视图): 堆叠项支持自定义排序
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/components/compare/CustomSortEdit.vue
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#3109 fix(系统管理-系统参数): 第三方登录平台默认邮箱设置为常量导致报错
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
Labels: 类型:bug

#3108 fix(系统管理-消息中心): 接收管理第三方平台渠道在未配置成功状态也能展示
  backend/src/main/java/io/dataease/controller/sys/MsgController.java
Labels: 类型:bug

#3112 fix: 数据源检测时间超出范围后，置为初始值
  frontend/src/views/system/SysParam/BasicSetting.vue
Labels: 类型:bug

#3111 feat: 支持应用市场，支持应用导入导出
  backend/src/main/java/io/dataease/controller/panel/AppLogController.java
  backend/src/main/java/io/dataease/controller/panel/PanelAppTemplateController.java
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/request/dataset/DataSetTableRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelAppTemplateApplyRequest.java
  backend/src/main/java/io/dataease/dto/appTemplateMarket/AppLogDTO.java
  backend/src/main/java/io/dataease/dto/appTemplateMarket/AppLogGridDTO.java
  backend/src/main/java/io/dataease/dto/panel/PanelExport2App.java
  backend/src/main/java/io/dataease/dto/panel/PanelGroupDTO.java
  backend/src/main/java/io/dataease/ext/ExtAppLogMapper.java
  backend/src/main/java/io/dataease/ext/ExtAppLogMapper.xml
  backend/src/main/java/io/dataease/plugins/common/base/domain/PanelAppTemplate.java
  backend/src/main/java/io/dataease/plugins/common/base/domain/PanelAppTemplateExample.java
  backend/src/main/java/io/dataease/plugins/common/base/domain/PanelAppTemplateWithBLOBs.java
  backend/src/main/java/io/dataease/plugins/common/base/mapper/PanelAppTemplateMapper.java
  backend/src/main/java/io/dataease/plugins/common/base/mapper/PanelAppTemplateMapper.xml
  backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateLogService.java
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/java/io/dataease/service/panel/PanelViewService.java
  backend/src/main/java/io/dataease/service/panel/applog/AppLogManager.java
  backend/src/main/java/io/dataease/service/panel/applog/AppLogQueryParam.java
  backend/src/main/java/io/dataease/service/panel/applog/AppLogService.java
  backend/src/main/resources/db/migration/V40__1.15.sql
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/api/appTemplateMarket/index.js
  frontend/src/api/appTemplateMarket/log.js
  frontend/src/api/dataset/dataset.js
  frontend/src/api/panel/panel.js
  frontend/src/api/system/appTemplate.js
  frontend/src/api/system/datasource.js
  frontend/src/components/msgCfm/index.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/appTemplate/component/TemplateImport.vue
  frontend/src/views/panel/appTemplate/component/TemplateItem.vue
  frontend/src/views/panel/appTemplate/component/TemplateList.vue
  frontend/src/views/panel/appTemplate/index.vue
  frontend/src/views/panel/appTemplateMarket/component/AppTemplateItem.vue
  frontend/src/views/panel/appTemplateMarket/component/MarketPreview.vue
  frontend/src/views/panel/appTemplateMarket/component/TemplateMarketItem.vue
  frontend/src/views/panel/appTemplateMarket/component/TemplateMarketPreviewItem.vue
  frontend/src/views/panel/appTemplateMarket/index.vue
  frontend/src/views/panel/appTemplateMarket/log/filterUser.vue
  frontend/src/views/panel/appTemplateMarket/log/index.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/system/datasource/DsForm.vue
Labels: 类型:新功能

#3110 feat: 支持 csv 文件
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  frontend/src/views/dataset/add/AddExcel.vue
Labels: 类型:新功能

#3116 refactor(仪表板): 优化仪表板为空的提示显示
  frontend/src/components/canvas/components/Editor/Preview.vue
Labels: 类型:优化

#3114 refactor(仪表板): 仪表板详情弹框显示用户别名
  backend/src/main/java/io/dataease/dto/panel/PanelGroupDTO.java
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
  frontend/src/api/panel/panel.js
  frontend/src/views/panel/list/common/PanelDetailInfo.vue
Labels: 类型:优化

#3118 refactor(仪表板): 复用视图支持适配当前仪表板样式
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/store/copy.js
  frontend/src/store/index.js
Labels: 类型:优化

#3120 perf(仪表板-过滤器): 过滤器提示文案
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#3123 feat: 模板市场支持权限管理和系统参数叠加权限控制，支持为不同用户开放或关闭“模板市场”菜单
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:新功能

#3125 fix: 数据源详情,数据集预览
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/system/datasource/dsTable.vue
Labels: 类型:bug

#3131 feat(数据源): 数据源详情
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml
Labels: 类型:新功能

#3132 refactor: 新建用户支持不设置用户角色
  frontend/src/views/system/user/userEditer.vue
Labels: 类型:优化

#3136 feat(视图): 阈值支持介于
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/senior/Threshold.vue
  frontend/src/views/chart/components/senior/dialog/TableThresholdEdit.vue
  frontend/src/views/chart/components/senior/dialog/TextThresholdEdit.vue
Labels: 类型:新功能

#3134 feat(系统管理-用户管理): 增加辅助信息包含第三方平台账号
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/controller/sys/request/SysUserCreateRequest.java
  backend/src/main/java/io/dataease/ext/ExtSysUserAssistMapper.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendDingtalk.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendLark.java
  backend/src/main/java/io/dataease/service/message/service/strategy/SendWecom.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
  frontend/src/api/system/user.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/user/userEditer.vue
Labels: 类型:新功能

#3135 perf(系统管理-用户管理): 用户辅助信息sql
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:优化

#3137 refactor: 优化标题修改，防止修改标题时切换视图出现修改标题与视图不对应情况
  frontend/src/components/DeDrag/index.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#3138 feat(视图): 缩略图增加样式配置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/components/senior/FunctionCfg.vue
Labels: 类型:新功能

#3152 refactor(视图): 阈值默认背景色调整
  frontend/src/views/chart/components/senior/dialog/TableThresholdEdit.vue
Labels: 类型:优化

#3151 refactor: 应用对接定时数据集立即同步
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
Labels: 类型:优化

#3153 feat(视图): echarts视图外边距设置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/component-style/MarginSelector.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:新功能

#3158 refactor(数据集): 数据集接口调整
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:优化

#3162 refactor(系统配置): 系统配置菜单拆分
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/components/business/DeLayoutContent.vue
  frontend/src/views/system/SysParam/index.vue
  frontend/src/views/system/plugin/dynamic.vue
Labels: 类型:优化

#3171 fix(仪表板): 优化文字组件修改字号时数字变动异常 #3099
  frontend/src/components/canvas/components/TextAttr.vue
  frontend/src/components/canvas/custom-component/DeRichTextView.vue
  frontend/src/views/panel/LinkJumpSet/index.vue
Labels: 类型:bug

#3170 fix(仪表板): 修复汇总表配置跳转字段后切换明细表跳转字段未清空
  frontend/src/components/canvas/custom-component/DeRichTextView.vue
  frontend/src/views/panel/LinkJumpSet/index.vue
Labels: 类型:bug

#3172 refactor: 修改国际化文案
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/lang/en.js
Labels: 类型:优化

#3157 fix(数据集): 抽取数据精度丢失
  backend/src/main/java/io/dataease/commons/utils/TableUtils.java
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
  backend/src/main/java/io/dataease/provider/engine/doris/DorisDDLProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:bug

#3179 feat(视图): 堆叠项支持自定义排序
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
Labels: 类型:新功能

#3180 fix(仪表板): 修复富文本视图动态值被固定问题
  frontend/src/components/canvas/custom-component/DeRichTextView.vue
Labels: 类型:bug

#3182 fix: 个人信息修改界面角色改为非必填
  frontend/src/views/system/user/privateForm.vue
Labels: 类型:bug

#3183 fix: 修复富文本视图待选字段超出显示范围问题
  frontend/src/components/canvas/components/Editor/fieldsList.vue
Labels: 类型:bug

#3185 fix(仪表板): 修复富文本视图部分情况下字段要删两次的情况
  frontend/src/components/canvas/custom-component/DeRichTextView.vue
Labels: 类型:bug

#3177 fix(系统管理-系统参数): 登录限制表单验证允许1-100正整数
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/SysParam/BasicSetting.vue
Labels: 类型:bug

#3188 fix(仪表板): 表格颜色样设置跟随仪表板主题变化后，设置视图属性后又恢复的问题
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#3189 fix(数据集): 更新excel 数据不需要校验数据集名称
  frontend/src/views/dataset/add/AddExcel.vue
Labels: 类型:bug

#3190 perf(个人信息): 扫码绑定第三方平台
  backend/src/main/java/io/dataease/auth/service/AuthUserService.java
  backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/controller/sys/response/AuthBindDTO.java
  backend/src/main/java/io/dataease/ext/AuthMapper.java
  backend/src/main/java/io/dataease/ext/AuthMapper.xml
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/user/privateForm.vue
Labels: 类型:优化

#3193 fix(ldap): ldap用户邮箱为空无法登录DE
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
Labels: 类型:bug

#3192 fix(个人信息): 绑定二维码无法显示
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  backend/src/main/resources/db/migration/V40__1.15.sql
  frontend/src/layout/components/Topbar.vue
  frontend/src/router/index.js
  frontend/src/views/system/user/privateForm.vue
Labels: 类型:bug

#3199 fix(登录): 登录限制提示优化
  backend/src/main/java/io/dataease/auth/entity/AccountLockStatus.java
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#3198 fix(登录): 登录成功后登录失败次数未清零
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
Labels: 类型:bug

#3197 fix(外观配置): 首页链接格式错误提示国际化
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:bug

#3201 fix(视图): echarts外边距设置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/component-style/MarginSelector.vue
Labels: 类型:bug

#3200 refactor: 修改数据库获取子级和父级函数，防止因垃圾数据出现环路导致循环情况
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:优化

#3203 fix(视图): echarts指标类型以及空间类型视图删除外边距设置
  frontend/src/views/chart/chart/util.js
Labels: 类型:bug

#3202 fix(模板管理): 修复删除模板分类列表未刷新问题
  frontend/src/views/panel/template/index.vue
Labels: 类型:bug

#3211 fix(登录限制): 限制登录次数填写保存后再次编辑出现验证逻辑错误
  frontend/src/views/system/SysParam/BasicSetting.vue
Labels: 类型:bug

#3208 perf(视图): 删除echarts分布式视图以及漏斗图外边距设置
  frontend/src/views/chart/chart/util.js
Labels: 类型:优化

#3214 perf(视图): 新建视图外边距继承了之前编辑的视图
  frontend/src/views/chart/components/component-style/MarginSelector.vue
Labels: 类型:优化

#3213 fix(视图): 外边距可以输入限制以外的数字
  frontend/src/views/chart/components/component-style/MarginSelector.vue
Labels: 类型:bug

#3212 fix(数据集): sql数据集修改字段先后顺序后，预览不起作用 #3062
  backend/src/main/java/io/dataease/controller/request/datasource/ApiDefinitionRequest.java
  backend/src/main/java/io/dataease/provider/datasource/ApiProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/system/datasource/DsConfiguration.vue
Labels: 类型:bug

#3219 fix(视图): 修复SQL Server标准差方差错误
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:bug

#3222 perf(用户管理): 删除第三方平台信息
  frontend/src/views/system/user/userEditer.vue
Labels: 类型:优化

#3225 refactor: 屏蔽echarts表格联动和跳转设置入口
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:优化

#3224 fix: 不同的sql 数据集参数同名
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:bug

#3226 fix(视图): 修复分组柱状图报错
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#3227 refactor: 优化国际化文案
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#3228 perf(个人信息): 第三方平台绑定DE用户
  backend/src/main/java/io/dataease/ext/AuthMapper.xml
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  backend/src/main/resources/db/migration/V40__1.15.sql
  frontend/src/layout/components/Topbar.vue
  frontend/src/router/index.js
Labels: 类型:优化

#3229 refactor: 优化数据集字段类型图标
  frontend/src/icons/svg/field_time.svg
  frontend/src/styles/index.scss
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:优化

#3231 refactor(数据集): 计算字段UI调整
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/CalcChartFieldEdit.vue
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:优化

#3234 fix(视图): 修复没有指标时编辑辅助线报错
  frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue
Labels: 类型:bug

#3232 fix(个人信息): 扫码绑定第三方平台错误信息提示
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
  frontend/src/views/system/user/privateForm.vue
Labels: 类型:bug

#3237 fix(仪表板): 修复辅助网格开启按钮状态显示问题
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/components/canvas/utils/style.js
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#3235 refactor: 优化字体大小限制，防止过滤组件标题被隐藏
  frontend/src/components/canvas/utils/style.js
Labels: 类型:优化

#3239 fix(登录): 钉钉扫码绑定DE用户后使用扫码登录失败
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
Labels: 类型:bug

#3242 fix(用户管理): 删除用户没有删除对应第三方平台信息
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:bug

#3244 fix(登录): 飞书扫码登录
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
Labels: 类型:bug

#3246 fix(视图): echarts缩略图背景样式
  frontend/src/views/chart/chart/common/common.js
Labels: 类型:bug

#3247 fix(过滤器): 非管理员删除过滤器字段报错无权限
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
Labels: 类型:bug

#3248 fix(过滤器): 标题设置后隐藏再开启被清空
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:bug

#3249 fix(过滤器): 树过滤器多选模式下选择部分节点再全选对目标视图无效
  frontend/src/components/ElTreeSelect/index.vue
Labels: 类型:bug

#3251 refactor: 更新视图复制自动命名函数，兼容富文本视图不需要显示标题的情况
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:优化

#3253 fix(视图): 编辑状态改变视图背景地图中文字没有及时变色
  frontend/src/api/system/dynamic.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#3254 fix(定时报告): 部分渠道消息发送失败会中断后面其他渠道消息
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
Labels: 类型:bug

#3257 fix(视图): 修复视图计算字段跟随视图复制后出现告警提示的问题
  frontend/src/views/chart/components/drag-item/utils.js
Labels: 类型:bug

#3262 fix(视图): 插件视图无法使用关联数据集
  backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
Labels: 类型:bug

#3259 refactor(视图): 轴值中刻度间隔文案优化
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
Labels: 类型:优化

#3264 fix(视图): 符号地图添加数字类型提示报错
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
Labels: 类型:bug

#3265 refactor(数据集): 数据集信息界面创建人显示为别名
  backend/src/main/java/io/dataease/controller/response/DataSetDetail.java
  backend/src/main/java/io/dataease/dto/dataset/DataSetTableDTO.java
  backend/src/main/java/io/dataease/dto/panel/PanelGroupDTO.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/api/panel/panel.js
  frontend/src/views/dataset/common/DatasetDetail.vue
  frontend/src/views/dataset/data/ViewTable.vue
  frontend/src/views/panel/list/common/PanelDetailInfo.vue
Labels: 类型:优化

#3266 fix: 数据集预览报错
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#3268 fix(视图): 设置tab背景对内部地图文字无效
  frontend/src/components/widget/DeWidget/DeTabs.vue
Labels: 类型:bug

#3271 fix: 创建数据集左侧列表可拉宽 保存数据集校验 数据请求添加loading
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/form.vue
Labels: 类型:bug

#3273 refactor(仪表板): 更新系统默认仪表板
  backend/src/main/resources/db/migration/V41__1.15-offical-panel-update.sql
Labels: 类型:优化

#3275 refactor: 默认的系统管理员角色增加系统配置相关菜单权限
  backend/src/main/resources/db/migration/V40__1.15.sql
Labels: 类型:优化

#3276 fix(定时报告): 第三方平台无法下载报告附件
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
Labels: 类型:bug

#3277 refactor: 清理未使用的数据集
  backend/src/main/resources/db/migration/V41__1.15-offical-panel-update.sql
Labels: 类型:优化

#3278 fix(数据更新): mysql YEAR 类型定时同步错误
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug

#3279 Pr@dev dataset bugfix
  frontend/src/components/deCustomCm/deTextarea.vue
  frontend/src/icons/svg/de-ds-warning.svg
  frontend/src/styles/index.scss
  frontend/src/views/panel/template/component/TemplateList.vue
  frontend/src/views/system/datasource/DsConfiguration.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:bug

#3280 fix(登录): 第三方平台扫码登录在姓名或邮箱重复情况下依然可以成功
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:bug

#3282 refactor(视图): 辅助线聚合方式优化
  frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue
Labels: 类型:优化

#3281 fix(仪表板): 修复部分仪表板复用tab组件时，复制的颜色边框值显示不正确问题
  frontend/src/components/canvas/utils/style.js
Labels: 类型:bug

#3283 fix(仪表板): 删除按钮组件的组件样式和超链接菜单
  frontend/src/components/canvas/components/Editor/SettingMenu.vue
Labels: 类型:bug

#3285 fix(仪表板): 修复网页组件在画布左上角时过滤组件和其他组件拖入仪表板事件被覆盖问题
  frontend/src/components/canvas/custom-component/DeFrame.vue
Labels: 类型:bug
