Repository dataease/dataease, pull requests merged in 2022-06, with the labels that each got.

#2367 fix: 符号地图导出excel缺少字段
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
Labels: 类型:bug

#2371 fix: 符号地图明细数据错误
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
Labels: 类型:bug

#2376 fix: 升级版本号1.11.1
  backend/pom.xml
  frontend/package.json
  frontend/pom.xml
  mobile/package.json
  mobile/pom.xml
  pom.xml
Labels: 类型:bug

#2385 feat: 过滤器枚举值排序
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/request/dataset/MultFieldValuesRequest.java
  backend/src/main/java/io/dataease/dto/dataset/DeSortDTO.java
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/api/ApiProvider.java
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetFieldService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  frontend/src/components/DragItem/index.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
  frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
  frontend/src/views/panel/filter/filterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
Labels: 类型:新功能

#2388 Pr@dev feat caculate id name
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:新功能

#2389 fix: 修复部分类型视图无法自定义颜色的问题
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#2395 fix: sql注入给出提示
  backend/src/main/java/io/dataease/commons/filter/SqlFilter.java
Labels: 类型:bug

#2406 feat: 视图字段可调整高度
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#2410 refactor: 重新设计明细查看
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/components/canvas/components/Editor/EditBarView.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#2411 refactor: 背景支持颜色图片同时选择
  frontend/src/components/DeDrag/index.vue
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/custom-component/component-list.js
  frontend/src/components/canvas/utils/utils.js
  frontend/src/views/background/index.vue
Labels: 类型:优化

#2419 feat: 切换仪表板自动取消之前未完成的数据请求
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/main.js
  frontend/src/utils/request.js
Labels: 类型:新功能

#2439 feat: 适配xpack-cas单点登录
  backend/pom.xml
  backend/src/main/java/io/dataease/auth/api/AuthApi.java
  backend/src/main/java/io/dataease/auth/config/cas/CasStrategy.java
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/auth/service/AuthUserService.java
  backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/commons/filter/SqlFilter.java
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  backend/src/main/java/io/dataease/ext/AuthMapper.java
  backend/src/main/java/io/dataease/ext/AuthMapper.xml
  backend/src/main/java/io/dataease/listener/CasStatusListener.java
  backend/src/main/java/io/dataease/plugins/server/CasServer.java
  backend/src/main/java/io/dataease/plugins/server/XCasServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
  backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  backend/src/main/resources/application.properties
  frontend/package.json
  frontend/src/api/user.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/components/Topbar.vue
  frontend/src/settings.js
  frontend/src/store/modules/user.js
  frontend/src/utils/auth.js
  frontend/src/views/system/SysParam/BasicSetting.vue
  frontend/src/views/system/SysParam/index.vue
Labels: 类型:新功能

#2440 refactor: 解决冲突
  backend/pom.xml
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
  backend/src/main/java/io/dataease/dto/dataset/SqlVariableDetails.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/listener/DatasetCheckListener.java
  backend/src/main/java/io/dataease/provider/datasource/EsProvider.java
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  backend/src/main/java/io/dataease/service/datasource/DriverService.java
  backend/src/main/resources/db/migration/V37__1.12.sql
  frontend/src/api/panel/view.js
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/bean/Condition.js
  frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
  frontend/src/lang/zh.js
  frontend/src/store/index.js
  frontend/src/utils/conditionUtil.js
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/panel/filter/filterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
  frontend/src/views/system/datasource/ApiBody.vue
  frontend/src/views/system/datasource/ApiKeyValue.vue
  frontend/src/views/system/datasource/ApiVariable.vue
Labels: 类型:优化

#2441 perf: 重置cas登录方式api增加管理员校验
  backend/src/main/java/io/dataease/auth/service/AuthUserService.java
  backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/plugins/server/CasServer.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:优化

#2442 perf: 增加cas切换默认登录方式api提示
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/SysParam/BasicSetting.vue
Labels: 类型:优化

#2443 perf: 优化cas切换api提示
  frontend/src/views/system/SysParam/BasicSetting.vue
Labels: 类型:优化

#2444 fix: 日志类型增加模糊搜索
  frontend/src/views/system/log/index.vue
Labels: 类型:bug

#2446 fix: 日志类型模糊搜索选择目标后词条消失
  frontend/src/views/system/log/index.vue
Labels: 类型:bug

#2453 feat: 过滤组件选择数据集时支持逐级返回
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:新功能

#2455 perf: 树过滤组件模糊搜索后全选只选中展示的节点
  frontend/src/components/ElTreeSelect/index.vue
Labels: 类型:优化

#2458 fix: 安装插件错误提示简化
  frontend/src/views/system/plugin/index.vue
Labels: 类型:bug

#2459 fix: 前端超时时间非空判断
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
Labels: 类型:bug

#2461 fix: api权限错误提示国际化
  backend/src/main/java/io/dataease/auth/aop/DePermissionAnnotationHandler.java
  backend/src/main/java/io/dataease/auth/aop/DePermissionProxyHandler.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#2464 fix: 插件视图不能使用sql数据集
  backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
Labels: 类型:bug

#2467 fix: 退出登录错误
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
Labels: 类型:bug

#2469 fix: 日志导出文件使用excel无法打开
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
  frontend/src/views/system/log/index.vue
Labels: 类型:bug

#2470 fix: 符号地图选择数字提示后报错
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#2473 fix: 计算字段报错 name变id
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:bug

#2474 fix: L7符号地图禁用导出图片功能
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
Labels: 类型:bug

#2483 perf: 地图调色手柄文字跟随仪表板主题色
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#2493 fix: 过滤器排序功能代码冲突后被覆盖
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:bug

#2497 fix: 过滤组件排序doris无效
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:bug

#2507 fix: 过滤器弹框文字精简
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:bug

#2508 fix: 过滤组件禁止同数据集多字段
  frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/filter/filterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:bug

#2509 refactor:更新官方示例，新安装系统屏蔽自定义数据集
  backend/src/main/resources/db/migration/V37__1.12.sql
Labels: 类型:优化

#2510 fix: 过滤组件删除默认选项后保存无效
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
Labels: 类型:bug

#2521 fix: pc
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/views/panel/edit/ComponentWait.vue
  frontend/src/views/panel/edit/ComponentWaitItem.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#2530 fix: 过滤条件字段排序导致仪表板一直请求
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/DeWidget/DeSelectTree.vue
Labels: 类型:bug

#2531 fix: 过滤条件选择空数据集给出提示
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:bug

#2532 fix: 过滤器编辑面板参数第一次不能显示
  frontend/src/views/panel/filter/filterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:bug

#2533 feat: 修改初始密码提示优化
  frontend/src/api/user.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/index.vue
Labels: 类型:新功能

#2534 fix: 个人信息页面刷新浏览器后排版错乱
  frontend/src/layout/components/Topbar.vue
Labels: 类型:bug

#2540 perf: 去除虚拟化选项
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:优化
