Repository dataease/dataease, pull requests merged in 2022-12, with the labels that each got.

#3986 fix: 优化水印xpack国际化，防止强制刷新国际化未翻译情况
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:bug

#3987 fix(仪表板): 选项卡组件点击位置出现与视图相同标
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#3994 feat(定时报告): 下载定时报告图片api
  backend/src/main/java/io/dataease/auth/annotation/DeRateLimiter.java
  backend/src/main/java/io/dataease/auth/aop/DeRateLimiterHandler.java
  backend/src/main/java/io/dataease/auth/service/DeLimitService.java
  backend/src/main/java/io/dataease/auth/service/impl/RedisLimitServiceImpl.java
  backend/src/main/java/io/dataease/auth/service/impl/StandaloneLimitServiceImpl.java
  backend/src/main/java/io/dataease/config/RedisConfig.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/resources/scripts/limit.lua
Labels: 类型:新功能

#3999 feat(视图): 透视表列汇总支持按合计排序
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
Labels: 类型:新功能

#4009 fix(i18n): i18n
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/widget/deWidget/DeTabs.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/index.scss
  frontend/src/views/chart/components/componentStyle/XAxisSelector.vue
  frontend/src/views/chart/components/componentStyle/XAxisSelectorAntV.vue
  frontend/src/views/chart/components/componentStyle/YAxisExtSelector.vue
  frontend/src/views/chart/components/componentStyle/YAxisExtSelectorAntV.vue
  frontend/src/views/chart/components/componentStyle/YAxisSelector.vue
  frontend/src/views/chart/components/componentStyle/YAxisSelectorAntV.vue
  frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
  frontend/src/views/chart/components/shapeAttr/TooltipSelector.vue
  frontend/src/views/dataset/data/FieldEdit.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/export/PDFPreExport.vue
  frontend/src/views/panel/linkJumpSet/index.vue
Labels: 类型:bug

#4014 feat(xpack): 钉钉工作台免登进入DataEase
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  frontend/src/permission.js
  frontend/src/router/index.js
  frontend/src/store/modules/permission.js
  frontend/src/views/DeAutoLogin.vue
Labels: 类型:新功能

#4022 fix(视图): 修复明细表总数
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#4027 feat(飞书): 工作台免登进入DataEase
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  frontend/src/api/user.js
  frontend/src/views/DeAutoLogin.vue
Labels: 类型:新功能

#4040 fix(视图): 修复表格斑马纹颜色不能变的问题
  frontend/src/views/chart/chart/common/common_table.js
Labels: 类型:bug

#4042 feat(应用): 应用模板支持选择存量数据源
  backend/src/main/java/io/dataease/commons/constants/PanelConstants.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelAppTemplateApplyRequest.java
  backend/src/main/java/io/dataease/ext/ExtAppLogMapper.xml
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/resources/db/migration/V45__1.18.sql
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/appTemplateMarket/log/index.vue
  frontend/src/views/system/datasource/DsForm.vue
Labels: 类型:新功能

#4044 feat(视图): 文本卡支持阈值
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/components/dragItem/utils.js
  frontend/src/views/chart/components/normal/LabelNormalText.vue
  frontend/src/views/chart/components/senior/Threshold.vue
  frontend/src/views/chart/components/senior/dialog/TextLabelThresholdEdit.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#4048 fix: 仪表板的过滤组件，点击编辑时或者预览时，选择项为白色背景，鼠标点击一下后才恢复为深色背景
  frontend/src/components/widget/deWidget/DeSelect.vue
Labels: 类型:bug

#4049 refactor(仪表板): 增加仪表板取消发布时提示等信息
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:优化

#4052 fix(仪表板): 修复全屏预览部分Tab组件内的下来框无法展开问题
  frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug

#4059 fix(视图): 修复指标卡、文本卡没有垂直居中的问题
  frontend/src/views/chart/components/normal/LabelNormal.vue
Labels: 类型:bug

#4061 fix(视图): 修复明细表总数
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#4063 fix(仪表板): 修复第一次打开仪表板，过滤组件无法过滤 Tab 组件内的视图 #4011
  frontend/src/utils/conditionUtil.js
Labels: 类型:bug

#4066 feat(仪表板): 编辑状态拖拽事件响应区域变更为边缘部分
  frontend/src/api/chart/chart.js
  frontend/src/components/deDrag/index.vue
Labels: 类型:新功能

#4071 fix(视图): 修复复制仪表板后视图计算字段表达式为空的问题 #4062
  backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
Labels: 类型:bug

#4073 fix(视图): 修复复制仪表板后视图计算字段表达式为空的问题 #4062
  backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
Labels: 类型:bug

#4072 feat(数据源): 数据源敏感信息加密
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/dto/DatasourceDTO.java
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  frontend/src/views/system/datasource/DsAppForm.vue
  frontend/src/views/system/datasource/DsFormContent.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:新功能

#4077 fix(仪表板): 修复公共链接中水印导致的控制台异常 #4060
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#4079 fix(仪表板): 修复下拉选过滤组件在适应仪表板自适应缩放时单选和多选高度不一致问题 #4019
  frontend/src/components/dataease/DeOutWidget.vue
Labels: 类型:bug

#4080 fix(仪表板): 修复刚加入的图片组件无法被删除
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#4081 refactor: 调整flyway
  backend/src/main/resources/db/migration/V45__1.17.1.sql
  backend/src/main/resources/db/migration/V46__1.18.sql
Labels: 类型:优化

#4082 fix(移动端): 修复手机端查看仪表板原本未被遮挡的视图，放大后被遮挡了部分的问题 #3967
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#4085 refactor(应用): 优化应用复用历史数据源
  frontend/src/views/system/datasource/DsForm.vue
  frontend/src/views/system/datasource/DsFormContent.vue
Labels: 类型:优化

#4087 feat(视图): 视图计算字段支持复制
  frontend/src/views/chart/view/ChartFieldEdit.vue
Labels: 类型:新功能

#4092 feat(仪表板): 仪表板样式及主题设置支持视图背景图
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:新功能

#4093 refactor(仪表板): 优化仪表板主题预览显示
  frontend/src/views/panel/subjectSetting/preSubject/SubjectTemplateItem.vue
Labels: 类型:优化

#4095 feat(视图): 色彩地图增加标记功能
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  frontend/src/components/deIconPicker/eIcon/e-icon.vue
  frontend/src/components/deIconPicker/eIconList.js
  frontend/src/components/deIconPicker/elementUI.js
  frontend/src/components/deIconPicker/fontAwesome.js
  frontend/src/components/deIconPicker/iconList.js
  frontend/src/components/deIconPicker/index.vue
  frontend/src/components/deIconPicker/utils/TypeUtil.js
  frontend/src/components/deIconPicker/utils/dom.js
  frontend/src/components/deIconPicker/utils/getSvg.js
  frontend/src/components/deIconPicker/utils/index.js
  frontend/src/components/deIconPicker/utils/util.js
  frontend/src/deicons/index.js
  frontend/src/deicons/svg/ai37.svg
  frontend/src/deicons/svg/ai65.svg
  frontend/src/deicons/svg/bumanyi.svg
  frontend/src/deicons/svg/chaping-yuankuang.svg
  frontend/src/deicons/svg/chaping.svg
  frontend/src/deicons/svg/circle.svg
  frontend/src/deicons/svg/cuowuguanbiquxiao-yuankuang.svg
  frontend/src/deicons/svg/five-star.svg
  frontend/src/deicons/svg/gantanhao-yuankuang.svg
  frontend/src/deicons/svg/haoping-yuankuang.svg
  frontend/src/deicons/svg/haoping.svg
  frontend/src/deicons/svg/jiantou-copy-copy-2.svg
  frontend/src/deicons/svg/jiantou-copy-copy-copy.svg
  frontend/src/deicons/svg/jiantou-copy-copy.svg
  frontend/src/deicons/svg/lingxing.svg
  frontend/src/deicons/svg/manyi.svg
  frontend/src/deicons/svg/paixu.svg
  frontend/src/deicons/svg/qizi.svg
  frontend/src/deicons/svg/rect.svg
  frontend/src/deicons/svg/shangjiantou.svg
  frontend/src/deicons/svg/weizhi.svg
  frontend/src/deicons/svg/wenhao-yuankuang.svg
  frontend/src/deicons/svg/wujiaoxing.svg
  frontend/src/deicons/svg/xiajiantou.svg
  frontend/src/deicons/svg/xiangshang.svg
  frontend/src/deicons/svg/xiangyou.svg
  frontend/src/deicons/svg/xiangzuo.svg
  frontend/src/deicons/svg/yiban.svg
  frontend/src/deicons/svg/youjiantou.svg
  frontend/src/deicons/svg/zheng-triangle.svg
  frontend/src/deicons/svg/zhengquewancheng-yuankuang.svg
  frontend/src/deicons/svg/zuojiantou.svg
  frontend/src/deicons/svgo.yml
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/dragItem/DetailItem.vue
  frontend/src/views/chart/components/functionStyle/MapMarkSelector.vue
  frontend/src/views/chart/components/map/MarkMapDataEditor.vue
  frontend/src/views/chart/components/table/TableNormal.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartStyle.vue
  frontend/vue.config.js
Labels: 类型:新功能

#4098 refactor(仪表板): 新增默认仪表板主题
  backend/src/main/resources/db/migration/V47__1.18-panel-subject-add.sql
  frontend/src/components/canvas/utils/style.js
Labels: 类型:优化

#4102 perf(登录): 第三方平台内免登进入DE隐藏登录以及修改密码按钮
  backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
  backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  frontend/src/layout/components/Topbar.vue
  frontend/src/utils/index.js
Labels: 类型:优化

#4103 fix(仪表板): 修复部分仪表板中模图片导出模板后再跨服务导入图片无法显示的问题
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#4106 fix(仪表板): 修复vuex中mobileLayoutStatus状态问题
  frontend/src/components/canvas/components/editor/PreviewEject.vue
  frontend/src/store/index.js
Labels: 类型:bug

#4107 feat(过滤器): 文本下拉组件选项可按照中文排序
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetFieldService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/filter/filterMain/FilterSort.vue
Labels: 类型:新功能

#4111 fix(视图): 修复设置默认时间后手动清除默认时间再复制视图显示数据依然是默认时间设置的数据
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/store/index.js
Labels: 类型:bug

#4112 perf(定时报告): 增加任务状态字段
  backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/resources/db/migration/V46__1.18.sql
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#4114 refactor(视图): 快速计算占比切换至其他类型时重置数值格式
  frontend/src/views/chart/components/dragItem/QuotaExtItem.vue
  frontend/src/views/chart/components/dragItem/QuotaItem.vue
Labels: 类型:优化

#4115 feat(视图): 视图计算字段支持复制
  frontend/src/views/chart/view/ChartFieldEdit.vue
Labels: 类型:新功能

#4117 feat: 过滤组件绑定参数优化,可直接展示数据集中的参数
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/controller/datasource/request/UpdataDsRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelAppTemplateApplyRequest.java
  backend/src/main/java/io/dataease/dto/DatasourceDTO.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
  frontend/src/api/dataset/dataset.js
  frontend/src/views/panel/filter/FilterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
  frontend/src/views/system/datasource/DsAppForm.vue
  frontend/src/views/system/datasource/DsFormContent.vue
Labels: 类型:新功能

#4118 feat(插件管理): 集群环境依赖redis的插件操作功能
  backend/src/main/java/io/dataease/commons/utils/IPUtils.java
  backend/src/main/java/io/dataease/plugins/entity/PluginOperate.java
  backend/src/main/java/io/dataease/service/redis/impl/PluginMsgService.java
  backend/src/main/java/io/dataease/service/sys/DistributedPluginService.java
  backend/src/main/java/io/dataease/service/sys/PluginService.java
Labels: 类型:新功能

#4119 feat(仪表板): 仪表板刷新时，过滤组件的备选项同时更新
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/deWidget/DeSelect.vue
  frontend/src/components/widget/deWidget/DeSelectGrid.vue
  frontend/src/components/widget/deWidget/DeSelectTree.vue
Labels: 类型:新功能

#4120 perf(地图): 优化图标选择器组件
  frontend/src/components/deIconPicker/deIconGroupPicker/index.vue
  frontend/src/components/deIconPicker/iconList.js
  frontend/src/deicons/svg/1-trend-01-topright.svg
  frontend/src/deicons/svg/1-trend-02-bottomright.svg
  frontend/src/deicons/svg/1-trend-03-topleft.svg
  frontend/src/deicons/svg/1-trend-04-bottomleft.svg
  frontend/src/deicons/svg/1-trend-05-top.svg
  frontend/src/deicons/svg/1-trend-06-right.svg
  frontend/src/deicons/svg/1-trend-07-left.svg
  frontend/src/deicons/svg/1-trend-08-bottom.svg
  frontend/src/deicons/svg/1-trend-09-top1.svg
  frontend/src/deicons/svg/1-trend-10-bottom1.svg
  frontend/src/deicons/svg/1-trend-11-left1.svg
  frontend/src/deicons/svg/1-trend-12-right1.svg
  frontend/src/deicons/svg/2-state-01-diamond.svg
  frontend/src/deicons/svg/2-state-02-triangle.svg
  frontend/src/deicons/svg/2-state-03-circle.svg
  frontend/src/deicons/svg/2-state-04-pentagon.svg
  frontend/src/deicons/svg/2-state-05-square.svg
  frontend/src/deicons/svg/2-state-06-flag.svg
  frontend/src/deicons/svg/2-state-07-error.svg
  frontend/src/deicons/svg/2-state-08-warn.svg
  frontend/src/deicons/svg/2-state-09-question.svg
  frontend/src/deicons/svg/2-state-10-ok.svg
  frontend/src/deicons/svg/3-rank-01-half.svg
  frontend/src/deicons/svg/3-rank-02-full.svg
  frontend/src/deicons/svg/3-rank-03-nice.svg
  frontend/src/deicons/svg/3-rank-04-commonly.svg
  frontend/src/deicons/svg/3-rank-05-bad.svg
  frontend/src/deicons/svg/3-rank-06-goodevaluate.svg
  frontend/src/deicons/svg/3-rank-07-badevaluate.svg
  frontend/src/deicons/svg/3-rank-08-badevaluatecircle.svg
  frontend/src/deicons/svg/3-rank-08-goodevaluatecircle.svg
  frontend/src/deicons/svg/4-location-01-mark.svg
  frontend/src/deicons/svg/4-location-02-mark1.svg
  frontend/src/deicons/svg/4-location-03-mark2.svg
  frontend/src/deicons/svg/4-location-04-location.svg
  frontend/src/deicons/svg/4-location-05-location1.svg
  frontend/src/deicons/svg/4-location-06-location2.svg
  frontend/src/deicons/svg/4-location-07-map.svg
  frontend/src/deicons/svg/4-location-08-map1.svg
  frontend/src/deicons/svg/5-weather-01-bigsnow.svg
  frontend/src/deicons/svg/5-weather-02-littlesnow.svg
  frontend/src/deicons/svg/5-weather-03-bigrain.svg
  frontend/src/deicons/svg/5-weather-04-littlerain.svg
  frontend/src/deicons/svg/5-weather-05-icerain.svg
  frontend/src/deicons/svg/5-weather-06-snowrain.svg
  frontend/src/deicons/svg/5-weather-07-sunny.svg
  frontend/src/deicons/svg/5-weather-08-cloudy.svg
  frontend/src/deicons/svg/5-weather-09-smog.svg
  frontend/src/deicons/svg/5-weather-10-typhoon.svg
  frontend/src/deicons/svg/5-weather-11-wind.svg
  frontend/src/deicons/svg/5-weather-12-thunder.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/functionStyle/MapMarkSelector.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:优化

#4121 perf(地图): 优化地图后台逻辑
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:优化

#4123 refactor(仪表板): 超长仪表板导出PDF、图片优化
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/views/panel/export/PDFPreExport.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:优化

#4124 feat: 支持复制数据源
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/datasource/DsForm.vue
  frontend/src/views/system/datasource/DsFormContent.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:新功能

#4125 feat(系统管理): 增加血缘关系菜单路由
  backend/src/main/resources/db/migration/V46__1.18.sql
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/icons/svg/sys-relationship.svg
  frontend/src/views/system/relationship/index.vue
Labels: 类型:新功能

#4126 fix(血缘关系): sql中删除数据库名称
  backend/src/main/resources/db/migration/V46__1.18.sql
Labels: 类型:bug

#4127 refactor(仪表板): 网页组件文案优化
  frontend/src/components/canvas/customComponent/DeFrame.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#4129 fix(用户管理): 钉钉用户因为username为纯数字导致无法修改DE用户信息
  frontend/src/views/system/user/UserEditer.vue
Labels: 类型:bug

#4130 perf(版本号): 规范发布版本号
  backend/src/main/resources/db/migration/V46__1.18.sql
Labels: 类型:优化

#4131 fix(地图): 地图下钻报错
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
Labels: 类型:bug

#4132 fix(登录): 登录过期失效
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
Labels: 类型:bug

#4134 fix(仪表板): 删除Tab画布时同时清理对应画布的组件
  frontend/src/components/widget/deWidget/DeTabs.vue
  frontend/src/store/index.js
Labels: 类型:bug

#4135 refactor(模板市场): 模板市场优化去掉应用系列分类
  backend/src/main/java/io/dataease/service/templateMarket/TemplateMarketService.java
Labels: 类型:优化

#4136 fix(过滤器): 时间范围过滤器参数设置多个数据集时异常
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:bug

#4138 feat(视图): 柱状图、折线图支持结果隐藏空数据
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/line/line_antv.js
  frontend/src/views/chart/components/senior/FunctionCfg.vue
Labels: 类型:新功能

#4139 feat(视图): 柱状图、折线图支持结果隐藏空数据
  frontend/src/views/chart/components/senior/FunctionCfg.vue
Labels: 类型:新功能

#4145 feat(视图): 视图可以单独设置刷新频率
  backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
  backend/src/main/resources/db/migration/V46__1.18.sql
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/store/index.js
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/panel/subjectSetting/panelStyle/OverallSetting.vue
Labels: 类型:新功能

#4146 Merge branch 'dev' into pr@dev@feat_relationship_analyze
  backend/src/main/java/io/dataease/controller/sys/RelationController.java
  backend/src/main/java/io/dataease/dto/RelationDTO.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.java
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.java
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.java
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
  backend/src/main/java/io/dataease/service/sys/RelationService.java
Labels: 类型:新功能

#4148 fix(视图): 修复明细表结果展示条数与分页模式冲突的问题
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#4149 feat(视图): 柱状图、折线图支持结果隐藏空数据
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/formatter.js
  frontend/src/views/chart/components/senior/FunctionCfg.vue
Labels: 类型:新功能

#4154 refactor(视图): 优化深色主题下图例翻页标识
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/ChartComponentG2.vue
Labels: 类型:优化

#4155 refactor(仪表板): 优化仪表板拖拽区
  frontend/src/components/deDrag/index.vue
Labels: 类型:优化

#4157 Merge branch 'dev' into pr@dev@feat_relationship_analyze
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.java
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/views/chart/chart/common/common_antv.js
Labels: 类型:新功能

#4160 fix(插件): 兼容已安装的第三方插件版本号
  backend/src/main/java/io/dataease/plugins/config/PluginRunner.java
Labels: 类型:bug

#4162 fix(地图): 指标字段可以添加到经纬度
  frontend/src/views/chart/components/map/MarkMapDataEditor.vue
Labels: 类型:bug

#4164 perf(插件): 限制官方插件更新卸载
  backend/src/main/java/io/dataease/service/sys/PluginService.java
  frontend/src/views/system/plugin/index.vue
Labels: 类型:优化

#4167 perf(地图): 标记地图经纬度字段删除图标样式
  frontend/src/views/chart/components/dragItem/DetailItem.vue
Labels: 类型:优化

#4168 perf(视图): 明细数据合并单元格后禁止排序
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:优化

#4169 feat(视图): 透视表增加表头行列点击事件
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/ChartComponentS2.vue
Labels: 类型:新功能

#4170 feat(仪表板): s2表格支持点击行头列头跳转并在跳转是带入其他相关字段匹配
  backend/src/main/java/io/dataease/ext/ExtPanelLinkJumpMapper.xml
  frontend/src/components/canvas/components/editor/PreviewEject.vue
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/panel/linkJumpSet/index.vue
Labels: 类型:新功能

#4171 fix: SQL参数在过滤组件中按表选择字段时出现重复的情况
  backend/src/main/java/io/dataease/commons/utils/HttpClientUtil.java
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/service/authModel/VAuthModelService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/assets/datasource/db2.jpg
  frontend/src/assets/datasource/hive.jpg
  frontend/src/assets/datasource/impala.jpg
  frontend/src/views/panel/filter/FilterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
  frontend/src/views/system/datasource/DsAppForm.vue
  frontend/src/views/system/datasource/DsConfiguration.vue
Labels: 类型:bug

#4172 fix(视图): 修复表格下钻后下钻列位置偏移的问题
  frontend/src/views/chart/chart/table/table-info.js
Labels: 类型:bug

#4175 perf(地图): 导出excel合并单元格
  backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/ViewDetailField.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/components/canvas/customComponent/UserViewDialog.vue
Labels: 类型:优化

#4176 fix(地图): 标签无法显示
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/chart/util.js
Labels: 类型:bug

#4177 fix(视图): 复制视图缺少view_fields字段
  backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
Labels: 类型:bug

#4179 fix(地图): 切换数据集后标记字段没有消失
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/functionStyle/MapMarkSelector.vue
  frontend/src/views/chart/components/map/MarkMapDataEditor.vue
Labels: 类型:bug

#4182 feat(视图): MySQL时间字段支持按季度、周统计
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/components/dragItem/DimensionExtItem.vue
  frontend/src/views/chart/components/dragItem/DimensionItem.vue
  frontend/src/views/chart/components/dragItem/QuotaExtItem.vue
  frontend/src/views/chart/components/dragItem/QuotaItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#4189 refactor(视图): 优化视图刷新时间限制
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#4190 fix(视图): 修复切换图库后开启视图刷新导致字段消失的问题
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#4191 feat(视图): 透视表支持合计列汇总
  frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
Labels: 类型:新功能

#4194 feat(视图): 透视表支持合计列汇总
  frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
Labels: 类型:新功能

#4196 fix: 定时任务状态
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
Labels: 类型:bug

#4195 refactor(仪表板): 媒体链接设置等提示文案修改
  frontend/src/components/canvas/customComponent/DeFrame.vue
  frontend/src/components/canvas/customComponent/DeStreamMedia.vue
  frontend/src/components/canvas/customComponent/DeVideo.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#4198 fix(仪表板): 解决仪表板快捷键与浏览器快捷键冲突问题，优先仪表板编辑区快捷键生效
  frontend/src/components/canvas/utils/shortcutKey.js
Labels: 类型:bug

#4199 fix(过滤器): sqlserver查询精确到毫秒的源数据有误差
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:bug

#4201 refactor(仪表板): 优化编辑界面复用功能键盘监听，防止关闭复用界面导致键盘监听事件失效
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/utils/shortcutKey.js
Labels: 类型:优化

#4204 refactor(仪表板): 调整仪表板快捷键事件
  frontend/src/components/canvas/utils/shortcutKey.js
Labels: 类型:优化

#4206 feat(仪表板): AntV 透视表格支持点击行头列头跳转并在跳转时带入其他相关字段进行匹配
  frontend/src/components/canvas/components/editor/PreviewEject.vue
  frontend/src/views/chart/components/ChartComponentS2.vue
Labels: 类型:新功能

#4207 refactor: 优化公共链接透视表跳转
  frontend/src/views/link/view/index.vue
Labels: 类型:优化

#4209 refactor(视图): 优化视图格式化，防止出现空值不显示的情况
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:优化

#4210 fix(血源分析): 优化血源关系查询结果
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
Labels: 类型:bug

#4212 refactor: 更改TiDB图标
  frontend/src/assets/datasource/TiDB.jpg
Labels: 类型:优化

#4216 refactor(仪表板): 优化键盘事件
  frontend/src/components/canvas/utils/shortcutKey.js
Labels: 类型:优化

#4218 refactor(仪表板): 富文本编辑区和拖拽区优化
  frontend/src/components/canvas/customComponent/DeRichText.vue
  frontend/src/components/deDrag/index.vue
  frontend/src/store/index.js
Labels: 类型:优化

#4214 fix: 解析csv文件异常
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#4219 fix(仪表板): 修复从收藏tab切换至仪表板tab页面右侧没有内容显示
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/panel/list/PanelMain.vue
Labels: 类型:bug

#4220 fix(视图): 日期格式受数据源控制
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/dragItem/DimensionExtItem.vue
  frontend/src/views/chart/components/dragItem/DimensionItem.vue
Labels: 类型:bug

#4224 refactor(血源分析-数据集): 调整数据集血缘关系查询结果
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
Labels: 类型:优化

#4229 fix: 解析sql错误
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#4231 refactor(仪表板): Tab内组件复制的组件还放置在tab内部
  frontend/src/components/canvas/store/copy.js
Labels: 类型:优化

#4232 fix(应用): 修复更新应用时缩略图可能未更新的情况
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
Labels: 类型:bug

#4233 fix: 同步数据分页错误
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
Labels: 类型:bug

#4236 refactor(仪表板): 调整Tab组件的拖拽区，Tab组件拖拽区固定在头部防止与内部组件拖拽区域冲突
  frontend/src/components/deDrag/index.vue
Labels: 类型:优化

#4241 refactor: 更新默认管理员权限
  backend/src/main/resources/db/migration/V46__1.18.sql
  frontend/src/views/panel/list/PanelMain.vue
Labels: 类型:优化

#4243 fix: 修复收藏tab切换至仪表板tab页面右侧没有内容显示
  frontend/src/views/panel/list/PanelMain.vue
Labels: 类型:bug

#4244 fix(血源关系): 修复存在多个 Excel 数据集依赖时的报错
  backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:bug

#4245 fix: 同步数据分页错误
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
Labels: 类型:bug

#4246 fix(地图): 跟随仪表板复制后丢失经纬度以及标记字段
  backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
Labels: 类型:bug

#4248 refactor(仪表板): 增加仪表板跳转外部链接URL非法提示
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#4250 fix(api): api文档token无法续命
  backend/src/main/java/io/dataease/auth/filter/F2CDocFilter.java
Labels: 类型:bug
