Repository dataease/dataease, pull requests merged in 2022-01, with the labels that each got.

#1583 fix: 移动端分页api
  backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.xml
  backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java
  backend/src/main/java/io/dataease/mobile/api/DirApi.java
  backend/src/main/java/io/dataease/mobile/api/HomeApi.java
  backend/src/main/java/io/dataease/mobile/api/MeApi.java
  backend/src/main/java/io/dataease/mobile/dto/DirItemDTO.java
  backend/src/main/java/io/dataease/mobile/dto/DirRequest.java
  backend/src/main/java/io/dataease/mobile/dto/HomeItemDTO.java
  backend/src/main/java/io/dataease/mobile/dto/HomeRequest.java
  backend/src/main/java/io/dataease/mobile/dto/MeItemDTO.java
  backend/src/main/java/io/dataease/mobile/server/HomeServer.java
  backend/src/main/java/io/dataease/mobile/service/HomeService.java
Labels: 类型:bug

#1586 fix: 移动端目录上下滑动不顺畅
  mobile/.gitignore
  mobile/src/pages/tabBar/dir/index.vue
  mobile/src/static/panelimg/panel1.png
  mobile/src/static/panelimg/panel2.png
Labels: 类型:bug

#1588 fix: 移动端版本号
  mobile/pom.xml
Labels: 类型:bug

#1591 fix: 移动端首页加载更多不自动消失
  mobile/src/pages/tabBar/dir/index.vue
  mobile/src/pages/tabBar/home/index.nvue
Labels: 类型:bug

#1593 fix: 数据集权限树
  backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
Labels: 类型:bug

#1594 fix: 周表达式无效
  backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java
Labels: 类型:bug

#1598 fix: 直连SQL数据集不支持制作关联数据集
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/add/AddUnion.vue
Labels: 类型:bug

#1599 fix: 直连SQL数据集不支持制作关联数据集
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/add/AddUnion.vue
Labels: 类型:bug

#1605 fix: 动态时间组件
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
  frontend/src/views/panel/filter/filterMain/FilterFoot.vue
Labels: 类型:bug

#1609 feat(数据集): 计算字段语法校验
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:新功能

#1610 fix: 动态日期过滤组件月份逻辑
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
  frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
Labels: 类型:bug

#1611 fix: 多字段枚举NPE异常
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
Labels: 类型:bug

#1612 fix: 邮件预览日志
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
Labels: 类型:bug

#1622 feat: 年份、年月组件增加动态时间
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
  frontend/src/views/panel/filter/filterMain/FilterFoot.vue
Labels: 类型:新功能

#1624 refactor: 视图样式配置项调整
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/liquid/liquid.js
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
  frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#1626 refactor: 优化主题切换
  backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#1627 fix: 修复左侧tree重命名右侧更新不及时的问题
  frontend/src/store/getters.js
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:bug

#1628 refactor: 优化年月过滤组件动态时间
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:优化

#1629 fix: 修复左侧tree重命名右侧更新不及时的问题
  frontend/src/store/getters.js
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:bug

#1630 fix: 地图复位中心点错误
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#1631 refactor: 去除mobile的编译目录
  mobile/dist/build/.automator/h5/.automator.json
  mobile/dist/build/h5/index.html
  mobile/dist/build/h5/static/DataEase-01.png
  mobile/dist/build/h5/static/about.png
  mobile/dist/build/h5/static/dir.png
  mobile/dist/build/h5/static/folder-close.png
  mobile/dist/build/h5/static/folder-open.png
  mobile/dist/build/h5/static/folder.png
  mobile/dist/build/h5/static/fonts/uni.75745d34.ttf
  mobile/dist/build/h5/static/home.png
  mobile/dist/build/h5/static/img/DataEase-01.b9bf8897.png
  mobile/dist/build/h5/static/img/logo-bg.e3894578.jpg
  mobile/dist/build/h5/static/img/user.1e5d0b29.png
  mobile/dist/build/h5/static/index.a5c69d49.css
  mobile/dist/build/h5/static/js/chunk-vendors.2822c2ee.js
  mobile/dist/build/h5/static/js/index.12bd8b7a.js
  mobile/dist/build/h5/static/js/pages-index-index.c4389d2e.js
  mobile/dist/build/h5/static/js/pages-login-index.3d0da2f3.js
  mobile/dist/build/h5/static/js/pages-login-index~pages-tabBar-dir-folder~pages-tabBar-dir-index~pages-tabBar-dir-search~pages-tabBa~a44ba637.9affcae7.js
  mobile/dist/build/h5/static/js/pages-tabBar-dir-folder.79329ccc.js
  mobile/dist/build/h5/static/js/pages-tabBar-dir-folder~pages-tabBar-dir-index~pages-tabBar-home-detail~pages-tabBar-me-about~pages-~aae7fe21.cb9438bf.js
  mobile/dist/build/h5/static/js/pages-tabBar-dir-index.de037b26.js
  mobile/dist/build/h5/static/js/pages-tabBar-dir-search.1c4fdeee.js
  mobile/dist/build/h5/static/js/pages-tabBar-home-detail.9ffb65b4.js
  mobile/dist/build/h5/static/js/pages-tabBar-home-index.dbcbfb00.js
  mobile/dist/build/h5/static/js/pages-tabBar-me-about.2943630b.js
  mobile/dist/build/h5/static/js/pages-tabBar-me-index.8ad5856a.js
  mobile/dist/build/h5/static/js/pages-tabBar-me-language.f2cb05fe.js
  mobile/dist/build/h5/static/js/pages-tabBar-me-outlink.f2df7eb4.js
  mobile/dist/build/h5/static/js/pages-tabBar-me-person.43d2b31a.js
  mobile/dist/build/h5/static/language.png
  mobile/dist/build/h5/static/login-logo.png
  mobile/dist/build/h5/static/logo-bg.jpg
  mobile/dist/build/h5/static/logo.png
  mobile/dist/build/h5/static/me.png
  mobile/dist/build/h5/static/msg.png
  mobile/dist/build/h5/static/uni.png
  mobile/dist/build/h5/static/uni.ttf
  mobile/dist/build/h5/static/user.png
  mobile/dist/build/h5/static/yibiaobans.png
Labels: 类型:优化

#1634 feat: 默认密码
  backend/src/main/java/io/dataease/auth/api/AuthApi.java
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  frontend/src/api/user.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/components/Topbar.vue
  frontend/src/layout/index.vue
  frontend/src/views/system/user/form.vue
Labels: 类型:新功能

#1635 fix: 修改密码向导被首页遮盖
  frontend/src/layout/index.vue
Labels: 类型:bug

#1636 feat: 仪表板允许对原有图片组件直接更换
  frontend/src/components/canvas/components/Editor/EditBar.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/styles/deicon/demo_index.html
  frontend/src/styles/deicon/iconfont.css
  frontend/src/styles/deicon/iconfont.js
  frontend/src/styles/deicon/iconfont.json
  frontend/src/styles/deicon/iconfont.ttf
  frontend/src/styles/deicon/iconfont.woff
  frontend/src/styles/deicon/iconfont.woff2
Labels: 类型:新功能

#1638 feat: 定时报告使用优先级线程池
  backend/src/main/java/io/dataease/base/mapper/ext/ExtTaskMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtTaskMapper.xml
  backend/src/main/java/io/dataease/commons/pool/PriorityThreadPoolExecutor.java
  backend/src/main/java/io/dataease/commons/pool/PriorityThreadPoolProperties.java
  backend/src/main/java/io/dataease/config/AsyncConfig.java
  backend/src/main/java/io/dataease/job/sechedule/ScheduleManager.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/listener/GlobalTaskStartListener.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
Labels: 类型:新功能

#1643 fix: 过滤组件默认值不能覆盖编辑的预览值
  frontend/src/components/canvas/utils/utils.js
  frontend/src/components/widget/DeWidget/DeDate.vue
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/DeWidget/DeNumberRange.vue
  frontend/src/components/widget/DeWidget/DeSelect.vue
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
  frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
  frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
Labels: 类型:bug

#1644 fix: token超时时间计算错误
  backend/src/main/java/io/dataease/auth/util/JWTUtils.java
Labels: 类型:bug

#1645 fix: 动态年月逻辑错误
  frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
Labels: 类型:bug

#1648 refactor: 修复冲突
  backend/pom.xml
  backend/src/main/java/io/dataease/commons/constants/ColumnPermissionConstants.java
  backend/src/main/java/io/dataease/commons/license/DefaultLicenseService.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableFieldsService.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/PermissionService.java
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  backend/src/main/resources/db/migration/V31__1.7.sql
  backend/src/main/resources/generatorConfig.xml
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:优化

#1665 Revert "refactor: 去掉无用代码"
  backend/src/main/java/io/dataease/mobile/service/DirService.java
Labels: 类型:优化

#1673 fix: 我分享的仪表板展示空tags
  backend/src/main/java/io/dataease/service/panel/ShareService.java
Labels: 类型:bug

#1674 refactor: 优化设计缺陷,增加展示字段
  backend/src/main/java/io/dataease/commons/utils/CronUtils.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#1675 fix: xpack菜单重启后偶尔加载不出来
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
Labels: 类型:bug

#1678 refactor: 优化空仪表板收藏状态
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:优化

#1679 refactor: 优化年份组件文案
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#1684 pr@v1.7@refactor_panel-mobile
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
Labels: 类型:优化

#1687 feat: api权限验证基本功能以及仪表板增删改权限demo
  backend/pom.xml
  backend/src/main/java/io/dataease/auth/annotation/DePermission.java
  backend/src/main/java/io/dataease/auth/annotation/DePermissions.java
  backend/src/main/java/io/dataease/auth/aop/DePermissionAnnotationHandler.java
  backend/src/main/java/io/dataease/auth/config/F2CRealm.java
  backend/src/main/java/io/dataease/auth/entity/AuthItem.java
  backend/src/main/java/io/dataease/auth/service/ExtAuthService.java
  backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.java
  backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.xml
  backend/src/main/java/io/dataease/commons/constants/AuthConstants.java
  backend/src/main/java/io/dataease/commons/constants/DePermissionType.java
  backend/src/main/java/io/dataease/commons/constants/ResourceAuthLevel.java
  backend/src/main/java/io/dataease/commons/model/UserPermissionItem.java
  backend/src/main/java/io/dataease/commons/utils/AuthUtils.java
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
  backend/src/main/java/io/dataease/service/sys/SysUserService.java
  backend/src/main/resources/ehcache/ehcache.xml
Labels: 类型:新功能

#1689 fix(table): 明细表默认分页数适配旧版本创建的视图
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#1690 fix(table): 明细表默认分页数适配旧版本创建的视图
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#1693 fix: AntV线宽
  frontend/src/views/chart/chart/line/line_antv.js
Labels: 类型:bug

#1694 fix: 邮箱连接失败错误信息翻译
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#1695 fix: AntV线宽
  frontend/src/views/chart/chart/line/line_antv.js
Labels: 类型:bug

#1696 fix: 移动端加载提示国际化
  mobile/src/locale/en.json
  mobile/src/locale/zh-Hans.json
  mobile/src/locale/zh-Hant.json
  mobile/src/pages/tabBar/home/detail.nvue
Labels: 类型:bug

#1697 fix: 列表新增按钮迷之消失
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  frontend/src/views/system/plugin/dynamic.vue
  frontend/src/views/system/user/index.vue
Labels: 类型:bug

#1698 fix: 下拉列表组件逻辑错误
  frontend/src/components/widget/DeWidget/DeSelectGrid.vue
Labels: 类型:bug

#1699 refactor: 首页优化
  backend/src/main/java/io/dataease/service/wizard/ReptileService.java
  frontend/src/views/wizard/details/CardDetail.vue
  frontend/src/views/wizard/index.vue
Labels: 类型:优化

#1700 fix: 组件属性框直接输入值无法保存问题
  frontend/src/components/canvas/store/snapshot.js
Labels: 类型:bug

#1701 fix: 指标拖拽问题
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#1702 fix: 指标拖拽问题
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#1704 fix: 仪表板过滤组件首次加载失效
  frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/Editor/Preview.vue
  frontend/src/components/canvas/components/Editor/index.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
  frontend/src/utils/conditionUtil.js
Labels: 类型:bug

#1705 fix: 主题名称重复提示国际化
  backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#1706 fix: 统一授权后，分组tree参数修正
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/dataset/group/Group.vue
Labels: 类型:bug

#1707 refactor: 优化地图标签选项
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
Labels: 类型:优化

#1708 refactor: 优化地图标签选项
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
Labels: 类型:优化

#1709 fix: favicon迷之消失
  backend/pom.xml
Labels: 类型:bug

#1710 fix: 仪表板编辑显示空白
  frontend/src/components/canvas/components/Editor/index.vue
Labels: 类型:bug

#1711 refactor: 修改移动端打包路径
  backend/pom.xml
  mobile/.gitignore
  mobile/package.json
Labels: 类型:优化

#1712 fix: 数字区间组件不能正常显示
  frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js
Labels: 类型:bug

#1716 fix: 日期范围动态时间季度错误
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
Labels: 类型:bug

#1717 fix: 文本过滤组件空默认值异常
  frontend/src/components/widget/DeWidget/DeInputSearch.vue
  frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js
Labels: 类型:bug

#1719 fix: 仪表板背景由颜色切换为图片，未加图片时背景颜色依然存在问题
  frontend/src/components/canvas/components/Editor/PreviewEject.vue
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#1720 fix: 仪表板背景由颜色切换为图片，未加图片时背景颜色依然存在问题
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#1722 fix: 移动端搜索出不存在的目录
  backend/src/main/java/io/dataease/mobile/service/DirService.java
  mobile/src/pages/tabBar/dir/search.vue
Labels: 类型:bug
