Repository dataease/dataease, pull requests merged in 2022-02, with the labels that each got.

#1725 feat: S2
  frontend/package.json
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common_table.js
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1726 feat: S2 Event
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/ChartComponentS2.vue
Labels: 类型:新功能

#1727 fix: 数字范围默认值导致仪表板空白
  frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js
Labels: 类型:bug

#1728 fix: 条件组件兼容老版本
  frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js
  frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
Labels: 类型:bug

#1729 fix: 解压zip未判断子目录
  backend/src/main/java/io/dataease/commons/utils/ZipUtils.java
Labels: 类型:bug

#1737 fix: 日期过滤默认值兼容老版本
  frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
  frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
Labels: 类型:bug

#1739 fix: api权限单独处理admin
  backend/src/main/java/io/dataease/auth/aop/DePermissionAnnotationHandler.java
Labels: 类型:bug

#1742 refactor: 移动端仪表板详情外层布局
  mobile/src/components/uni-col/uni-col.vue
  mobile/src/components/uni-icons/icons.js
  mobile/src/components/uni-icons/uni-icons.vue
  mobile/src/components/uni-icons/uni.ttf
  mobile/src/components/uni-row/uni-row.vue
  mobile/src/pages/tabBar/home/detail.nvue
  mobile/src/uni_modules/uni-icons/changelog.md
  mobile/src/uni_modules/uni-icons/components/uni-icons/icons.js
  mobile/src/uni_modules/uni-icons/components/uni-icons/uni-icons.vue
  mobile/src/uni_modules/uni-icons/components/uni-icons/uniicons.css
  mobile/src/uni_modules/uni-icons/components/uni-icons/uniicons.ttf
  mobile/src/uni_modules/uni-icons/package.json
  mobile/src/uni_modules/uni-icons/readme.md
  mobile/src/uni_modules/uni-nav-bar/changelog.md
  mobile/src/uni_modules/uni-nav-bar/components/uni-nav-bar/uni-nav-bar.vue
  mobile/src/uni_modules/uni-nav-bar/components/uni-nav-bar/uni-status-bar.vue
  mobile/src/uni_modules/uni-nav-bar/package.json
  mobile/src/uni_modules/uni-nav-bar/readme.md
  mobile/src/uni_modules/uni-scss/changelog.md
  mobile/src/uni_modules/uni-scss/index.scss
  mobile/src/uni_modules/uni-scss/package.json
  mobile/src/uni_modules/uni-scss/readme.md
  mobile/src/uni_modules/uni-scss/styles/index.scss
  mobile/src/uni_modules/uni-scss/styles/setting/_border.scss
  mobile/src/uni_modules/uni-scss/styles/setting/_color.scss
  mobile/src/uni_modules/uni-scss/styles/setting/_radius.scss
  mobile/src/uni_modules/uni-scss/styles/setting/_space.scss
  mobile/src/uni_modules/uni-scss/styles/setting/_styles.scss
  mobile/src/uni_modules/uni-scss/styles/setting/_text.scss
  mobile/src/uni_modules/uni-scss/styles/setting/_variables.scss
  mobile/src/uni_modules/uni-scss/styles/tools/functions.scss
  mobile/src/uni_modules/uni-scss/theme.scss
  mobile/src/uni_modules/uni-scss/variables.scss
Labels: 类型:优化

#1743 feat: S2 pivot
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1747 fix: 修复地图范围不受权限控制的问题
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#1748 feat: S2 pivot
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#1752 refactor: 格式化代码
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#1755 fix: 移动端详情页面布局
  mobile/src/pages.json
  mobile/src/pages/tabBar/home/detail.nvue
Labels: 类型:bug

#1756 feat: 仪表板集成插件视图
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:新功能

#1759 fix: 新建资源缓存一致性问题
  backend/src/main/java/io/dataease/auth/annotation/DeCleaner.java
  backend/src/main/java/io/dataease/auth/aop/DeCleanerAnnotationHandler.java
  backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
  backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#1761 refactor: 视图字段增加校验提示
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/components/drag-item/DimensionExtItem.vue
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/DrillItem.vue
  frontend/src/views/chart/components/drag-item/FilterItem.vue
  frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/components/drag-item/components/FieldErrorTips.vue
  frontend/src/views/chart/components/drag-item/utils.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:优化

#1763 refactor: 增加数据源、部分数据集api权限
  backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.xml
  backend/src/main/java/io/dataease/commons/utils/AuthUtils.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
  backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
  backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XDisplayServer.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/java/io/dataease/plugins/server/XLdapServer.java
  backend/src/main/java/io/dataease/plugins/server/XOidcServer.java
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
Labels: 类型:优化

#1766 feat: 公共连接title展示当前仪表板名称
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  frontend/src/views/link/view/index.vue
Labels: 类型:新功能

#1768 feat: 公共链接使用8位随机字符后缀,兼容老版本数字后缀
  backend/src/main/java/io/dataease/base/domain/PanelLinkMapping.java
  backend/src/main/java/io/dataease/base/domain/PanelLinkMappingExample.java
  backend/src/main/java/io/dataease/base/mapper/PanelLinkMappingMapper.xml
  backend/src/main/java/io/dataease/commons/utils/CodingUtil.java
  backend/src/main/java/io/dataease/controller/IndexController.java
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  backend/src/main/resources/db/migration/V32__1.8.sql
Labels: 类型:新功能

#1769 feat: 分享显示名优化
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml
Labels: 类型:新功能

#1770 refactor: 基础景象
  Dockerfile
Labels: 类型:优化

#1771 feat: 移动端图标颜色调整
  mobile/src/pages.json
  mobile/src/static/dir_select.png
  mobile/src/static/home_select.png
  mobile/src/static/me.png
  mobile/src/static/me_select.png
Labels: 类型:新功能

#1772 refactor: 切换镜像源
  Dockerfile
Labels: 类型:优化

#1773 refactor: 切换chromium镜像
  Dockerfile
Labels: 类型:优化

#1774 feat: S2 pivot
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common_table.js
  frontend/src/views/chart/components/ChartComponentS2.vue
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
Labels: 类型:新功能

#1775 refactor: 重构公共链接短链接
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
  frontend/src/views/link/generate/index.vue
Labels: 类型:优化

#1776 fix: 重新开启链接后，老的链接无效
  backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
Labels: 类型:bug

#1780 feat: S2 pivot align
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/common/common_table.js
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
Labels: 类型:新功能

#1783 refactor: 仪表板兼容插件视图
  backend/src/main/java/io/dataease/base/domain/ChartView.java
  backend/src/main/java/io/dataease/base/domain/ChartViewExample.java
  backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java
  backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml
  backend/src/main/resources/db/migration/V32__1.8.sql
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartType.vue
Labels: 类型:优化

#1784 feat: 兼容插件视图样式设置
  frontend/src/components/AsyncComponent/index.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/system/plugin/PluginCom.vue
Labels: 类型:新功能

#1788 feat: 视图权限跟随仪表板
  frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue
  frontend/src/views/chart/components/component-style/LegendSelector.vue
  frontend/src/views/chart/components/component-style/LegendSelectorAntV.vue
  frontend/src/views/chart/components/component-style/SplitSelector.vue
  frontend/src/views/chart/components/component-style/SplitSelectorAntV.vue
  frontend/src/views/chart/components/component-style/TitleSelector.vue
  frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue
  frontend/src/views/chart/components/component-style/XAxisSelector.vue
  frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelector.vue
  frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue
  frontend/src/views/chart/components/component-style/YAxisSelector.vue
  frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue
  frontend/src/views/chart/components/drag-item/ChartDragItem.vue
  frontend/src/views/chart/components/drag-item/DimensionExtItem.vue
  frontend/src/views/chart/components/drag-item/DimensionItem.vue
  frontend/src/views/chart/components/drag-item/DrillItem.vue
  frontend/src/views/chart/components/drag-item/FilterItem.vue
  frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
  frontend/src/views/chart/components/drag-item/QuotaItem.vue
  frontend/src/views/chart/components/shape-attr/ColorSelector.vue
  frontend/src/views/chart/components/shape-attr/LabelSelector.vue
  frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue
  frontend/src/views/chart/components/shape-attr/SizeSelector.vue
  frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
  frontend/src/views/chart/components/shape-attr/TooltipSelector.vue
  frontend/src/views/chart/components/shape-attr/TooltipSelectorAntV.vue
Labels: 类型:新功能

#1789 refactor: 完善视图插件
  frontend/src/components/AsyncComponent/index.vue
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/system/plugin/PluginCom.vue
Labels: 类型:优化

#1793 feat: 气泡地图国际化
  frontend/src/components/canvas/custom-component/UserView.vue
Labels: 类型:新功能

#1796 feat: 过滤条件穿透到tab组件内部视图
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/store/index.js
  frontend/src/views/panel/filter/filterDialog.vue
Labels: 类型:新功能

#1797 refactor: 新增视图插件flyway
  backend/src/main/resources/db/migration/V32__1.8.sql
Labels: 类型:优化

#1798 fix: 气泡地图图标
  frontend/src/icons/svg/buddle-map.svg
Labels: 类型:bug

#1799 refactor: chromium下载太慢发布之前先屏蔽
  Dockerfile
Labels: 类型:优化

#1802 fix: 修复只修改仪表板名称后，移动端列表不显示仪表板问题
  backend/src/main/java/io/dataease/service/panel/PanelViewService.java
Labels: 类型:bug

#1807 feat: 视图组件支持设置背景图片
  backend/src/main/java/io/dataease/base/domain/SysBackgroundImage.java
  backend/src/main/java/io/dataease/base/domain/SysBackgroundImageExample.java
  backend/src/main/java/io/dataease/base/mapper/SysBackgroundImageMapper.java
  backend/src/main/java/io/dataease/base/mapper/SysBackgroundImageMapper.xml
  backend/src/main/resources/db/migration/V32__1.8.sql
Labels: 类型:新功能

#1811 refactor: 插件组件dom层级调整
  frontend/src/views/system/plugin/PluginCom.vue
Labels: 类型:优化

#1813 feat: 数据集api权限
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:新功能

#1814 feat: 仪表板api权限
  backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java
  backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
  backend/src/main/java/io/dataease/controller/panel/api/StoreApi.java
Labels: 类型:新功能

#1815 fix: 气泡地图放大无法显示
  frontend/src/components/canvas/custom-component/UserViewDialog.vue
Labels: 类型:bug

#1816 fix: tabs组件中的视图全屏预览错误
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/utils/conditionUtil.js
Labels: 类型:bug

#1817 fix: 时间动态组件鼠标悬浮自增长
  frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
  frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
Labels: 类型:bug

#1818 feat: 增加xpack包内部分api
  backend/src/main/java/io/dataease/config/Knife4jConfiguration.java
  backend/src/main/java/io/dataease/controller/IndexController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskLogController.java
  backend/src/main/java/io/dataease/plugins/server/ColumnPermissionsController.java
  backend/src/main/java/io/dataease/plugins/server/RowPermissionsController.java
  backend/src/main/java/io/dataease/plugins/server/SSOServer.java
  backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
  backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XDisplayServer.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/java/io/dataease/plugins/server/XLdapServer.java
  backend/src/main/java/io/dataease/plugins/server/XOidcServer.java
  backend/src/main/java/io/dataease/plugins/server/XUserKeysServer.java
  backend/src/main/java/io/dataease/plugins/server/view/PluginViewServer.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
Labels: 类型:新功能

#1819 fix: tabs初始化条件报错
  frontend/src/components/widget/DeWidget/DeTabs.vue
  frontend/src/utils/conditionUtil.js
Labels: 类型:bug

#1825 fix: 获取API数据源下表接口报错
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
Labels: 类型:bug

#1826 fix: 获取API数据源下表接口报错
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
Labels: 类型:bug

#1830 refactor: 重构基础镜像
  Dockerfile
Labels: 类型:优化

#1833 refactor: flyway修改拓展插件名称
  backend/src/main/resources/db/migration/V32__1.8.sql
Labels: 类型:优化

#1835 refactor: 数据集视图权限
  backend/src/main/java/io/dataease/controller/chart/ChartController.java
  backend/src/main/java/io/dataease/controller/chart/ChartGroupController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:优化

#1836 refactor: 数据集视图权限
  backend/src/main/java/io/dataease/controller/chart/ChartController.java
  backend/src/main/java/io/dataease/controller/chart/ChartGroupController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:优化

#1837 fix: tab新增失败
  frontend/src/utils/conditionUtil.js
Labels: 类型:bug

#1838 refactor: 视图权限
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  frontend/src/api/chart/chart.js
  frontend/src/api/panel/panel.js
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/common/DatasetChartDetail.vue
Labels: 类型:优化

#1839 refactor: 视图权限
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  frontend/src/api/chart/chart.js
  frontend/src/api/panel/panel.js
  frontend/src/components/canvas/custom-component/UserView.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/dataset/common/DatasetChartDetail.vue
Labels: 类型:优化

#1840 refactor: 删除无用接口
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  frontend/src/api/chart/chart.js
Labels: 类型:优化

#1843 refactor: 数据集视图权限
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/dataset/DatasetFunctionController.java
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
Labels: 类型:优化

#1844 refactor: 数据集视图权限
  backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  backend/src/main/java/io/dataease/controller/dataset/DatasetFunctionController.java
  backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
Labels: 类型:优化

#1846 fix: 公共链接跳转无法打开目标仪表板
  backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelLinkJumpMapper.xml
Labels: 类型:bug

#1847 fix: 使用未同步数据集创建视图权限问题
  frontend/src/views/chart/view/TableSelector.vue
Labels: 类型:bug
