Repository dataease/dataease, pull requests merged in 2023-08, with the labels that each got.

#5807 fix(视图):修复使用模版创建的仪表板，仪表板视图的创建人用的模版中视图的创建人信息的问题
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#5810 fix: 初始化demo数据源异常
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
Labels: 类型:bug

#5811 fix(仪表板): 修复仪表板空属性联动时被联动视图出现报错问题
  backend/src/main/java/io/dataease/provider/query/SQLUtils.java
Labels: 类型:bug

#5812 refactor: 计算字段表达式与视图中使用的不匹配则标记红色
  frontend/src/views/chart/components/dragItem/utils.js
Labels: 类型:优化

#5813 refactor: 字段管理修改名称、维度指标时不进行语法校验
  backend/src/main/java/io/dataease/controller/chart/ChartViewFieldController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  frontend/src/views/chart/view/ChartFieldEdit.vue
  frontend/src/views/dataset/data/FieldEdit.vue
Labels: 类型:优化

#5814 feat(仪表板): 仪表板复用时支持选择适应当前主题和保持源样式 #5703
  frontend/src/components/canvas/store/copy.js
  frontend/src/store/index.js
  frontend/src/views/panel/edit/index.vue
Labels: 类型:新功能

#5815 fix: 修复日期过滤不包含起始时间的问题
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug

#5817 Pr@dev st fix
  frontend/src/utils/request.js
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#5818 fix(仪表板): 修复辅助网格设计开关显示可能与主题不同步问题 #5665
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#5819 fix(视图): 修复计算字段弹框热键冲突问题 #5501
  frontend/src/components/canvas/utils/shortcutKey.js
Labels: 类型:bug

#5828 refactor: 字段枚举值限制上限1000条
  backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:优化

#5854 fix: 修复表名错误
  backend/src/main/resources/db/migration/V57__1.18-table-desc-update.sql
Labels: 类型:bug

#5887 feat(视图-仪表盘): 刻度标签支持隐藏
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/gauge/gauge.js
  frontend/src/views/chart/chart/gauge/gauge_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
  frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:新功能

#5895 refactor(仪表板): 当源视图多个个字段匹配目标视图一个字段的时，默认仅保留当前点击的维度值匹配 #5769
  frontend/src/store/index.js
Labels: 类型:优化

#5898 fix(仪表板): 修复因下钻导致联动触发菜单位置不准确的问题 #5768
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/store/index.js
Labels: 类型:bug

#5899 fix(仪表板): 修复通过静态文件获取接口可以夸目录访问其他文件问题 #5864
  backend/src/main/java/io/dataease/commons/utils/StaticResourceUtils.java
Labels: 类型:bug

#5900 refactor(仪表板): 外部参数配置时，对于某一参数下已经配置的视图，添加参数联动字段选择视图时不重复出现 #5697
  frontend/src/views/panel/outerParamsSet/index.vue
Labels: 类型:优化

#5907 fix: 轴值必须大于数据
  frontend/src/views/chart/chart/common/common_antv.js
Labels: 类型:bug

#5941 feat: 词云图字体大小区间调整
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/chart/wordCloud/word_cloud.js
  frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:新功能

#5945 feat: 词云图字间距调整
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/chart/wordCloud/word_cloud.js
  frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:新功能
