Repository dataease/dataease, pull requests merged in 2023-02, with the labels that each got.

#4434 refactor(数据集): 非直连数据集修改字段前需完成数据同步
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
Labels: 类型:优化

#4435 refactor(数据集): 非直连数据集修改字段前需完成数据同步
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
Labels: 类型:优化

#4436 fix(应用): 修复应用更新名称缩略图未显示问题
  backend/src/main/java/io/dataease/controller/panel/PanelAppTemplateController.java
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
Labels: 类型:bug

#4440 fix: API 数据集状态显示
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
Labels: 类型:bug

#4446 refactor: 更新flyway
  backend/src/main/resources/db/migration/V49__1.18.2.sql
Labels: 类型:优化

#4448 feat: 修改API 数据集名称时，同步修改数据集里的表名
  backend/src/main/java/io/dataease/controller/request/datasource/ApiDefinition.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  frontend/src/views/system/datasource/DsConfiguration.vue
Labels: 类型:新功能

#4455 refactor: 更新kettle依赖仓库地址
  backend/pom.xml
Labels: 类型:优化

#4457 fix(登录): 退出登录后token依然可用(jwt通病)
  backend/src/main/java/io/dataease/auth/config/F2CRealm.java
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/auth/util/JWTUtils.java
  backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java
  backend/src/main/resources/ehcache/ehcache.xml
Labels: 类型:bug

#4460 fix: 解析API数据出错
  backend/src/main/java/io/dataease/provider/datasource/ApiProvider.java
Labels: 类型:bug

#4481 fix(登录): 退出后重新登录路由到历史页面
  frontend/src/layout/components/Topbar.vue
  frontend/src/permission.js
Labels: 类型:bug

#4483 fix(血缘关系): 修复血缘关系模糊搜索后点击文件夹模糊搜索字段消失
  frontend/src/views/system/relationship/index.vue
Labels: 类型:bug

#4485 refactor: 优化仪表板数据集菜单操作逻辑，防止菜单量大时可能造成的卡顿
  backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.java
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
  backend/src/main/java/io/dataease/ext/ExtVAuthModelMapper.java
  backend/src/main/java/io/dataease/ext/ExtVAuthModelMapper.xml
  backend/src/main/java/io/dataease/service/authModel/VAuthModelService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/components/canvas/utils/utils.js
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/group/CreatDsGroup.vue
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/dataset/group/GroupMoveSelector.vue
  frontend/src/views/panel/list/PanelList.vue
  frontend/src/views/panel/list/editPanel/index.vue
Labels: 类型:优化

#4488 refactor(视图): 分页表格导出时支持导出全量数据
  backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/components/canvas/customComponent/UserViewDialog.vue
  frontend/src/store/index.js
Labels: 类型:优化

#4490 fix(仪表板): 表格明细导出去掉底部无用翻页组件
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#4497 refactor(数据集): 数据集导出权限由管理权限控制
  frontend/src/views/dataset/data/ViewTable.vue
Labels: 类型:优化

#4499 perf(登录): 及时删除废弃的token缓存
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
Labels: 类型:优化

#4505 refactor: 增加权限管理api文档
  backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
Labels: 类型:优化

#4508 refactor: Api文档整理
  backend/src/main/java/io/dataease/auth/api/AuthApi.java
  backend/src/main/java/io/dataease/auth/api/DynamicMenuApi.java
  backend/src/main/java/io/dataease/config/Knife4jConfiguration.java
  backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
Labels: 类型:优化

#4509 fix(视图): 修复doris中使用case语法报错
  backend/src/main/resources/sql/sqlTemplate.stg
Labels: 类型:bug

#4510 fix(登录): 刷新token导致退出登录
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
  backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java
  backend/src/main/resources/ehcache/ehcache.xml
  frontend/src/utils/request.js
Labels: 类型:bug

#4511 refactor: Api文档整理
  backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
Labels: 类型:优化

#4516 fix(登录): 刷新token导致用户频繁掉线
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
Labels: 类型:bug

#4520 fix(视图): 修复分页明细表，字段设置跳转链接，只有第一页生效的问题 #4494
  frontend/src/views/chart/components/ChartComponentS2.vue
Labels: 类型:bug

#4523 feat: 根据dataease.properties配置里的mysql链接信息来更新demo数据源的配置信息
  backend/src/main/java/io/dataease/listener/DataSourceInitStartListener.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
Labels: 类型:新功能

#4527 feat: 升级版本号到1.18.3
  backend/pom.xml
  backend/src/main/resources/db/migration/V50__1.18.3.sql
  frontend/package.json
  frontend/pom.xml
  mobile/pom.xml
  pom.xml
Labels: 类型:新功能

#4542 fix: 修复部分部分数据集新建缓存没有及时刷新的问题
  backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/dataset/add/AddUnion.vue
Labels: 类型:bug

#4543 fix(仪表板): 修复切换主题色过滤组件表头位置也变化的问题
  frontend/src/components/canvas/utils/style.js
  frontend/src/components/widget/deWidget/TitlePosition.vue
Labels: 类型:bug

#4549 refactor(仪表板): 调整文本组件字体大小范围
  frontend/src/components/canvas/components/TextAttr.vue
Labels: 类型:优化

#4559 fix(i18n): i18n
  backend/src/main/java/io/dataease/controller/panel/PanelPdfTemplateController.java
  backend/src/main/resources/db/migration/V50__1.18.3.sql
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/utils/StringUtils.js
  frontend/src/views/background/index.vue
  frontend/src/views/panel/export/PDFPreExport.vue
Labels: 类型:bug

#4566 feat(登录): 移动端钉钉工作台免登进入DE
  backend/src/main/java/io/dataease/auth/config/F2CRealm.java
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/auth/util/JWTUtils.java
  backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java
  frontend/src/permission.js
  mobile/src/common/utils.js
  mobile/src/pages.json
  mobile/src/pages/login/index.vue
Labels: 类型:新功能

#4572 perf(登录): 移动端钉钉工作台免登使用DE
  backend/src/main/resources/ehcache/ehcache.xml
  mobile/src/locale/zh-Hans.json
  mobile/src/locale/zh-Hant.json
  mobile/src/pages.json
  mobile/src/pages/login/index.vue
Labels: 类型:优化

#4575 perf(用户管理): 编辑页面保存时增加页面遮罩
  frontend/src/api/system/user.js
  frontend/src/views/system/user/UserEditer.vue
Labels: 类型:优化

#4576 fix: 抽取 oralce date类型数据格式化
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
Labels: 类型:bug

#4592 fix(仪表板): 修复部分明细预览无法滚动查看的问题
  frontend/src/components/canvas/customComponent/UserViewDialog.vue
Labels: 类型:bug

#4593 fix(视图): 修复明细表查询分页失效的问题
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#4594 fix(移动端): 手动删除缓存解决未绑定也能从工作台进入DE
  frontend/src/permission.js
Labels: 类型:bug

#4596 refactor: 仪表板防范XSS攻击 #4585
  frontend/package.json
  frontend/src/components/canvas/customComponent/DeRichText.vue
  frontend/src/components/canvas/customComponent/DeRichTextView.vue
  frontend/src/components/canvas/customComponent/VText.vue
  frontend/src/main.js
Labels: 类型:优化

#4597 fix(路由): 无法路由到资源
  frontend/src/permission.js
Labels: 类型:bug

#4600 fix(仪表版): 修复编辑状态下Tab组件内部仪表板板切换时可能存在的错位问题
  frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug

#4601 perf(token): 禁用每分钟自动刷新token机制
  backend/src/main/java/io/dataease/auth/filter/F2CDocFilter.java
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
  backend/src/main/java/io/dataease/auth/util/JWTUtils.java
  backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java
  backend/src/main/java/io/dataease/listener/ApplicationCloseEventListener.java
  backend/src/main/java/io/dataease/listener/util/CacheUtils.java
  backend/src/main/resources/ehcache/ehcache.xml
Labels: 类型:优化

#4608 fix(分组柱状图-下钻): 修复分组柱状图子维度下钻问题
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#4617 fix(视图): 修复部分表格全量导出时报错问题
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#4645 fix: 同步mysql数据出错
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug

#4646 fix(仪表板):修复部分富文本组件样式无法保存问题
  frontend/src/components/canvas/customComponent/DeRichText.vue
  frontend/src/components/canvas/customComponent/DeRichTextView.vue
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:bug

#4658 fix(视图): 修复自定义排序第二次进入直接确认无效的问题
  frontend/src/views/chart/components/compare/CustomSortEdit.vue
Labels: 类型:bug

#4660 fix(应用): 修复仪表板应用导出时，携带单独数据集定义的组件导入新环境组件会报错问题 #4620
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#4661 fix(仪表板): 优化新建仪表板目录提示文案 #4619
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#4663 refactor: 升级版本号
  backend/src/main/resources/db/migration/V51__1.18.4.sql
Labels: 类型:优化
