Repository dataease/dataease, pull requests merged in 2023-01, with the labels that each got.

#4255 fix(应用): 复用历史数据源记录名称，数据源删除时在应用日志中也进行显示
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#4256 refactor(应用): 复用数据源的应用记录允许编辑
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/views/system/datasource/DsFormContent.vue
Labels: 类型:优化

#4257 refactor: 优化仪表板主题样式
  backend/src/main/java/io/dataease/service/panel/PanelGroupExtendDataService.java
  backend/src/main/java/io/dataease/service/panel/PanelSubjectService.java
  backend/src/main/resources/db/migration/V46__1.18.sql
  backend/src/main/resources/db/migration/V47__1.18-panel-subject-add.sql
Labels: 类型:优化

#4262 fix(血源关系): 删除数据源和数据集时如果没有查看血源关系的权限则不提示跳转
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/system/datasource/DsTree.vue
  frontend/src/views/system/relationship/index.vue
Labels: 类型:bug

#4264 fix(api): 恢复错误提交
  backend/src/main/java/io/dataease/auth/filter/F2CDocFilter.java
Labels: 类型:bug

#4265 fix(定时报告): cron表达式错误文案
  backend/src/main/java/io/dataease/job/sechedule/ScheduleManager.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/resources/i18n/messages_en_US.properties
  backend/src/main/resources/i18n/messages_zh_CN.properties
  backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#4266 refactor: 取消发布的仪表板在收藏里隐藏菜单
  backend/src/main/resources/db/migration/V47__1.18-panel-subject-add.sql
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:优化

#4269 refactor: 更新flyway
  backend/src/main/resources/db/migration/V46__1.18.sql
Labels: 类型:优化

#4274 fix(仪表板): 修复外部过滤后切换Tab可能导致Tab内表格不显示数据问题
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug

#4277 Pr@dev@fixds
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
  frontend/src/views/dataset/data/UpdateInfo.vue
Labels: 类型:bug

#4281 refactor(仪表板): 优化矩阵移动算法减少组件拖拽时导致的卡顿现象
  frontend/src/components/canvas/components/editor/DeEditor.vue
  frontend/src/components/deDrag/index.vue
Labels: 类型:优化

#4288 fix(仪表板): 在第三方平台内禁止使用新Tab预览以及全屏预览功能
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#4291 fix(视图): 优化视图翻页提示防止
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#4293 fix(tab): 点击tab内部视图会误触resize事件
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/views/chart/components/map/MapController.vue
Labels: 类型:bug

#4294 fix(过滤器): 代码冲突导致初始状态不显示参数列表
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:bug

#4297 fix(地图): 切换数据集后标记字段错误提示优化
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/components/functionStyle/MapMarkSelector.vue
Labels: 类型:bug

#4298 refactor(仪表板): 调整悬浮组件位置调整最大位置范围，优化悬浮组件复制逻辑防止复制位置差距太大问题
  frontend/src/components/canvas/store/copy.js
  frontend/src/views/chart/view/PositionAdjust.vue
Labels: 类型:优化

#4299 fix(地图): 数据为0在提示中无法展示出来
  frontend/src/views/chart/chart/map/map.js
Labels: 类型:bug

#4301 fix(ldap): 测试连接以表单信息为准
  backend/src/main/java/io/dataease/plugins/server/XLdapServer.java
Labels: 类型:bug

#4307 fix(视图): 修复当指标或维度过多时，使用富文本视图选择参数，参数超过一屏显示不全问题 #4300
  frontend/src/components/canvas/components/editor/FieldsList.vue
Labels: 类型:bug

#4308 fix(公共连接): 移动端无法返回上一级
  frontend/src/components/canvas/components/editor/CanvasOptBar.vue
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#4309 refactor: 升级版本号
  backend/pom.xml
  frontend/package.json
  frontend/pom.xml
  mobile/pom.xml
  pom.xml
Labels: 类型:优化

#4314 feat(插件管理): 升级1.18.1相关插件sql
  backend/src/main/resources/db/migration/V48__1.18.1.sql
Labels: 类型:新功能

#4316 feat(用户管理): 第三方平台用户禁止重置密码
  frontend/src/views/system/user/index.vue
Labels: 类型:新功能

#4317 feat(视图): 辅助线支持字体大小设置
  frontend/src/views/chart/chart/common/common.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/components/senior/AssistLine.vue
  frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue
Labels: 类型:新功能

#4319 feat: 数据集新建页面数据源排序 数据集详情展示UI调整 数据集展示的表与字段支持筛选框搜索
  frontend/package.json
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/dataset/add/util.js
  frontend/src/views/dataset/common/DatasetDetail.vue
  frontend/src/views/system/datasource/DsFormContent.vue
Labels: 类型:新功能

#4321 feat(过滤器): 控制范围显示优化
  frontend/src/views/panel/filter/FilterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterControl.vue
Labels: 类型:新功能

#4323 feat(视图): Echarts 视图点击激活被选择后才能进行滚轮缩放操作，非激活状态禁止滚轮缩放 #3031
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:新功能

#4326 fix(插件管理): 卸载按钮灰置后依然可以卸载
  frontend/src/views/system/plugin/index.vue
Labels: 类型:bug

#4327 fix: 修复默认双碳及能源情况概览内置仪表板部分图例显示不正确问题
  backend/src/main/resources/db/migration/V41__1.15-offical-panel-update.sql
Labels: 类型:bug

#4332 fix(视图): 修复导出视图明细当有空值时报错的问题
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#4336 feat(插件管理): 优化插件版本flyway
  backend/src/main/resources/db/migration/V48__1.18.1.sql
Labels: 类型:新功能

#4338 Merge branch 'dev' into pr@dev@feat_relation_tree_select
  frontend/src/views/dataset/group/Group.vue
  frontend/src/views/system/datasource/DsTree.vue
  frontend/src/views/system/relationship/index.vue
Labels: 类型:新功能

#4339 feat: 升级版本号到1.18.2
  backend/pom.xml
  backend/src/main/resources/db/migration/V49__1.18.2.sql
  frontend/package.json
  frontend/pom.xml
  mobile/pom.xml
  pom.xml
Labels: 类型:新功能

#4340 fix(仪表板): 修复仪表板制作页面使用撤销操作后视图的操作列表消失问题 #4335
  frontend/src/components/canvas/components/editor/EditBar.vue
Labels: 类型:bug

#4342 fix(仪表板): 修复仪表板制作页面使用撤销操作后视图的操作列表消失问题 #4335
  frontend/src/components/canvas/components/editor/EditBar.vue
Labels: 类型:bug

#4343 feat(血源关系): 仪表板名称选项增加默认仪表板
  frontend/src/views/system/relationship/index.vue
Labels: 类型:新功能

#4344 refactor(视图): 气泡地图支持点击激活后滚轮缩放
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:优化

#4346 feat(视图): 视图明细导出增加权限控制
  backend/src/main/resources/db/migration/V49__1.18.2.sql
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:新功能

#4349 feat(视图): 辅助线支持字体大小设置
  backend/src/main/java/io/dataease/dto/chart/ChartSeniorAssistDTO.java
Labels: 类型:新功能

#4352 refactor(视图): Echarts矩形树图支持获取焦点再滚动
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:优化

#4353 feat(应用): 应用复用数据源时增加数据源有效标识
  frontend/src/views/system/datasource/DsFormContent.vue
Labels: 类型:新功能

#4354 feat(视图): 视图明细导出增加权限控制
  backend/src/main/resources/db/migration/V49__1.18.2.sql
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:新功能

#4359 feat(视图): 指标卡、文本卡支持调整位置
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/normal/LabelNormal.vue
  frontend/src/views/chart/components/normal/LabelNormalText.vue
  frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
  frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:新功能

#4360 fix(血缘关-数据源列表): 数据源列表按照类型和名称升序排序
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  frontend/src/views/system/relationship/index.vue
Labels: 类型:bug

#4363 fix(仪表板): 修复模板状态的仪表板下拉组件编辑可能报错问题
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#4365 fix(数据源列表): 数据源列表按照类型名称和数据源名称升序排序，忽略大小写
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
Labels: 类型:bug

#4367 feat(仪表板): 前端增加导出分页功能
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/components/canvas/components/editor/DeEditor.vue
  frontend/src/components/canvas/components/editor/PageLineEditor.vue
  frontend/src/components/canvas/utils/utils.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/panel.js
Labels: 类型:新功能

#4373 fix(过滤器): 下拉过滤器切换枚举字段后没有清空默认值
  frontend/src/components/widget/deWidget/DeSelect.vue
  frontend/src/components/widget/deWidget/DeSelectGrid.vue
Labels: 类型:bug

#4375 fix(血缘关系): 下拉树组件高度调整
  frontend/src/views/system/relationship/index.vue
Labels: 类型:bug

#4380 fix(移动端): 修复移动端点击视图缺少按键问题
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
Labels: 类型:bug

#4382 fix(仪表板): 修复仪表板编辑界面点击全屏后返回快捷键冲突
  frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#4383 feat(视图): 插件视图增加行权限机制
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
Labels: 类型:新功能

#4385 refactor(视图): 控制视图导出图片权限跟随仪表板导出权限
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/utils/style.js
Labels: 类型:优化

#4387 refactor(视图): 控制视图导出图片权限跟随仪表板导出权限
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:优化

#4388 fix(仪表板): 分页线缺失图标
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/icons/svg/page-line.svg
Labels: 类型:bug

#4389 fix(血缘关系): 修复默认仪表板查询结果为空
  frontend/src/views/system/relationship/consanguinity.vue
  frontend/src/views/system/relationship/index.vue
Labels: 类型:bug

#4392 refactor: 更新默认浅色主题
  backend/src/main/resources/db/migration/V49__1.18.2.sql
Labels: 类型:优化

#4394 refactor(仪表板): 按钮组件禁止复制和移入Tab内
  frontend/src/components/canvas/utils/shortcutKey.js
  frontend/src/components/deDrag/index.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#4397 feat(仪表板): api导出pdf增加设置页脚选项
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
Labels: 类型:新功能

#4401 fix(过滤器): 过滤器与查询按钮匹配问题-issues-4379
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#4403 refactor: 更换首页快速入门链接
  frontend/src/views/wizard/index.vue
Labels: 类型:优化

#4404 feat(企业微信): 支持企业微信内应用自动登录
  backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
  frontend/src/api/user.js
  frontend/src/views/DeAutoLogin.vue
Labels: 类型:新功能

#4408 fix(视图): 地图范围相互影响
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#4411 refactor(仪表板): 优化仪表板矩阵模式下的拖拽可能出现的松开手柄后大小再次变化，位置未置顶问题
  frontend/src/components/canvas/components/editor/DeEditor.vue
  frontend/src/components/deDrag/index.vue
Labels: 类型:优化

#4412 fix: 解析pg sql出错
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#4414 refactor(仪表板): 从模板新建的过滤组件在没有重新关联数据集前忽略权限检查,防止报无权限问题
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  frontend/src/api/dataset/dataset.js
Labels: 类型:优化

#4416 fix(仪表板): 数字区间过滤器空默认值无法替换编辑时填写的值
  frontend/src/components/widget/deWidget/DeNumberRange.vue
Labels: 类型:bug

#4422 refactor(仪表板): 调整组件最小长宽
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/components/deDrag/index.vue
Labels: 类型:优化

#4424 perf(仪表板): 隐藏pdf导出分页按钮
  frontend/src/components/canvas/components/Toolbar.vue
Labels: 类型:优化

#4426 fix: 获取 API 数据结构不校验jsonpath
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/datasource/DsConfiguration.vue
Labels: 类型:bug

#4428 fix(仪表板): 修复查询按钮不能控制Tab组件内部视图问题
  frontend/src/components/canvas/DeCanvas.vue
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/editor/DeEditor.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/dataease/DeOutWidget.vue
  frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug
