Repository dataease/dataease, pull requests merged in 2023-04, with the labels that each got.

#4954 fix(视图-符号地图): 修复符号地图初始化时设置主题不生效
  frontend/src/components/canvas/utils/style.js
Labels: 类型:bug

#4957 fix(视图-编辑): 修复流向地图的属性出现在其他视图中
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shapeAttr/ColorSelector.vue
  frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:bug

#4959 fix(视图-流向地图): 流向地图初始化使用默认主题，无数据可调节倾角和主题
  frontend/src/views/chart/chart/map/map_antv.js
Labels: 类型:bug

#4962 fix(视图-流向地图): 修复动画属性和渐变属性无效
  frontend/src/views/chart/chart/map/map_antv.js
  frontend/src/views/chart/components/shapeAttr/ColorSelector.vue
Labels: 类型:bug

#4965 fix(仪表板): 选项卡组件tab页过多时，轮播标题被遮挡，看不见部分标题了 #4956
  frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug

#4966 fix(视图-流向地图): 修复新建的视图颜色属性不生效
  frontend/src/components/canvas/utils/style.js
  frontend/src/components/canvas/utils/utils.js
  frontend/src/views/chart/chart/map/map_antv.js
  frontend/src/views/chart/components/shapeAttr/MapSelectorAntV.vue
Labels: 类型:bug

#4967 feat(视图): Doris,StarRocks同环比支持周，季度
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  frontend/src/views/chart/components/dragItem/DimensionExtItem.vue
  frontend/src/views/chart/components/dragItem/DimensionItem.vue
Labels: 类型:新功能

#4975 refactor(视图-流向地图): 修改部分默认属性
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/map/map_antv.js
  frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:优化

#4989 fix(数据集): 修复校验sql卡顿导致数据集重名
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#5017 feat(过滤器): 动态时间过滤器跟随仪表板刷新
  frontend/src/components/widget/deWidget/DeDate.vue
Labels: 类型:新功能

#5019 fix(公共连接): 导出excel没有遮罩没有按钮失效
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/components/canvas/customComponent/UserViewDialog.vue
Labels: 类型:bug

#5020 fix: oracle时间过滤组件提示异常
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
Labels: 类型:bug

#5021 refactor(视图插件): 图表类型选择页面图标对齐
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/icons/svg/buddle-map.svg
  frontend/src/icons/svg/buddle-map_mini.svg
  frontend/src/icons/svg/map.svg
  frontend/src/icons/svg/map_mini.svg
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/view/ChartType.vue
Labels: 类型:优化

#5022 fix(用户管理): 飞书同步的用户手机号无法通过DE表单验证
  frontend/src/views/system/user/UserEditer.vue
Labels: 类型:bug

#5024 fix(定时报告): 导出视图名称包含"/"报错
  backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
Labels: 类型:bug

#5025 fix(定时报告): 使用模版导出视图数据报错
  backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
Labels: 类型:bug

#5064 feat(视图-对称条形图): 新增对称条形图
  backend/src/main/java/io/dataease/dto/chart/AxisChartDataAntVDTO.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
  backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
  frontend/src/components/canvas/components/editor/SettingMenu.vue
  frontend/src/icons/svg/bidirectional-bar.svg
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/common/common_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/ChartComponentG2.vue
  frontend/src/views/chart/components/componentStyle/XAxisSelectorAntV.vue
  frontend/src/views/chart/components/componentStyle/YAxisSelectorAntV.vue
  frontend/src/views/chart/components/senior/FunctionCfg.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:新功能

#5113 fix: 识别 mysql BIGINT UNSIGNED
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug
