Repository dataease/dataease, pull requests merged in 2023-11, with the labels that each got.

#6487 fix: 修复定时同步数据集日期范围过滤不包含左侧的问题 #6423
  core/backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
Labels: 类型:bug

#6493 refactor(仪表板): 优化仪表板快捷键相应区域，避免弹框中的快捷操作影响仪表板
  core/frontend/src/components/canvas/customComponent/Picture.vue
  core/frontend/src/components/canvas/utils/shortcutKey.js
Labels: 类型:优化

#6494 perf: 公共链接跳转返回上一级
  core/backend/src/main/java/io/dataease/controller/IndexController.java
  core/frontend/public/link.html
  core/frontend/src/components/canvas/components/editor/CanvasOptBar.vue
  core/frontend/src/components/canvas/components/editor/Preview.vue
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/views/link/view/index.vue
Labels: 类型:优化

#6495 perf: echarts地图图层控制弹窗放到左侧
  core/frontend/src/views/chart/components/map/MapLayerController.vue
Labels: 类型:优化

#6500 refactor(仪表板): 修复部分图片不显示问题
  core/frontend/src/components/canvas/customComponent/Picture.vue
Labels: 类型:优化

#6510 feat(仪表板): 增加组件内部样式是否自适应仪表板缩放功能 #5793
  core/frontend/src/components/canvas/components/Toolbar.vue
  core/frontend/src/components/canvas/components/editor/DeEditor.vue
  core/frontend/src/components/canvas/components/editor/Preview.vue
  core/frontend/src/components/canvas/utils/utils.js
  core/frontend/src/icons/svg/icon_auto-adaptor.svg
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/panel/panel.js
Labels: 类型:新功能

#6512 feat(仪表板): 增加组件内部样式是否自适应仪表板缩放功能 #5793
  core/frontend/src/components/canvas/components/Toolbar.vue
  core/frontend/src/components/canvas/components/editor/DeEditor.vue
  core/frontend/src/components/canvas/components/editor/Preview.vue
  core/frontend/src/components/canvas/utils/utils.js
  core/frontend/src/styles/deicon/demo_index.html
  core/frontend/src/styles/deicon/iconfont.css
  core/frontend/src/styles/deicon/iconfont.js
  core/frontend/src/styles/deicon/iconfont.json
  core/frontend/src/styles/deicon/iconfont.ttf
  core/frontend/src/styles/deicon/iconfont.woff
  core/frontend/src/styles/deicon/iconfont.woff2
Labels: 类型:新功能

#6514 fix(仪表板): 修复不支持SVG矢量图上传问题 #5233 #5013
  core/backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/background/BackgroundOverall.vue
  core/frontend/src/views/panel/subjectSetting/panelStyle/BackgroundSelector.vue
  core/frontend/src/views/panel/subjectSetting/panelStyle/MobileBackgroundSelector.vue
Labels: 类型:bug

#6516 fix(仪表板): 修复仪表板目录移动到最顶级需要刷新才显示问题
  core/frontend/src/components/canvas/utils/utils.js
Labels: 类型:bug

#6518 fix: doris直连数字下拉排序
  core/backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug

#6523 fix: 符号地图报错
  core/backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
Labels: 类型:bug

#6536 feat: 移动端时间组件
  core/frontend/package.json
  core/frontend/public/mobile.html
  core/frontend/src/components/canvas/components/Toolbar.vue
  core/frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  core/frontend/src/components/canvas/components/editor/MobileCheckBar.vue
  core/frontend/src/components/dataease/DeOutWidget.vue
  core/frontend/src/components/widget/deWidget/DeDate.vue
  core/frontend/src/components/widget/deWidget/serviceNameFn.js
  core/frontend/src/mobile/App.vue
  core/frontend/src/mobile/main.js
  core/frontend/src/router/mobile.js
  core/frontend/src/store/index.js
  core/frontend/src/views/mobile/index.vue
  core/frontend/src/views/panel/edit/ComponentWait.vue
  core/frontend/src/views/panel/edit/index.vue
  core/frontend/src/views/panel/subjectSetting/panelStyle/MobileBackgroundSelector.vue
  core/frontend/vue.config.js
Labels: 类型:新功能

#6538 fix: 修复echarts横向柱状图排序颠倒的问题 #6528
  core/backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#6542 feat: mobile页面白名单
  core/backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
Labels: 类型:新功能

#6561 fix: 修复符号地图主题修改无效
  extensions/dataease-extensions-view/view-symbolmap/view-symbolmap-frontend/src/views/antv/symbolmap/index.vue
Labels: 类型:bug

#6562 fix: 禁用水波图/仪表盘阈值回车事件
  core/frontend/src/views/chart/components/senior/Threshold.vue
Labels: 类型:bug

#6568 refactor: 修改healthcheck方法
  installer/dataease/dectl
  installer/dataease/install.sh
Labels: 类型:优化

#6575 fix: 符号地图点击后跟随鼠标移动#5901
  extensions/dataease-extensions-view/view-symbolmap/view-symbolmap-frontend/src/views/antv/symbolmap/index.vue
Labels: 类型:bug

#6587 perf: 文本下拉选择首项
  core/frontend/src/components/widget/deWidget/DeSelect.vue
Labels: 类型:优化

#6590 perf: 文本下拉选择首项样式
  core/frontend/src/components/elVisualSelect/index.vue
  core/frontend/src/components/widget/deWidget/DeSelect.vue
Labels: 类型:优化

#6594 fix: 地图高级配置最后一页显示undefined
  core/frontend/src/views/chart/components/senior/MapMapping.vue
Labels: 类型:bug

#6610 feat: Echarts 表格联动跳转
  core/frontend/src/components/canvas/components/editor/SettingMenu.vue
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:新功能

#6614 feat: 下拉过滤器设置为必填选项
  core/frontend/src/components/canvas/components/editor/DeEditor.vue
  core/frontend/src/components/canvas/components/editor/Preview.vue
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/components/dataease/DeOutWidget.vue
  core/frontend/src/components/widget/bean/Condition.js
  core/frontend/src/components/widget/deWidget/DeSelect.vue
  core/frontend/src/store/index.js
  core/frontend/src/views/panel/filter/FilterDialog.vue
  core/frontend/src/views/panel/filter/filterMain/FilterFoot.vue
  core/frontend/src/views/panel/filter/filterMain/FilterHead.vue
Labels: 类型:新功能

#6619 feat: 过滤器设置为必填选项
  core/frontend/src/components/widget/deWidget/DeDate.vue
  core/frontend/src/components/widget/deWidget/DeInputSearch.vue
  core/frontend/src/components/widget/deWidget/DeNumberRange.vue
  core/frontend/src/components/widget/deWidget/DeSelectGrid.vue
  core/frontend/src/components/widget/deWidget/DeSelectTree.vue
  core/frontend/src/views/panel/filter/FilterDialog.vue
  core/frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
  core/frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
Labels: 类型:新功能

#6620 fix: 角色列表普通员工禁止操作提示文案#6593
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
Labels: 类型:bug

#6621 fix: echarts地图高级配置地名映射会影响地图颜色#6192
  core/frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#6622 feat: 表格支持隐藏表头#5873
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/chart/chart/chart.js
  core/frontend/src/views/chart/chart/table/table-info.js
  core/frontend/src/views/chart/chart/util.js
  core/frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
  core/frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:新功能

#6636 fix: 图表编辑异常
  core/frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#6655 perf: 个人信息接口隐藏密码
  core/backend/src/main/java/io/dataease/controller/sys/SysUserController.java
Labels: 类型:优化

#6664 feat: 雷达图值轴自定义最大值最小值
  core/frontend/src/views/chart/chart/chart.js
  core/frontend/src/views/chart/chart/radar/radar_antv.js
  core/frontend/src/views/chart/chart/util.js
  core/frontend/src/views/chart/components/componentStyle/SplitSelectorAntV.vue
  core/frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:新功能

#6667 fix: 下拉过滤器选择排序字段后切换选项字段下拉框消失
  core/frontend/src/components/widget/deWidget/DeSelect.vue
Labels: 类型:bug

#6678 perf: 下拉过滤器使用后台模糊搜索
  core/backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
  core/backend/src/main/java/io/dataease/controller/request/dataset/MultFieldValuesRequest.java
  core/backend/src/main/java/io/dataease/service/dataset/DataSetFieldService.java
  core/backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  core/frontend/src/components/elVisualSelect/index.vue
  core/frontend/src/components/widget/deWidget/DeSelect.vue
Labels: 类型:优化

#6679 fix: 日志api未校验对应菜单权限
  core/backend/src/main/java/io/dataease/controller/sys/SysLogController.java
Labels: 类型:bug

#6680 refactor(仪表板): 优化自定义颜色数据加载时机，改为需要配置时加载，防止初始化即加载导致请求时间过长 #6638
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/views/chart/components/shapeAttr/ColorSelector.vue
Labels: 类型:优化

#6681 feat: 指标卡支持空值处理和后缀 #5413 #5576
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/chart/chart/chart.js
  core/frontend/src/views/chart/chart/util.js
  core/frontend/src/views/chart/components/normal/LabelNormal.vue
  core/frontend/src/views/chart/components/senior/FunctionCfg.vue
  core/frontend/src/views/chart/components/shapeAttr/ColorSelector.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
  core/frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#6687 fix(仪表板): 修复通过仪表板样式中部分属性更新，tab组件中非当前页中组件未生效问题 #6644
  core/frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug

#6690 perf: doris数据源过滤器选项排序
  core/backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  core/backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:优化

#6693 perf: doris数据源下拉过滤器选项模糊搜索
  core/backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:优化

#6694 feat(仪表板): 仪表板外部参数支持匹配过滤组件 #5891
  core/frontend/src/icons/svg/filter.svg
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/store/index.js
  core/frontend/src/views/panel/outerParamsSet/index.vue
Labels: 类型:新功能

#6695 fix: 指标卡/文本卡字体在 mac 上不生效
  core/frontend/src/components/canvas/utils/style.js
  core/frontend/src/views/chart/components/normal/LabelNormal.vue
  core/frontend/src/views/chart/components/normal/LabelNormalText.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
Labels: 类型:bug

#6698 feat(仪表板): 仪表板外部参数支持匹配过滤组件,兼容多选范围组件 #5891
  core/frontend/src/store/index.js
  core/frontend/src/views/panel/outerParamsSet/index.vue
Labels: 类型:新功能

#6703 refactor(视图): 富文本视图点击编辑按钮文本区域进入编辑状态
  core/frontend/src/components/canvas/components/editor/EditBar.vue
  core/frontend/src/components/canvas/customComponent/DeRichTextView.vue
Labels: 类型:优化

#6704 feat: 维度自定义排序支持置顶和搜索#6288
  core/frontend/src/icons/svg/to-top.svg
  core/frontend/src/views/chart/components/compare/CustomSortEdit.vue
Labels: 类型:新功能

#6708 fix: echarts表格隐藏表头同时隐藏统计行
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#6709 fix: antv汇总表序号列斑马纹不生效
  core/frontend/src/views/chart/chart/table/table-info.js
Labels: 类型:bug

#6721 fix(仪表板): 修复部分外部参数添加按钮点击没反应问题
  core/frontend/src/views/panel/outerParamsSet/index.vue
Labels: 类型:bug

#6722 feat: echarts雷达图自定义最大值最小值。
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/chart/chart/radar/radar.js
  core/frontend/src/views/chart/chart/radar/radar_antv.js
  core/frontend/src/views/chart/chart/util.js
  core/frontend/src/views/chart/components/componentStyle/SplitSelector.vue
  core/frontend/src/views/chart/components/componentStyle/SplitSelectorAntV.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:新功能

#6730 fix: antv 提示偏移
  core/frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  core/frontend/src/components/canvas/customComponent/UserViewDialog.vue
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/chart/components/ChartComponentG2.vue
  core/frontend/src/views/chart/view/ChartStyle.vue
Labels: 类型:bug

#6742 fix: sqlserver 下拉组件有排序时筛选报错
  core/backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  core/backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  sdk/dataease-plugin-datasource/src/main/java/io/dataease/plugins/datasource/query/QueryProvider.java
Labels: 类型:bug

#6744 fix: 明细表分页由小变大时不显示数据
  core/frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#6788 fix: 修复将图表和过滤组件添加到选项卡内过滤组件的默认值筛选将不生效问题 #6777
  core/frontend/src/components/canvas/components/editor/EditBar.vue
  core/frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#6792 fix: 修复Tab页中的不同画布之间的过滤组件可能相互影响问题
  core/frontend/src/utils/conditionUtil.js
Labels: 类型:bug

#6793 fix: 优化编辑状态Tab加载方式改为实时加载，防止未加载视图对主题改变不响应问题 #6644
  core/frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug

#6799 fix: 直连presto数据源使用时间过滤组件报错 #6359
  extensions/dataease-extensions-datasource/presto/presto-backend/src/main/java/io/dataease/plugins/datasource/dm/query/PrestoQueryProvider.java
Labels: 类型:bug

#6803 fix: 修复移动端设计界面待选组件区域字体显示比例过大问题
  core/frontend/src/components/canvas/components/Toolbar.vue
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/views/panel/edit/ComponentWaitItem.vue
Labels: 类型:bug

#6826 feat: 维度/指标多选拖拽
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/chart/components/ChartComponentS2.vue
  core/frontend/src/views/chart/components/table/TableNormal.vue
  core/frontend/src/views/chart/view/ChartEdit.vue
  extensions/dataease-extensions-view/view-3dpie/view-3dpie-frontend/src/views/highcharts/3dpie/data.vue
  extensions/dataease-extensions-view/view-bubblemap/view-bubblemap-frontend/src/views/echarts/map/buddle/data.vue
  extensions/dataease-extensions-view/view-chartmix/view-chartmix-frontend/src/views/antv/chartmix/data.vue
  extensions/dataease-extensions-view/view-racebar/view-racebar-frontend/src/views/antv/racebar/data.vue
  extensions/dataease-extensions-view/view-sankey/view-sankey-frontend/src/views/antv/sankey/data.vue
  extensions/dataease-extensions-view/view-symbolmap/view-symbolmap-frontend/src/views/antv/symbolmap/data.vue
Labels: 类型:新功能

#6838 fix(视图-明细表): 修复非直连模式下明细表分页由小变大不显示数据
  core/frontend/src/views/chart/components/ChartComponentS2.vue
  core/frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:bug

#6840 fix(视图-雷达图): 雷达图最小值取实际最小值
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/chart/chart/radar/radar.js
  core/frontend/src/views/chart/chart/radar/radar_antv.js
  core/frontend/src/views/chart/components/componentStyle/SplitSelector.vue
  core/frontend/src/views/chart/components/componentStyle/SplitSelectorAntV.vue
Labels: 类型:bug

#6869 perf(数据源): 模糊搜索以及1000条限制排序
  core/backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/api/ApiProvider.java
  core/backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  core/backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  extensions/dataease-extensions-datasource/dm/dm-backend/src/main/java/io/dataease/plugins/datasource/dm/query/DmQueryProvider.java
  extensions/dataease-extensions-datasource/kingbase/kingbase-backend/src/main/java/io/dataease/plugins/datasource/kingbase/query/KingbaseQueryProvider.java
  extensions/dataease-extensions-datasource/kylin/kylin-backend/src/main/java/io/dataease/plugins/datasource/kylin/query/KylinQueryProvider.java
  extensions/dataease-extensions-datasource/maxcompute/maxcompute-backend/src/main/java/io/dataease/plugins/datasource/dm/query/MaxcomputeQueryProvider.java
  extensions/dataease-extensions-datasource/mongo/mongo-backend/src/main/java/io/dataease/plugins/datasource/mongo/query/MongobiQueryProvider.java
  extensions/dataease-extensions-datasource/presto/presto-backend/src/main/java/io/dataease/plugins/datasource/dm/query/PrestoQueryProvider.java
  sdk/dataease-plugin-common/src/main/java/io/dataease/plugins/common/dto/sqlObj/SQLObj.java
  sdk/dataease-plugin-datasource/src/main/java/io/dataease/plugins/datasource/query/QueryProvider.java
Labels: 类型:优化

#6870 perf(过滤器): 过滤器弹窗搜索数据集错误
  core/frontend/src/views/panel/filter/FilterDialog.vue
Labels: 类型:优化

#6874 perf(过滤器): 树过滤器添加排序字段后会多出一级
  core/backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:优化

#6875 perf(过滤器): 树过滤器废弃限制1000条
  core/backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
Labels: 类型:优化

#6878 perf(过滤器): 树过滤器改变排序方式后默认值重置
  core/frontend/src/components/widget/deWidget/DeSelectTree.vue
Labels: 类型:优化

#6879 perf(过滤器): 树过滤器跨数据集多字段错误信息国际化
  core/backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
  core/backend/src/main/resources/i18n/messages_en_US.properties
  core/backend/src/main/resources/i18n/messages_zh_CN.properties
  core/backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:优化

#6881 perf: 使用默认密码登录提示但还可以切换路由
  core/frontend/src/layout/index.vue
Labels: 类型:优化

#6887 feat: 内置账号转uid接口
  core/backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  core/backend/src/main/java/io/dataease/controller/sys/request/TransAccountRequest.java
  core/backend/src/main/java/io/dataease/ext/ExtSysUserMapper.java
  core/backend/src/main/java/io/dataease/ext/ExtSysUserMapper.xml
  core/backend/src/main/java/io/dataease/service/sys/SysUserService.java
Labels: 类型:新功能

#6861 fix: 去掉数据库名
  core/backend/src/main/java/io/dataease/controller/datasource/DriverMgmController.java
  core/backend/src/main/java/io/dataease/provider/datasource/ApiProvider.java
  core/backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  core/backend/src/main/resources/i18n/messages_en_US.properties
  core/backend/src/main/resources/i18n/messages_zh_CN.properties
  core/backend/src/main/resources/i18n/messages_zh_TW.properties
  extensions/dataease-extensions-datasource/dm/dm-backend/src/main/java/io/dataease/plugins/datasource/dm/provider/DmConfig.java
  extensions/dataease-extensions-datasource/dm/dm-frontend/src/views/dm.vue
Labels: 类型:bug

#6893 refactor: 优化外部参数过滤组件配置名称显示
  core/frontend/src/store/index.js
  core/frontend/src/views/panel/outerParamsSet/index.vue
Labels: 类型:优化

#6896 perf: 过滤器在编辑页面触发两次请求
  core/frontend/src/components/canvas/DeCanvas.vue
  core/frontend/src/components/widget/deWidget/DeDate.vue
  core/frontend/src/components/widget/deWidget/DeInputSearch.vue
  core/frontend/src/components/widget/deWidget/DeNumberRange.vue
  core/frontend/src/components/widget/deWidget/DeSelect.vue
  core/frontend/src/components/widget/deWidget/DeSelectGrid.vue
  core/frontend/src/components/widget/deWidget/DeSelectTree.vue
  core/frontend/src/views/panel/edit/index.vue
Labels: 类型:优化

#6899 fix: 外部参数下拉树不生效问题
  core/frontend/src/store/index.js
Labels: 类型:bug

#6901 refactor: 去掉打印
  core/backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:优化

#6902 fix: 列表过滤器模糊搜索缺少选项
  core/frontend/src/components/widget/deWidget/DeSelectGrid.vue
Labels: 类型:bug

#6903 refactor: 调整过滤组件边框图层层级，优化外部参数优先级
  core/frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  core/frontend/src/components/deDrag/index.vue
  core/frontend/src/store/index.js
Labels: 类型:优化

#6905 fix(视图): 修复指标/维度多选拖拽未正确删除不符合的项
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/chart/view/ChartEdit.vue
  extensions/dataease-extensions-view/view-3dpie/view-3dpie-frontend/src/views/highcharts/3dpie/data.vue
  extensions/dataease-extensions-view/view-bubblemap/view-bubblemap-frontend/src/views/echarts/map/buddle/data.vue
  extensions/dataease-extensions-view/view-chartmix/view-chartmix-frontend/src/views/antv/chartmix/data.vue
  extensions/dataease-extensions-view/view-racebar/view-racebar-frontend/src/views/antv/racebar/data.vue
  extensions/dataease-extensions-view/view-sankey/view-sankey-frontend/src/views/antv/sankey/data.vue
  extensions/dataease-extensions-view/view-symbolmap/view-symbolmap-frontend/src/views/antv/symbolmap/data.vue
Labels: 类型:bug

#6910 fix(视图): 修复联动跳转选框在全屏预览状态下部分不可见
  core/frontend/src/components/canvas/components/editor/ViewTrackBar.vue
Labels: 类型:bug

#6912 perf: 过滤器设置首项作用于tab内视图预览无效
  core/frontend/src/components/canvas/components/editor/Preview.vue
Labels: 类型:优化

#6914 Pr@dev@fix sql
  core/backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/system/datasource/DsConfiguration.vue
Labels: 类型:bug

#6917 perf: 下拉过滤器首选项作用于tab中视图(编辑状态)
  core/frontend/src/utils/conditionUtil.js
Labels: 类型:优化

#6920 perf: 下拉过滤器与选项卡交互
  core/frontend/src/components/canvas/utils/utils.js
  core/frontend/src/components/widget/deWidget/DeSelect.vue
  core/frontend/src/utils/conditionUtil.js
Labels: 类型:优化

#6942 fix: 关联数据集保存 #6894
  core/backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#6945 fix: 关联数据集报错 #6894
  core/backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug
