Repository dataease/dataease, pull requests merged in 2023-03, with the labels that each got.

#4681 feat: 参数设置 时间选择组件改造
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:新功能

#4688 fix(应用): 修复应用不支持视图计算字段的问题 #4686
  backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
Labels: 类型:bug

#4711 refactor: 升级版本号
  backend/pom.xml
  pom.xml
Labels: 类型:优化

#4715 fix: 修复公共链接获取多余用户信息漏洞问题
  backend/src/main/java/io/dataease/auth/api/dto/CurrentUserDto.java
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/controller/sys/SystemInfoController.java
  backend/src/main/java/io/dataease/dto/UserLoginInfoDTO.java
  backend/src/main/java/io/dataease/service/SystemInfoService.java
  frontend/src/api/systemInfo/userLogin.js
  frontend/src/components/canvas/components/editor/Preview.vue
Labels: 类型:bug

#4718 refactor: 升级版本号
  backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskLogService.java
  backend/src/main/resources/db/migration/V52__1.18.5.sql
Labels: 类型:优化

#4721 fix(仪表板): 修复站内分享导出明细表部分存在无权限问题 #4697
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java
  frontend/src/components/canvas/customComponent/UserViewDialog.vue
Labels: 类型:bug

#4731 feat(视图): echarts表格支持设置边框颜色、自动换行
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/senior/ScrollCfg.vue
  frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
  frontend/src/views/chart/components/table/TableNormal.vue
Labels: 类型:新功能

#4740 feat(视图-子维度下钻): 视图支持从子维度下钻
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:新功能

#4744 feat(仪表板): 仪表板间跳转，支持携带下钻多级参数 #4695
  frontend/src/components/canvas/components/editor/PreviewEject.vue
Labels: 类型:新功能

#4743 fix(过滤器): 数字区间只能输入整数
  frontend/src/components/widget/deWidget/DeNumberRange.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:bug

#4746 fix(过滤器): 树过滤器在sqlserver和ck数据源不能选择单字段过滤
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:bug

#4757 fix(视图): 视图未更换数据集直接点确定时不清空视图计算字段
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#4760 refactor: 首页适配新blog
  backend/src/main/java/io/dataease/service/wizard/ReptileService.java
  frontend/src/views/wizard/index.vue
Labels: 类型:优化

#4761 feat(登录): 多客户端同时登录限制
  backend/src/main/java/io/dataease/auth/api/AuthApi.java
  backend/src/main/java/io/dataease/auth/api/dto/SeizeLoginDto.java
  backend/src/main/java/io/dataease/auth/server/AuthServer.java
  backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
  backend/src/main/java/io/dataease/auth/util/JWTUtils.java
  backend/src/main/java/io/dataease/commons/constants/ParamConstants.java
  backend/src/main/java/io/dataease/commons/model/OnlineUserModel.java
  backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  backend/src/main/resources/db/migration/V52__1.18.5.sql
  backend/src/main/resources/ehcache/ehcache.xml
  frontend/src/api/user.js
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/index.vue
  frontend/src/utils/index.js
  frontend/src/utils/message.js
  frontend/src/utils/request.js
  frontend/src/views/login/index.vue
  frontend/src/views/system/sysParam/BasicSetting.vue
  frontend/src/websocket/index.js
Labels: 类型:新功能

#4765 feat(登录): 关闭浏览器之前执行登出
  frontend/src/layout/components/Topbar.vue
  frontend/src/utils/index.js
  frontend/vue.config.js
Labels: 类型:新功能

#4762 fix(视图-日期字段下钻): 修复视图下钻时包含日期字段返回空数据
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:bug

#4768 fix(仪表板): 修复新用户创建第一个仪表板目录时需要刷新一下才出现的问题 #4767
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#4770 refactor(仪表板): 删除文案优化 #4766
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:优化

#4771 perf(过滤器): 过滤器字段过多样式优化
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
Labels: 类型:优化

#4777 refactor: 计算字段函数为空时增加提示
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/view/CalcChartFieldEdit.vue
  frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:优化

#4778 perf(登录): 移动端禁止多端登录
  frontend/src/views/chart/view/ChartEdit.vue
  mobile/src/common/js/request/index.js
  mobile/src/locale/en.json
  mobile/src/locale/zh-Hans.json
  mobile/src/locale/zh-Hant.json
  mobile/src/pages/login/index.vue
  mobile/src/pages/tabBar/me/index.vue
  mobile/src/settings.js
Labels: 类型:优化

#4784 perf(登录): 多端登录限制缓存优化
  backend/src/main/java/io/dataease/auth/util/JWTUtils.java
  backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java
Labels: 类型:优化

#4787 fix(视图-下钻): 修复视图下钻异常
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#4797 fix(视图-分组堆叠柱状图): 修复分组堆叠柱状图标签内容只能单选
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shapeAttr/LabelSelectorAntV.vue
  frontend/src/views/chart/group/Group.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#4804 fix: sql数据集保存时，变量生效
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#4807 fix(数据集): 修复关联数据集不选字段报错的问题
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#4812 perf(仪表板): 背景图片接口上传任意文件issue#4798
  backend/src/main/java/io/dataease/controller/staticResource/StaticResourceController.java
  backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java
  frontend/src/api/staticResource/staticResource.js
Labels: 类型:优化

#4816 refactor(视图): 优化边框样式，防止组件预览页面显示双框 #4813
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
Labels: 类型:优化

#4818 perf: sql注入bug-issue#4795
  backend/src/main/java/io/dataease/auth/annotation/SqlInjectValidator.java
  backend/src/main/java/io/dataease/auth/aop/SqlInjectAop.java
  backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java
  backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
  backend/src/main/java/io/dataease/controller/panel/api/StoreApi.java
  backend/src/main/java/io/dataease/controller/sys/MsgController.java
  backend/src/main/java/io/dataease/controller/sys/SysDeptController.java
  backend/src/main/java/io/dataease/controller/sys/SysLogController.java
  backend/src/main/java/io/dataease/controller/sys/SysPluginController.java
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
Labels: 类型:优化

#4821 refactor: 计算字段函数为空时增加提示
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#4836 fix(视图-下钻): 修复部分视图下钻异常
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#4842 refactor(数据集): SQL数据集进入编辑时默认不执行SQL
  frontend/src/views/dataset/add/AddSQL.vue
Labels: 类型:优化

#4843 refactor: 更换首页技术交流群二维码
  frontend/src/assets/wizard_wechat-group.png
  frontend/src/views/wizard/index.vue
Labels: 类型:优化

#4846 fix(视图-下钻): 修复维度重复时下钻异常
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#4865 fix(过滤器): 弹框中下拉备选项无法显示
  frontend/src/components/elVisualSelect/index.vue
  frontend/src/views/panel/filter/FilterDialog.vue
Labels: 类型:bug

#4866 fix(视图): 修复部分外置数据库复制带有视图字段的仪表板时报错问题 #4854
  backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
Labels: 类型:bug

#4867 fix(过滤器): 英文逗号引起查询错误
  frontend/src/components/widget/deWidget/DeSelect.vue
Labels: 类型:bug

#4879 perf(消息api): 排序字段报错
  backend/src/main/java/io/dataease/auth/aop/SqlInjectAop.java
Labels: 类型:优化

#4881 fix: 企业微信 用户管理错位
  frontend/src/views/system/user/index.vue
Labels: 类型:bug

#4887 fix(仪表板): 修复首次新建的仪表板不刷新界面直接移动造成内部视图丢失的问题
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:bug

#4890 fix(系统设置): 地图设置国际化
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/system/sysParam/MapSetting/MapSettingRight.vue
Labels: 类型:bug

#4902 fix(视图): 修复mysql日期不能过滤的问题 #4891
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug

#4904 fix(视图): 修复日期不能过滤的问题
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug

#4912 fix(公共链接): 修复公共链接部分明细表导出失败问题
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#4923 fix(数据集): 修复数据集菜单树操作显示不同步问题
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:bug

#4941 refactor(仪表板): excel导出按钮防止重复点击#4925
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/components/canvas/customComponent/UserViewDialog.vue
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:优化

#4942 refactor(仪表板): 批量操作文案修改 #4884
  frontend/src/components/canvas/components/Toolbar.vue
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:优化

#4943 refactor(仪表板): 新建仪表板默认关闭自动刷新
  frontend/src/views/panel/panel.js
Labels: 类型:优化

#4944 fix(视图-地图): 修改地图icon
  frontend/src/icons/svg/buddle-map.svg
  frontend/src/icons/svg/map.svg
Labels: 类型:bug
