Repository dataease/dataease, pull requests merged in 2023-09, with the labels that each got.

#6033 fix: 时间过滤
  core/backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
Labels: 类型:bug

#6034 fix: 分组堆叠柱状图日期堆叠项支持年季度和年周#5290
  core/frontend/src/views/chart/components/dragItem/ChartDragItem.vue
  core/frontend/src/views/chart/components/dragItem/DimensionExtItem.vue
  core/frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#6038 fix(视图-地图): 点击事件触发多次
  core/frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#6040 Merge branch 'dev' into pr@dev@fix_gauge_batch_edit
  core/frontend/src/views/chart/chart/util.js
  core/frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:bug

#6041 feat: 自动识别移动端配置
  core/backend/src/main/java/io/dataease/commons/constants/ParamConstants.java
  core/backend/src/main/java/io/dataease/controller/sys/response/BasicInfo.java
  core/backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  core/frontend/src/components/canvas/components/editor/Preview.vue
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/utils/index.js
  core/frontend/src/views/system/sysParam/BasicSetting.vue
Labels: 类型:新功能

#6042 fix: 引入依赖错误github#5770
  core/backend/src/main/java/io/dataease/auth/service/ProxyAuthService.java
Labels: 类型:bug

#6043 fix: websocket基础url
  core/frontend/src/websocket/index.js
Labels: 类型:bug

#6045 Merge branch 'dev' into pr@dev@fix_font_family
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/chart/chart/chart.js
  core/frontend/src/views/chart/components/ChartComponentG2.vue
  core/frontend/src/views/chart/components/ChartComponentS2.vue
  core/frontend/src/views/chart/components/componentStyle/TitleSelector.vue
  core/frontend/src/views/chart/components/componentStyle/TitleSelectorAntV.vue
  core/frontend/src/views/chart/components/normal/LabelNormal.vue
  core/frontend/src/views/chart/components/normal/LabelNormalText.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
  extensions/dataease-extensions-view/view-chartmix/view-chartmix-frontend/src/views/antv/chartmix/index.vue
  extensions/dataease-extensions-view/view-sankey/view-sankey-frontend/src/views/antv/sankey/index.vue
  extensions/dataease-extensions-view/view-symbolmap/view-symbolmap-frontend/src/views/antv/symbolmap/index.vue
Labels: 类型:bug

#6046 fix(仪表板): 修复全屏模式下过滤组件显示异常问题
  4362e265-5fbd-49d7-9e63-d88d82efe3fe.xml
  476409e8-9887-438e-a6ce-e4e29ddd64bc.xml
  core/frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  core/frontend/src/components/canvas/components/editor/EditBar.vue
Labels: 类型:bug

#6047 refactor(仪表板): 除了编辑状态下，鼠标移动到仪表板组件上时不显示边框
  core/frontend/src/components/canvas/components/editor/ComponentWrapper.vue
Labels: 类型:优化

#6048 fix(仪表板): 仪表板背景不透明 度0的时候失效
  core/frontend/src/components/canvas/components/editor/DeEditor.vue
  core/frontend/src/components/canvas/components/editor/Preview.vue
  core/frontend/src/components/canvas/customComponent/UserViewDialog.vue
  core/frontend/src/components/canvas/customComponent/UserViewMobileDialog.vue
  core/frontend/src/views/background/BackgroundOverall.vue
  core/frontend/src/views/background/index.vue
  core/frontend/src/views/chart/components/componentStyle/dialog/RemarkEditor.vue
  core/frontend/src/views/panel/edit/ComponentWait.vue
  core/frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#6049 fix(视图-地图): 删除地图下钻错误提示
  core/frontend/src/views/chart/components/ChartComponent.vue
  extensions/dataease-extensions-view/view-bubblemap/view-bubblemap-frontend/src/views/echarts/map/buddle/index.vue
Labels: 类型:bug

#6054 perf(地图设置): 地球村和中国区域只能增加不能删除提示#5979
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/views/system/sysParam/MapSetting/MapSettingLeft.vue
  core/frontend/src/views/system/sysParam/MapSetting/index.vue
  core/frontend/src/views/system/sysParam/index.vue
Labels: 类型:优化

#6055 fix: 修复表格下钻页码不从第一页开始的问题
  core/frontend/src/views/chart/components/ChartComponentS2.vue
Labels: 类型:bug

#6052 fix(仪表板): 修复全屏模式下过滤组件显示异常问题
  core/frontend/src/components/canvas/components/editor/ComponentWrapper.vue
Labels: 类型:bug

#6062 feat: 登录失败次数过多发送邮件通知管理员#5621
  core/backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
  core/backend/src/main/java/io/dataease/commons/constants/ParamConstants.java
  core/backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
  core/backend/src/main/java/io/dataease/ext/ExtSysUserMapper.java
  core/backend/src/main/java/io/dataease/ext/ExtSysUserMapper.xml
  core/backend/src/main/java/io/dataease/service/sys/SysUserService.java
  core/backend/src/main/java/io/dataease/service/system/EmailService.java
  core/backend/src/main/java/io/dataease/service/system/SystemParameterService.java
  core/backend/src/main/resources/i18n/messages_en_US.properties
  core/backend/src/main/resources/i18n/messages_zh_CN.properties
  core/backend/src/main/resources/i18n/messages_zh_TW.properties
  core/frontend/src/views/system/sysParam/BasicSetting.vue
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/loginlimit/dto/response/LoginLimitInfo.java
Labels: 类型:新功能

#6059 refactor(仪表板): 优化模版查询结果，防止数据过多出现卡顿 #5992
  core/backend/src/main/java/io/dataease/controller/request/panel/PanelTemplateRequest.java
  core/backend/src/main/java/io/dataease/ext/ExtPanelTemplateMapper.xml
Labels: 类型:优化

#6065 fix(仪表板): 修复Tab组件中的过滤组件设置默认值不生效问题 #5795
  core/frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#6071 fix: 修复数据集移动可以重名的问题
  core/backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java
Labels: 类型:bug

#6073 feat: 表格行/列头悬停提示
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  core/frontend/src/main.js
  core/frontend/src/views/chart/chart/chart.js
  core/frontend/src/views/chart/chart/common/common_antv.js
  core/frontend/src/views/chart/chart/table/table-info.js
  core/frontend/src/views/chart/chart/util.js
  core/frontend/src/views/chart/components/ChartComponentS2.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:新功能

#6074 fix: 气泡图大小字段失效
  core/frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#6075 refactor: 文本/指标卡位置属性编辑调整#5978
  core/frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:优化

#6077 feat: AntV 柱状图/条形图支持刷选
  4362e265-5fbd-49d7-9e63-d88d82efe3fe.xml
  476409e8-9887-438e-a6ce-e4e29ddd64bc.xml
  core/frontend/src/views/chart/chart/bar/bar_antv.js
Labels: 类型:新功能

#6082 fix: 透视表列悬浮显示内容有误
  core/frontend/src/views/chart/chart/table/table-info.js
Labels: 类型:bug

#6078 fix(仪表板): 修复全屏模式下动态排序没有提示问题
  core/frontend/src/components/canvas/customComponent/UserView.vue
  extensions/dataease-extensions-view/view-racebar/view-racebar-frontend/src/views/antv/racebar/index.vue
Labels: 类型:bug

#6086 fix: 使用echarts地图符号功能模版报错#5918
  core/backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#6087 fix: AntV 组合图标题设置不生效
  extensions/dataease-extensions-view/view-chartmix/view-chartmix-frontend/src/views/antv/chartmix/index.vue
Labels: 类型:bug

#6093 fix: 桑基图和混合图标题属性调整无效
  core/backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  extensions/dataease-extensions-view/view-chartmix/view-chartmix-frontend/src/views/antv/chartmix/index.vue
  extensions/dataease-extensions-view/view-sankey/view-sankey-frontend/src/views/antv/sankey/index.vue
Labels: 类型:bug

#6108 Merge branch 'dev' into pr@dev@fixrowpermissions
  core/backend/src/main/java/io/dataease/plugins/server/RowPermissionsController.java
  core/backend/src/main/java/io/dataease/plugins/server/RowPermissionsTreeController.java
  core/frontend/src/api/dataset/dataset.js
Labels: 类型:bug

#6109 fix: pg、db2 支持currentSchema
  core/backend/src/main/java/io/dataease/dto/datasource/Db2Configuration.java
  core/backend/src/main/java/io/dataease/dto/datasource/PgConfiguration.java
Labels: 类型:bug

#6131 fix(插件): 自动升级插件版本号
  core/backend/src/main/java/io/dataease/ext/ExtSysPluginMapper.java
  core/backend/src/main/java/io/dataease/ext/ExtSysPluginMapper.xml
  core/backend/src/main/java/io/dataease/plugins/config/PluginRunner.java
  core/backend/src/main/java/io/dataease/service/sys/PluginService.java
Labels: 类型:bug

#6136 fix: 加强图片校验，防止恶意代码通过合成到图片上传到服务器中引起的攻击行为
  core/backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java
  core/frontend/src/views/background/BackgroundOverall.vue
  core/frontend/src/views/panel/appTemplate/AppTemplateContent.vue
Labels: 类型:bug

#6137 Merge branch 'dev' into pr@dev@fixrowpermissions
  core/backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
Labels: 类型:bug

#6140 fix(日志): apikey记录日志
  core/backend/src/main/java/io/dataease/auth/aop/DeLogAnnotationHandler.java
  core/backend/src/main/java/io/dataease/commons/constants/SysLogConstants.java
  core/backend/src/main/java/io/dataease/ext/ExtSysLogMapper.xml
  core/backend/src/main/java/io/dataease/plugins/server/XUserKeysServer.java
  core/backend/src/main/java/io/dataease/service/sys/log/LogService.java
  core/backend/src/main/resources/i18n/messages_en_US.properties
  core/backend/src/main/resources/i18n/messages_zh_CN.properties
  core/backend/src/main/resources/i18n/messages_zh_TW.properties
Labels: 类型:bug

#6159 fix: 编辑时切换到明细表会清空字段
  core/frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#6198 feat: 动态设置访问路径前缀
  core/backend/src/main/java/io/dataease/controller/IndexController.java
  core/frontend/.env.production
  core/frontend/.env.staging
  core/frontend/public/link.html
  core/frontend/vue.config.js
Labels: 类型:新功能
