Repository dataease/dataease, pull requests merged in 2023-05, with the labels that each got.

#5144 refactor(仪表板): 优化仪表板预览加载提示 #5141
  frontend/src/api/panel/enshrine.js
  frontend/src/api/panel/linkJump.js
  frontend/src/api/panel/linkage.js
  frontend/src/api/panel/panel.js
  frontend/src/api/panel/pdfTemplate.js
Labels: 类型:优化

#5170 fix: 精简模式手动修改字段类型为数值后不生效
  backend/src/main/java/io/dataease/commons/utils/ExcelXlsxReader.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
Labels: 类型:bug

#5173 Pr@dev st fix
  frontend/vue.config.js
Labels: 类型:bug

#5174 feat: 透视表数据行维度字段支持同环比
  frontend/src/views/chart/components/compare/CompareEdit.vue
  frontend/src/views/chart/components/dragItem/QuotaItem.vue
Labels: 类型:新功能

#5185 Pr@dev@fixextratdata
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:bug

#5189 refactor: 去掉打印
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:优化

#5202 Pr@dev st fix
  frontend/src/components/canvas/components/editor/ViewTrackBar.vue
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/views/panel/filter/FilterDialog.vue
Labels: 类型:bug

#5208 refactor: 组合图轴值最大值不能小于数值最大值
  frontend/src/views/chart/chart/mix/mix.js
Labels: 类型:优化

#5212 Pr@dev st fix
  frontend/vue.config.js
Labels: 类型:bug

#5213 fix(消息管理): 删除已读消息api存在IDOR漏洞
  backend/src/main/java/io/dataease/ext/ExtSysMsgMapper.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
Labels: 类型:bug

#5215 fix(定时报告): 立即执行停止状态的任务报错
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
Labels: 类型:bug

#5216 fix(消息管理): 消息批量已读api存在IDOR安全漏洞
  backend/src/main/java/io/dataease/ext/ExtSysMsgMapper.java
  backend/src/main/java/io/dataease/service/message/SysMsgService.java
Labels: 类型:bug

#5221 refactor: 获取 oracle 所有表
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
Labels: 类型:优化

#5224 fix(视图-对称条形图): 修复对称条形图值轴和刻度异常
  frontend/src/components/canvas/components/editor/SettingMenu.vue
  frontend/src/views/chart/chart/bar/bar_antv.js
  frontend/src/views/chart/chart/common/common_antv.js
Labels: 类型:bug

#5240 refactor(仪表板): 视频组件可修改背景色 #5228
  frontend/src/custom-theme.css
Labels: 类型:优化

#5255 feat: 组合图副轴值支持同环比
  frontend/src/views/chart/components/dragItem/QuotaExtItem.vue
Labels: 类型:新功能

#5257 refactor(首页): 增加首页论坛链接
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/wizard/index.vue
Labels: 类型:优化

#5259 refactor(首页): 增加首页论坛链接
  frontend/src/views/wizard/index.vue
Labels: 类型:优化

#5260 Pr@dev st fix
  frontend/src/components/canvas/components/editor/PreviewFullScreen.vue
  frontend/src/components/canvas/customComponent/DeVideo.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/background/index.vue
  frontend/src/views/chart/components/componentStyle/TitleSelectorAntV.vue
  frontend/src/views/chart/components/table/TableNormal.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/FuSplitPane.vue
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/add/union/UnionPreview.vue
  frontend/src/views/dataset/common/DatasetTableData.vue
  frontend/src/views/dataset/data/TabDataPreview.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
  frontend/src/views/panel/index.vue
  frontend/src/views/panel/list/PanelViewShow.vue
  frontend/src/views/panel/subjectSetting/panelStyle/FilterStyleSelector.vue
  frontend/src/views/system/datasource/DriverForm.vue
  frontend/src/views/system/datasource/DsConfiguration.vue
  frontend/vue.config.js
Labels: 类型:bug

#5261 fix(消息管理): 接受管理中“国际飞书”无法隐藏#5119
  backend/src/main/java/io/dataease/controller/sys/MsgController.java
  frontend/src/views/msg/Setting.vue
Labels: 类型:bug

#5262 fix(地图): 缺失维度指标的情况下标题也无法显示#5172
  frontend/src/views/chart/chart/map/map.js
Labels: 类型:bug

#5266 feat(仪表板): 文本搜索组件忽略大小写
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:新功能

#5268 refactor: 不同用户登录及时清理历史菜单缓存 #5118
  frontend/src/store/modules/user.js
Labels: 类型:优化

#5272 fix(视图): 修复富文本视图，会出现无法编辑标题名称的情况 #5182
  frontend/src/views/chart/components/componentStyle/TitleSelectorAntV.vue
Labels: 类型:bug

#5273 fix(仪表板): 修复编辑手机端仪表板后，重新切换到仪表板可能显示异常的问题 #4717
  frontend/src/views/panel/list/PanelMain.vue
Labels: 类型:bug

#5276 fix(仪表板): 修复仪表板名字较长时信息被压缩问题 #4860
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#5278 feat(lic): ak/sk增加许可验证逻辑
  backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
Labels: 类型:新功能

#5279 fix(仪表板): 修复仪表板目录删除后，目录目录下的仪表板对应的默认仪表板可能没有跟随删除问题 #5171
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.java
  backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
Labels: 类型:bug

#5283 refactor: 优化关联数据集保存速度
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
Labels: 类型:优化

#5285 fix(仪表板): 带过滤器的模版过滤器无法切换数据集
  frontend/src/views/panel/filter/FilterDialog.vue
Labels: 类型:bug

#5289 fix(仪表板): 修复部分官方示例模板导入后无法使用官方示例数据集的问题
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#5292 fix(仪表板): 修复仪表板复用组件，位置属性与目标仪表板设置不一致问题
  frontend/src/components/canvas/store/copy.js
  frontend/src/components/canvas/utils/style.js
Labels: 类型:bug

#5294 fix(视图-表格): 修复表格序号字体样式无法调整
  frontend/src/views/chart/chart/common/common_table.js
Labels: 类型:bug

#5297 Pr@dev st fix
  frontend/src/views/system/plugin/Dynamic.vue
Labels: 类型:bug

#5303 feat(视图-地图): ECharts 地图支持空值过滤
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/components/senior/FunctionCfg.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#5308 fix: 组件优化导致加载异常
  frontend/src/components/canvas/components/editor/PreviewFullScreen.vue
  frontend/src/components/canvas/customComponent/DeVideo.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/chart/components/componentStyle/TitleSelectorAntV.vue
  frontend/src/views/chart/components/table/TableNormal.vue
  frontend/src/views/chart/view/ChartEdit.vue
  frontend/src/views/chart/view/FuSplitPane.vue
  frontend/src/views/dataset/add/AddApi.vue
  frontend/src/views/dataset/add/AddCustom.vue
  frontend/src/views/dataset/add/AddDB.vue
  frontend/src/views/dataset/add/AddExcel.vue
  frontend/src/views/dataset/add/union/UnionPreview.vue
  frontend/src/views/dataset/common/DatasetTableData.vue
  frontend/src/views/dataset/data/TabDataPreview.vue
  frontend/src/views/panel/edit/index.vue
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
  frontend/src/views/panel/index.vue
  frontend/src/views/panel/list/PanelViewShow.vue
  frontend/src/views/system/datasource/DsConfiguration.vue
  frontend/src/views/system/plugin/Dynamic.vue
  frontend/vue.config.js
Labels: 类型:bug

#5311 fix(仪表板): 修复悬浮组件移入tab组件可能导致浏览器卡顿问题
  frontend/src/api/map/map.js
  frontend/src/components/deDrag/index.vue
Labels: 类型:bug

#5312 refactor: 季度、周格式增加字母标识
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:优化

#5323 Pr@dev st fix
  frontend/src/components/canvas/components/editor/ViewTrackBar.vue
Labels: 类型:bug

#5327 feat(视图-地图，汇总表): ECharts 地图，AntV 汇总表支持空值过滤
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/chart.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/ChartComponent.vue
  frontend/src/views/chart/components/senior/FunctionCfg.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#5332 fix: 校验数据库名称
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
Labels: 类型:bug

#5333 feat(视图-表格): AntV明细表，透视表支持空值策略
  frontend/src/views/chart/chart/table/table-info.js
  frontend/src/views/chart/components/senior/FunctionCfg.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:新功能

#5338 Pr@dev st fix
  frontend/src/views/system/task/FilterUserRecord.vue
Labels: 类型:bug

#5342 feat(仪表板): 删除分享IDOR漏洞
  backend/src/main/java/io/dataease/service/panel/ShareService.java
Labels: 类型:新功能

#5346 Pr@dev st fix
  frontend/src/views/dataset/add/AddSQL.vue
  frontend/src/views/system/task/FilterUser.vue
  frontend/src/views/system/task/FilterUserRecord.vue
Labels: 类型:bug

#5350 fix(仪表板): 过滤器删除最后一个字段后前面的字段也无法展示
  frontend/src/views/panel/filter/FilterDialog.vue
Labels: 类型:bug

#5359 fix: sqlserver 过滤中文
  backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:bug

#5361 fix(仪表板): 修复仪表板联动后需要清除联动条件才能进行下次联动的问题
  frontend/public/tinymce/skins/ui/oxide-dark/skin.css
  frontend/public/tinymce/skins/ui/oxide-dark/skin.min.css
  frontend/public/tinymce/skins/ui/oxide/skin.css
  frontend/public/tinymce/skins/ui/oxide/skin.min.css
  frontend/src/components/canvas/customComponent/DeRichTextView.vue
  frontend/src/utils/conditionUtil.js
Labels: 类型:bug

#5365 fix(仪表板): 修复删除动态时间组件定时器没有删除导致异常刷新问题
  frontend/src/components/widget/deWidget/DeDate.vue
Labels: 类型:bug

#5366 fix(仪表板): 修复仪表板联动后需要清除联动条件才能进行下次联动的问题
  frontend/src/utils/conditionUtil.js
Labels: 类型:bug

#5371 fix(视图): 定时同步数据集时间类型字段过滤不生效
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
Labels: 类型:bug

#5374 fix(数据源): 模糊搜索未忽略大小写
  frontend/src/views/system/datasource/DsTree.vue
Labels: 类型:bug

#5379 fix(数据集): 优化数据集同步界面分页查询逻辑，解决分页查询慢的问题
  backend/src/main/java/io/dataease/ext/ExtDataSetTaskMapper.xml
Labels: 类型:bug
