Repository dataease/dataease, pull requests merged in 2023-07, with the labels that each got.

#5571 fix(插件管理): 插件文件上传漏洞#5559
  backend/src/main/java/io/dataease/commons/utils/DeFileUtils.java
  backend/src/main/java/io/dataease/controller/sys/SysPluginController.java
Labels: 类型:bug

#5573 Pr@dev st fix
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/customComponent/UserView.vue
  frontend/src/views/chart/components/ChartComponentG2.vue
Labels: 类型:bug

#5581 Pr@dev st fix
  frontend/src/components/asyncComponent/index.vue
Labels: 类型:bug

#5598 fix(仪表板): 修复预览复用预览视图未显示问题
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
Labels: 类型:bug

#5610 refactor(视图): 视图时间和数值字段过滤时支持不为空选项 #5291
  frontend/src/views/chart/components/filter/QuotaFilterEditor.vue
  frontend/src/views/chart/components/filter/ResultFilterEditor.vue
Labels: 类型:优化

#5616 fix(仪表板): 优化联动配置界面，防止联动配置卡顿问题
  backend/src/main/java/io/dataease/ext/ExtPanelViewLinkageMapper.xml
  frontend/src/components/canvas/components/editor/LinkageField.vue
Labels: 类型:bug

#5617 refactor(仪表板): 调整组件最大高度,防止编辑界面与预览界面高度不一致问题
  frontend/src/views/chart/view/PositionAdjust.vue
Labels: 类型:优化

#5618 fix(仪表板): 修复默认仪表盘里重命名改完不生效问题 #5599
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:bug

#5625 fix(视图): 修复doris过滤时间不为空不生效的问题
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
Labels: 类型:bug

#5626 fix: impala 过滤时间出错
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
  backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
Labels: 类型:bug

#5631 fix: 校验数据库名称
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
Labels: 类型:bug

#5632 fix(应用管理): 应用记录查询存在sql注入漏洞
  backend/src/main/java/io/dataease/controller/panel/AppLogController.java
  backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.java
  backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
Labels: 类型:bug

#5635 Pr@dev st fix
  frontend/src/lang/zh.js
Labels: 类型:bug

#5638 fix(视图-数值格式化): 修复对称条形图副值轴无法调整格式化
  frontend/src/views/chart/components/dragItem/QuotaExtItem.vue
  frontend/src/views/chart/view/ChartEdit.vue
Labels: 类型:bug

#5640 fix(视图-PDF导出): PDF导出时图标显示异常
  frontend/src/components/canvas/components/editor/EditBar.vue
Labels: 类型:bug

#5648 feat: java8升级java11
  backend/pom.xml
Labels: 类型:新功能

#5661 fix: 修复存储型XSS漏洞
  frontend/src/views/chart/view/TitleRemark.vue
  frontend/src/views/dataset/data/components/LazyTree.vue
  frontend/src/views/dataset/group/GroupMoveSelector.vue
  frontend/src/views/login/index.vue
  frontend/src/views/panel/export/PDFPreExport.vue
  frontend/src/views/system/user/index.vue
  frontend/src/views/wizard/WizardCard.vue
  frontend/src/views/wizard/WizardCardEnterprise.vue
  frontend/src/views/wizard/details/CardDetail.vue
  frontend/src/views/wizard/details/LatestDevelopments.vue
Labels: 类型:bug

#5690 refactor: 更新typos规则
  .typos.toml
Labels: 类型:优化

#5706 Pr@dev st fix
  frontend/src/views/chart/components/componentStyle/dialog/RemarkEditor.vue
Labels: 类型:bug

#5711 perf(许可): 许可过期提示
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/layout/components/Licbar.vue
Labels: 类型:优化

#5712 perf(视图): 色彩地图放大点击不提示无钻取字段
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:优化

#5714 fix(仪表板): 修复选项卡后面没有展开的tab页没有加载导致无法过滤的问题
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#5719 perf(过滤器): 悬浮提示字段所属数据集
  frontend/src/components/dragItem/index.vue
  frontend/src/views/panel/filter/FilterDialog.vue
  frontend/src/views/panel/filter/filterMain/FilterHead.vue
Labels: 类型:优化

#5726 fix: 抽取 excel 数据
  backend/src/main/java/io/dataease/commons/utils/ExcelXlsxReader.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
Labels: 类型:bug

#5734 fix: 禁止关闭浏览器注销token功能
  frontend/src/layout/components/Topbar.vue
Labels: 类型:bug

#5741 Pr@dev st fix
  frontend/src/views/login/index.vue
Labels: 类型:bug

#5787 fix: 行列权限空指针异常
  backend/src/main/java/io/dataease/service/dataset/PermissionService.java
Labels: 类型:bug

#5796 fix: 修复年份过滤不生效的问题
  backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
Labels: 类型:bug

#5797 Pr@dev st fix
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug
