Repository dataease/dataease, pull requests merged in 2023-06, with the labels that each got.

#5396 fix(仪表板): 修复仪表板视图请求可能被提前取消导致视图不显示问题
  frontend/src/components/canvas/components/editor/Preview.vue
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:bug

#5399 fix(视图-提示): 修复提示框被遮挡
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/views/chart/components/ChartComponentG2.vue
Labels: 类型:bug

#5418 Pr@dev st fix
  frontend/src/views/dataset/Form.vue
  frontend/src/views/dataset/add/AddUnion.vue
  frontend/src/views/panel/list/PanelViewShow.vue
Labels: 类型:bug

#5424 fix(视图-过滤): 修复定时同步数据集时间过滤组件失效。
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
Labels: 类型:bug

#5427 fix(视图-提示): 修复 echarts 提示被遮挡。
  frontend/src/views/chart/components/ChartComponent.vue
Labels: 类型:bug

#5437 fix: 处理日期、时间过滤
  backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
  backend/src/main/java/io/dataease/commons/utils/ExcelXlsReader.java
  backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
  backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
  backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
  backend/src/main/java/io/dataease/service/sys/log/LogService.java
Labels: 类型:bug

#5441 fix(视图-流向地图): 修复流向地图复用按钮被遮挡
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/views/chart/chart/map/map_antv.js
Labels: 类型:bug

#5443 fix(仪表板): 修复tab组件左右移动按钮复用和编辑时被遮挡的问题 #5380
  frontend/src/components/widget/deWidget/DeTabs.vue
Labels: 类型:bug

#5444 refactor(仪表板): 屏蔽树查询组件非必要Loading提示
  frontend/src/api/dataset/dataset.js
Labels: 类型:优化

#5445 fix: 增加应用操作后端权限校验 #5442
  backend/src/main/java/io/dataease/controller/panel/PanelAppTemplateController.java
Labels: 类型:bug

#5447 fix: 拼写纠正
  backend/src/main/java/io/dataease/commons/pool/PriorityThreadPoolExecutor.java
  backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
  backend/src/main/java/io/dataease/service/panel/ShareService.java
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/dataset/data/components/filterFiled.vue
Labels: 类型:bug

#5451 perf(cas): cas切换管理员步骤繁琐
  backend/src/main/java/io/dataease/plugins/server/CasServer.java
Labels: 类型:优化

#5455 perf(用户管理): 删除无用api
  backend/src/main/java/io/dataease/controller/sys/SysUserController.java
Labels: 类型:优化

#5460 refactor(仪表板): 拆分仪表板移动和更新接口，优化后端权限校验 #5450
  backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
  frontend/src/api/panel/panel.js
  frontend/src/views/panel/list/PanelList.vue
Labels: 类型:优化

#5462 perf(仪表板): 数字范围过滤器可用范围
  frontend/src/components/widget/deWidget/DeNumberRange.vue
Labels: 类型:优化

#5470 fix: 初始化引擎失败，数组越界 #5452
  backend/src/main/java/io/dataease/service/engine/EngineService.java
Labels: 类型:bug

#5475 Pr@dev st fix
  frontend/src/components/canvas/components/editor/Preview.vue
Labels: 类型:bug

#5481 feat(定时报告): 邮件支持pdf附件格式
  backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  backend/src/main/java/io/dataease/service/system/EmailService.java
  backend/src/main/resources/db/migration/V55__1.18.8.sql
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
Labels: 类型:新功能

#5491 refactor(视图): 视图复制后名称以-n结尾
  backend/src/main/resources/db/migration/V55__1.18.8.sql
Labels: 类型:优化

#5492 refactor(仪表板): 做联动配置时，同一数据集的视图首次配置默认全部选中
  backend/src/main/java/io/dataease/dto/PanelViewLinkageDTO.java
  backend/src/main/java/io/dataease/ext/ExtPanelViewLinkageMapper.xml
  backend/src/main/java/io/dataease/service/panel/PanelViewLinkageService.java
  backend/src/main/resources/db/migration/V55__1.18.8.sql
  frontend/src/components/canvas/components/editor/EditBar.vue
Labels: 类型:优化

#5500 feat(lic): lic验证慢
  backend/src/main/java/io/dataease/commons/license/DefaultLicenseService.java
Labels: 类型:新功能

#5507 Pr@dev st fix
  frontend/src/permission.js
Labels: 类型:bug

#5513 feat(视图-Excel导出): 视图界面直接可直接导出 Excel
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/components/canvas/customComponent/UserViewDialog.vue
  frontend/src/components/canvas/utils/utils.js
Labels: 类型:新功能

#5514 Pr@dev st fix
  frontend/src/components/canvas/customComponent/UserView.vue
Labels: 类型:bug

#5524 perf(sql白名单): sql注入检测白名单由外部配置文件覆盖
  backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java
  backend/src/main/resources/application.properties
Labels: 类型:优化

#5537 fix(视图-Excel导出): 修复导出按钮及预览界面导出异常
  frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  frontend/src/components/canvas/components/editor/EditBar.vue
  frontend/src/components/canvas/utils/utils.js
  frontend/src/icons/svg/file-excel.svg
Labels: 类型:bug

#5542 fix(视图): 修复辅助线动态值报错 #5534
  backend/src/main/java/io/dataease/service/chart/ChartViewService.java
Labels: 类型:bug

#5564 perf(视图): 地图提示增加隐藏空值设置#5562
  frontend/src/lang/en.js
  frontend/src/lang/tw.js
  frontend/src/lang/zh.js
  frontend/src/views/chart/chart/map/map.js
  frontend/src/views/chart/chart/util.js
  frontend/src/views/chart/components/shapeAttr/TooltipSelector.vue
Labels: 类型:优化

#5565 fix: 拼写错误
  frontend/src/lang/en.js
Labels: 类型:bug
