Repository dataease/dataease, pull requests merged in 2023-12, with the labels that each got.

#6999 feat: 计算字段支持二次引用 #5996
  core/backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  core/backend/src/main/resources/i18n/messages_en_US.properties
  core/backend/src/main/resources/i18n/messages_zh_CN.properties
  core/backend/src/main/resources/i18n/messages_zh_TW.properties
  core/frontend/src/views/chart/view/CalcChartFieldEdit.vue
  core/frontend/src/views/dataset/data/CalcFieldEdit.vue
Labels: 类型:新功能

#7002 fix: 修复首页最新动态跳转链接不正确问题
  core/backend/src/main/java/io/dataease/service/wizard/ReptileService.java
Labels: 类型:bug

#7003 fix: 符号地图标签提示未去重
  extensions/dataease-extensions-view/view-symbolmap/view-symbolmap-backend/src/main/java/io/dataease/plugins/view/official/handler/SymbolMapRSHandler.java
Labels: 类型:bug

#7006 fix: 文本搜索开启必填后首次过滤结果与外部参数冲突问题
  core/frontend/src/store/index.js
Labels: 类型:bug

#7019 fix: ES数据源创建数据集后报错，剔除sql不支持的数据类型 #6293
  core/backend/src/main/java/io/dataease/provider/datasource/EsProvider.java
Labels: 类型:bug

#7031 fix: 修复普通用户移动端设计界面画布区域视图无法展示问题
  core/frontend/src/components/canvas/components/Toolbar.vue
  core/frontend/src/views/mobile/index.vue
  core/frontend/src/views/panel/edit/index.vue
Labels: 类型:bug

#7036 fix: 没有已完成的同步任务，无法进行增量同步
  core/backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
Labels: 类型:bug

#7038 fix: 优化文本XSS校验，防止出现模版编辑出现卡死现象 #5258 #6977
  core/frontend/src/components/canvas/customComponent/VText.vue
Labels: 类型:bug

#7044 perf: 下拉文本首项作用范围超出仪表板
  core/frontend/src/components/canvas/components/editor/Preview.vue
Labels: 类型:优化

#7054 fix: 数据源插件拼接错误
  core/backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
  extensions/dataease-extensions-datasource/dm/dm-backend/src/main/java/io/dataease/plugins/datasource/dm/query/DmConstants.java
  extensions/dataease-extensions-datasource/kylin/kylin-backend/src/main/java/io/dataease/plugins/datasource/kylin/query/KylinConstants.java
  extensions/dataease-extensions-datasource/maxcompute/maxcompute-backend/src/main/java/io/dataease/plugins/datasource/dm/query/MaxConstants.java
  extensions/dataease-extensions-datasource/presto/presto-backend/src/main/java/io/dataease/plugins/datasource/dm/query/PrestoConstants.java
Labels: 类型:bug

#7081 fix: 修复添加边框样式后过滤组件等无点击效果问题
  core/frontend/src/components/canvas/components/editor/ComponentWrapper.vue
  core/frontend/src/components/deDrag/index.vue
Labels: 类型:bug

#7084 fix(视图): 表格详情使用原有样式，其他视图统一样式，不使用斑马纹。
  core/frontend/src/App.vue
  core/frontend/src/components/canvas/components/editor/EditBar.vue
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/components/widget/deWidget/DeTabs.vue
  core/frontend/src/views/chart/components/ChartComponentS2.vue
  core/frontend/src/views/chart/components/shapeAttr/ColorSelector.vue
  core/frontend/src/views/dataset/add/AddExcel.vue
  core/frontend/src/views/system/datasource/DsConfiguration.vue
  core/frontend/src/views/system/sysParam/BasicSetting.vue
Labels: 类型:bug

#7090 fix: 查询按钮设置关联范围失效
  core/frontend/src/components/canvas/components/editor/Preview.vue
Labels: 类型:bug

#7101 fix: 仅调整 Tab 组件的标签顺序未触发到仪表板的保存按钮转为可点击状态问题 #6133
  core/frontend/src/components/canvas/components/editor/SettingMenu.vue
  core/frontend/src/components/widget/deWidget/TabStyle.vue
  core/frontend/src/layout/components/Topbar.vue
Labels: 类型:bug

#7105 feat: 支持分页
  core/backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
  core/backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
  core/frontend/src/views/chart/chart/chart.js
Labels: 类型:新功能

#7110 fix: demo用户默认失效#5995
  core/backend/src/main/resources/db/migration/V59__1.18.14.sql
Labels: 类型:bug

#7111 feat: 支持分页
  core/backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
Labels: 类型:新功能

#7115 feat: 系统管理-任务管理-数据同步菜单支持排序 #5760
  core/backend/src/main/java/io/dataease/ext/ExtDataSetTaskMapper.xml
  core/backend/src/main/java/io/dataease/job/sechedule/ScheduleManager.java
  core/backend/src/main/java/io/dataease/listener/AppStartListener.java
  core/backend/src/main/java/io/dataease/service/ScheduleService.java
  core/backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java
  core/frontend/src/views/system/task/DatasetTaskList.vue
Labels: 类型:新功能

#7134 feat: 定时报告发送至飞书群聊
  core/backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  core/backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/email/dto/request/XpackEmailTaskRequest.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/email/dto/response/XpackEmailTemplateDTO.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/lark/dto/entity/LarkGroupData.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/lark/dto/entity/LarkGroupHttpResult.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/lark/dto/entity/LarkGroupItem.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/lark/dto/entity/LarkGroupResult.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/lark/service/LarkXpackService.java
Labels: 类型:新功能

#7137 feat: 定时报告过滤掉已禁用用户
  core/backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  core/backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
  core/backend/src/main/resources/db/migration/V59__1.18.14.sql
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/email/dto/request/XpackEmailTaskRequest.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/email/dto/request/XpackEmailViewRequest.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/email/dto/response/XpackEmailTemplateDTO.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/email/service/EmailXpackService.java
Labels: 类型:新功能

#7146 refactor(视图-表格编辑): 表格样式编辑部分属性换行。#7124
  core/frontend/src/views/chart/components/shapeAttr/SizeSelector.vue
  core/frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
Labels: 类型:优化

#7158 feat: 定时报告发送至角色、组织
  core/backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/email/dto/request/XpackEmailTaskRequest.java
  sdk/dataease-plugin-interface/src/main/java/io/dataease/plugins/xpack/email/dto/response/XpackEmailTemplateDTO.java
Labels: 类型:新功能

#7166 perf: 定时报告发送组织角色
  core/backend/src/main/java/io/dataease/auth/service/ExtAuthService.java
  core/backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
  core/backend/src/main/java/io/dataease/commons/utils/AuthUtils.java
  core/backend/src/main/java/io/dataease/ext/ExtAuthMapper.java
  core/backend/src/main/java/io/dataease/ext/ExtAuthMapper.xml
  core/backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
Labels: 类型:优化

#7172 perf: 删除页面右上角修改密码提示功能
  core/frontend/src/layout/index.vue
Labels: 类型:优化

#7179 perf: 过滤器必填逻辑
  core/frontend/src/components/canvas/customComponent/UserView.vue
  core/frontend/src/components/dataease/DeOutWidget.vue
  core/frontend/src/components/widget/deWidget/DeDate.vue
  core/frontend/src/components/widget/deWidget/DeInputSearch.vue
  core/frontend/src/components/widget/deWidget/DeNumberRange.vue
  core/frontend/src/components/widget/deWidget/DeSelect.vue
  core/frontend/src/components/widget/deWidget/DeSelectGrid.vue
  core/frontend/src/components/widget/deWidget/DeSelectTree.vue
  core/frontend/src/lang/en.js
  core/frontend/src/lang/tw.js
  core/frontend/src/lang/zh.js
Labels: 类型:优化

#7182 fix: 过滤组件首项禁用后首次手动设置默认项无法正常显示
  core/frontend/src/components/widget/deWidget/DeSelect.vue
Labels: 类型:bug

#7183 perf: 定时报告收件人数据结构
  core/backend/src/main/resources/db/migration/V59__1.18.14.sql
  extensions/dataease-extensions-view/view-bubblemap/view-bubblemap-frontend/package.json
Labels: 类型:优化

#7185 perf: 移动端token过期之后循环刷新页面
  core/mobile/src/pages/login/index.vue
Labels: 类型:优化

#7192 fix: .typos.toml
  .typos.toml
Labels: 类型:bug
